### ISSUE TITLE
Multiline Lists Documentation

### ISSUE THREAD

**Issue by crashb** [inkle/ink#10]
https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#advanced-multiline-lists

i was not able to find any section or documentation on multiline lists

**Comment by joningold** [comment]
D'oh! You're right, that somehow fell out of the documentation. We'll get that in, but for anyone checking this, the format is 
{stopping:
 -  stuff
 - other stuff
}
for sequences, and replace that "stopping" with "cycle", "shuffle" or "once" for the other kinds of lists.
