### ISSUE TITLE
Return statement in functions do not close function body

### ISSUE THREAD

**Issue by Glidias** [inkle/ink#100]
```
// Variables
VAR boutRounds=1	
VAR boutExchange=1

// for each char (tag charPersonName)
CONST charPersonName_reflex = 5
CONST charPersonName_mobility = 5
// for each char.body... parts... (tag bodyPartName)
VAR charPersonName_wound_bodyPartName = 0

// Functions
=== function showCombat()
	~ return "Round "+boutRounds+" - Exchange:"+boutExchange

=== function inflictWoundOn(target)
	~ return

=== xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  // this line divider for seperating functions is lame, because it doesn't detect ~return to enclose function body!

// Combat!
Welcome to Riddle of Steel/Song of Swords RPG Combat simulator.
Let's fight!
-> Exchange
```

`~return` statement within each function doesn't close function body! 

Without the divider hack, I get a an error which states:
`ERROR: 'tros.ink' line 26: Functions may not contain diverts, but saw '-> Exchange'`
It seems the function code extends beyond the return statement.
I understand that there will often be multiple return statements within a function as a result of switch conditions, so the return statement isn't useful in explicitly determining the function body.

Without an explicit way to enclose code within functions, am i forced to currently declare my functions at the bottom of the .ink page?

Anyway, i guess this isn't too much of an issue atm, (good to fix it though), as i'll be procedurally generating the .ink anyway, and probably resorting to include files to define functions seperately....

**Comment by joningold** [comment]
So the idea is that in general all content is inside knots; and at the top
of your file is a divert that says "this is where the story starts" (or the
game code simply points the story to the right place.) so you could make
your dividing line into a knot called "start-game"
or whatever and then point to that at the top.

Adding the functionality to auto close a function once all of its paths
have hit a return would be clever... But it doesn't really seem worth the
complexity to me?

Cheers
Jon

**Comment by joethephish** [comment]
Quite apart from the complexity, it also introduces ambiguity, and makes it
harder to check for loose ends (in normal knots specifically). As long as
every knot and function starts with a consistent syntax, we can be sure of
where the previous one is intended to end, and make sure it has been
terminated correctly.

As Jon said, any content that you want to place at global scope, either as
an introductory/setup section, or for tiny unstructured stories, or simply
to divert to the first knot, should be placed at the top.
