### ISSUE TITLE
Passed ref pointers into function affects "unrelated" temp variable in existing Knot scope

### ISSUE THREAD

**Issue by Glidias** [inkle/ink#104]
Test below

```
->adv_test_funcParamScope

=== adv_test_funcParamScope
~temp withinScopeOfKnot = 0

Value is {withinScopeOfKnot} at the moment.

{adv_testFuncParamScope(withinScopeOfKnot)}
Is Value 1? Value = {withinScopeOfKnot}

-> TestDone

=== function adv_testFuncParamScope(ref withinScopeOfKnot)
~temp x
~withinScopeOfKnot=1
{adv_testFuncParamScope2(x)}
assert pointer changed: x == 3: x = {x}


=== function adv_testFuncParamScope2(ref withinScopeOfKnot)
~withinScopeOfKnot = 3
// the above should not affect the main Knot despite having similar name, since the `~temp x` pointer was passed in!

// --------------------------------------------------------------------

=== TestDone
Test Completed!
->DONE
```

The unfortunate result:
```
Value is 0 at the moment.assert pointer changed: x == 3: x = 0
Is Value 1? Value = 3
Test Completed!
```

How it happens:
In `adv_testFuncParamScope2` function,
The  ref parameter should only affect the earlier function `adv_testFuncParamScope`'s local temp "x" variable, but it seems to affect the Knot scope under `adv_test_funcParamScope` due to a matching parameter name label with the Knot temp variable name. Also, the `~temp x` pointer that was passed in from the earlier function `adv_testFuncParamScope`, isn't affected.

Somehow, if I change the label of `withinScopeOfKnot` to something else that isn't part of the `adv_test_funcParamScope` Knot scope, it'd be fine! But shouldn't the parameter label be arbituary here? Why is there a naming collision with the function being able to access a temporary variable within the existing Knot scope due to a matching parameter name with the current Knot? All functions should be self-contained with regards to the parameters passed in from their given caller!

**Comment by Glidias** [comment]
```
// Test passed (only if ref x isn't accessed set)
=== adv_test_funcParamScope2
~temp x = 0

Value is {x} at the moment.

{adv_testFuncParamScopeXXX(x)}
knot x remains the same as zero?: = {x}

->TestDone

=== function adv_testFuncParamScopeXXX(ref x)
~temp y
// It seems, any pointer value set operation below at ~x=0 on the parameter will trigger the issue !
// Would need to set ~x only after recursive function calls are made? Weird...
//~x = 0  
{adv_testFuncParamScopeXXX2(y)}
assert pointer changed:  == 3:  = {y}

=== function adv_testFuncParamScopeXXX2(ref x)
~x = 3
```

Somehow, accessing/setting the pointer reference value and then calling the other function after that, will inadvertently cause the matching label "ref x" to reference the  Knot scope instead. When commented away (as commented) in the example above, the issue doesn't occur. Weird....a bug indeed.

**Comment by joethephish** [comment]
Verified a bug, thanks! Will investigate...

**Comment by joethephish** [comment]
Found and fixed! In master, will make it into next release. The `_` workaround is a good one for now, if a little annoying!
