### ISSUE TITLE
How to Add A Ending

### ISSUE THREAD

**Issue by TheCGMaster** [inkle/ink#107]
How do I add a ending? there is nothing in the documentation showing you how

**Comment by aloisdg** [comment]
You mean `-> DONE` ?

**Comment by TheCGMaster** [comment]
No, doing -> Done or -> End doesn't end the Talking, For example if the conversation is over i want something to happen according to what it ends with.

**Comment by aloisdg** [comment]
@TheCGMaster Sorry I didn't help. Maybe you should be more specific.

**Comment by joningold** [comment]
END will stop the flow. If you want to change what happens after the ink
stops, maybe set an ink variable to reflect what happened and then query it
from the game code?

Jon
