### ISSUE TITLE
Compiler argument -d (working directory) removed

### ISSUE THREAD

**Issue by nullObjectPtr** [inkle/ink#119]
Looks like the "-d" (working directory) argument for inklecate was removed in 0.3.5
Was this deprecated on purpose? This was a breaking change for us, all of our engine hooks were in separate files inside an "/include" subfolder so as not to clutter the workspace for our technical writers.

**Comment by joethephish** [comment]
Yeah, that was deprecated in purpose. We realised that it could be simpler and simple use the root ink file's directory as the working directory. That way the include structure should be unambiguous too.

It's possible you may need to change your include paths though if you were using the `-d` option before?

**Comment by nullObjectPtr** [comment]
Okay! No problem, as long as it was on purpose. We'll just fix up our include paths.

**Comment by joethephish** [comment]
Ah thanks! Tidied that up.
