### ISSUE TITLE
Feature request: warning for misuse of "else" in a multiline block

### ISSUE THREAD

**Issue by joningold** [inkle/ink#123]
So one of the commonest mistakes I make is this :

```
{ conditional:
    One option.
else:
   Other option.
}
```

when I intended "- else". The trouble with it is, it compiles quite happily and is difficult to scan for by eye, and can take a lot of time to hunt down.

A warning would be great, which  for this case would be straightforward - "else:" is a pretty rare piece of content for a writer to use.  

The harder issue is catching:

```
{ condition A: 
    condition B:
}
```

since `condition B:` could well be English-like. But perhaps we could issue a warning for any line of text terminating in a (non-backslashed?) colon inside a multiline block?

**Comment by joethephish** [comment]
The else thing sounds doable!

Not so sure about the condition thing, since it's common to have a piece of text following the condition, on the same line... (and as you say, it's more possible for it to be english-like).

**Comment by joethephish** [comment]
Done, in 532d6ed600fd0d7224a5f5277e78d700f5f1d40e.
