### ISSUE TITLE
Manipulate variables outside of Ink script.

### ISSUE THREAD

**Issue by cenewsom1** [inkle/ink#125]
I'd like to be able to modify the value of a global variable (ie. set hasSpoken = true) that was declared in Ink from an external C# script. It would help with being able to control the flow of the story and identify speakers that are currently holding a conversation.

Is there any functionality built in that supports this? Looking through the available functions, the closest I could get was from observing the current variables.

I appreciate any and all help!

**Comment by theuncommon** [comment]
It sounds like you're after the Setting/Getting variables logic: https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#settinggetting-ink-variables

unless I'm misunderstanding what it is you're aiming to do.

**Comment by cenewsom1** [comment]
Ah, that's it. Thanks!
