### ISSUE TITLE
Pictures?

### ISSUE THREAD

**Issue by sogen** [inkle/ink#127]
Hi, is there a way to add images?

**Comment by joethephish** [comment]
No, this is up to the individual game. You could invent your own syntax like:

`IMAGE: myAwesomeImage.jpg`

(And Parse that line when it comes through in your game.)

Or you could use [external functions](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#exernal-functions), for example:

```
EXTERNAL showImage(imageName)

// Call your image function
~ showImage("myAwesomeImage.jpg")
```

and then in your game (if you're using C#):

```
_inkStory.BindExternalFunction ("showImage", (string imageName) => {
    // load and display the image
});  
```

**Comment by sogen** [comment]
Cool, thanks @joethephish !
