### ISSUE TITLE
Conditional blocks not allowing choices

### ISSUE THREAD

**Issue by naam00** [inkle/ink#129]
Not sure if this is a syntax error on my part, or something that should work but doesn't, but the below code:

```
VAR someFlag=false

{someFlag:
    Some flag got set.
    *   [Oh dear]
        Much dear, yes!
    *   [Are you sure?]
        Quite sure, yes!
-else:
    No flag got set!
    *   [Oh dear]
        Much dear, yes!
    *   [Are you sure?]
        Quite sure, yes!
}

->END
```

... doesn't seem to work (the choices don't show up). At least not in Inky.

**Comment by facelesspanda** [comment]
Conditional choices are a different syntax. Your example could be achieved with this script:

```
{someFlag:
    Some flag got set.
 - else:
    No flag got set!
}

    *   {someFlag} [Oh dear]
        Much dear, yes!
    *   {someFlag} [Are you sure?]
        Quite sure, yes!
    *   {not someFlag} [Oh dear]
        Much dear, yes!
    *   {not someFlag} [Are you sure?]
        Quite sure, yes!
```

Though this is if you want choices in both cases. If you want the flow to change depending on variable, use diverts.

**Comment by naam00** [comment]
Thanks!

I worked around it with diverts, yes (I needed a choice segment in one situation, and just a simple statement in another). I must say it _feels_ like a workaround, but thinking about it in programming terms now, I assume there's no way Weave could work if we're allowed to cordon off choice-segments...

**Comment by joethephish** [comment]
Actually, your code was entirely valid, and you're allowed to put choices within conditionals.

The problem is with your `-> END`: it can be a little bit surprising, but `END` ensures the story really does come to an end! So, it cancels/removes any choices that exist. If you use `-> DONE` instead, it's softer, and doesn't remove the choices.

**Comment by joningold** [comment]
... Or put the END statement on a gather; that's probably what you meant;
for the story to end after the response.

**Comment by joethephish** [comment]
Good point!

**Comment by naam00** [comment]
> The problem is with your -> END: it can be a little bit surprising, but END ensures the story really does come to an end! So, it cancels/removes any choices that exist. If you use -> DONE instead, it's softer, and doesn't remove the choices.

I'm not sure I understand – ending a section with END destroys choices within conditionals? I'm completely unsure about the exact differences between END and DONE now (I thought I understood : ), I'm using END where I can because it seems to play better with tunnels (I use a tunnel setup for a testloop so I can play within Inky, in Unity the sections are triggered by things in the scene). 

I do understand the gather-remark by @joningold: the ->END as it is now is in fact read as being part of the response, even though the response gets cut off by a curly, so to say : ). Not really an obvious thing but I guess that's logical. 

Thanks!
naam

**Comment by joethephish** [comment]
This is the kind of thing `END` could be useful for. You might have some conditional options that are pulled in from somewhere, but at the moment you use `-> END`, you're literally telling the story flow that it can't continue. Necessarily then, it can't allow any options to be shown, since the story has concluded at that point.

Whereas, if you use `-> DONE`, you're telling the story flow "I'm done providing content right here". So, it is useful for marking the end of a thread, for example.

```
VAR with_alice = true
VAR drunk = true

You approach the edge of a cliff.
{with_alice:
    <- alice_options
}
{drunk:
    <> But in your drunken stupour, you step backwards onto nothing but thin air. Your fall is long, but your death is instant.
    -> END
}

== alice_options ==
* "Get away from me!"
* Say nothing
```

**Comment by naam00** [comment]
Here's why I tend to use END:

```
== mainLoop ==
	->Entry->

	->loop
	= loop
	->DisplayMenu->
	->loop
	->END

== Entry ==
Instructions go here.
Skip Intro?
	+[Yes]

**Comment by joningold** [comment]
I may have misunderstood but I don't think you need END there; since it's
below the divert to loop it'll never be processed.


Jon

**Comment by naam00** [comment]
(Sorry @joningold I hit the comment button before finishing the comment somehow, seems you got only half the reply by email : ).
