### ISSUE TITLE
inkjs: Binding External Function

### ISSUE THREAD

**Issue by ElfDecker** [inkle/ink#130]
I needed to bind external function in ink using inkjs. I am using such code in Ink:
`EXTERNAL print_enemy_stats(enemy_type)`
And such code in JavaScript:
`story.BindExternalFunction("print_enemy_stats", function(enemy_type) {
		var curEnemy = enemies[enemy_type];
		return "Health: " + curEnemy.health + "; Strength: " + curEnemy.strength;
	});`
But in Inky during compilation I have such exception:

> Ink.Runtime.StoryException: Missing function binding for external 'print_enemy_stats', and no fallback ink function found.
   in Ink.Runtime.Story.ValidateExternalBindings(Object o)
   in Ink.Runtime.Story.ValidateExternalBindings(Container c)
   in Ink.Runtime.Story.ValidateExternalBindings(Object o)
   in Ink.Runtime.Story.ValidateExternalBindings(Container c)
   in Ink.Runtime.Story.ValidateExternalBindings(Object o)
   in Ink.Runtime.Story.ValidateExternalBindings(Container c)
   in Ink.Runtime.Story.ValidateExternalBindings(Object o)
   in Ink.Runtime.Story.ValidateExternalBindings(Container c)
   in Ink.Runtime.Story.ValidateExternalBindings(Object o)
   in Ink.Runtime.Story.ValidateExternalBindings(Container c)
   in Ink.Runtime.Story.ValidateExternalBindings(Object o)
   in Ink.Runtime.Story.ValidateExternalBindings(Container c)
   in Ink.Runtime.Story.Continue()
   in Ink.CommandLinePlayer.EvaluateStory()
   in Ink.CommandLinePlayer.Begin()
   in Ink.CommandLineTool..ctor(String[] args)
   in Ink.CommandLineTool.Main(String[] args)

What I am doing wrong? Or, maybe, binding external functions isn't implemented in inkjs yet?

**Comment by joethephish** [comment]
Ah, external functions are untested in Inky right now, and will need some
extra work to make it user friendly and allow fallbacks to work so it
doesn't give you an error when running (by defining a fallback function in
ink).

The feature should be functional in inkjs, although is probably relatively
untested...

Sorry! Alpha software etc :)

**Comment by ElfDecker** [comment]
> Ah, external functions are untested in Inky right now, and will need some
extra work to make it user friendly and allow fallbacks to work so it
doesn't give you an error when running (by defining a fallback function in
ink).

The feature should be functional in inkjs, although is probably relatively
untested...

Sorry! Alpha software etc :)

Oh, I see. But this error prevents Inky from compiling, and, because of this, exporting to JS, So, is there some way to fix this error and use external functions, or no?

**Comment by joethephish** [comment]
Hrm. Yeah, sorry, I'm afraid so :-(

**Comment by ElfDecker** [comment]
Oh, what a pity. I wanted to implement my own battle system with external functions.

**Comment by joethephish** [comment]
I'll see what I can do to get it added very soon...

**Comment by y-lohse** [comment]
The way I do this so far, is I write all my stuff in inky, then paste the ink file in a text editor, add the extenal functions, and compile using inklecate. Though if you have more than a couple of externals this workflow is probably impractical.

I've tested external functions in inkjs with simple examples such as multiplying numbers, and I use a very simple one that does stuff before the story exits. It works quite well, though yeah, there might be bugs with more advanced usages :-)

**Comment by ElfDecker** [comment]
@joethephish, and what about other functions? What functions of Ink for C# aren't implemented in inkjs yet?
@y-lohse, it isn't working even in such way.

**Comment by y-lohse** [comment]
Uh, it should. I mean it does, I've done it :p. Maybe we can trouble shoot it, what's happening?

> What functions of Ink for C# aren't implemented in inkjs yet?

inkjs is on feature parity with the C# version, it's just not very battle tested yet. But if you find bugs I'm happy to investigate :-)

**Comment by ElfDecker** [comment]
@y-lohse now it all work. There was problem on side of my code. But, one more question. How can I access variables of story from JavaScript? Your `variableState` seems to be not working.

**Comment by y-lohse** [comment]
It should work exactly like described in the doc on most systems, ie. `var health = story.variableState['health'];`.
There's just a quirck if you're using an older browser where a certain javascript feature is not supported, in which case there is [this fallback function](https://github.com/y-lohse/inkjs#compatibility-with-older-node-and-browser-versions). Hop it helps :-)

**Comment by joethephish** [comment]
Actually, I take it back. Now I've experimented, fallback functions are indeed working as expected in inky. The only problem is that we don't catch the error you mentioned, so it's not clear what you're supposed to do.

If you write something like this:

```
EXTERNAL gameFunc(x, y)

Placeholder result: {gameFunc(1, 2)}

== function gameFunc(x, y) ==
~ return 5
```

So, implement your external function with an ink function, purely a placeholder for testing within inky, then when you bind a proper function to inkjs, it will use that one instead of the ink-defined one.

**Comment by joethephish** [comment]
Closing this issue, and opening one in the inky repo: https://github.com/inkle/inky/issues/37
