### ISSUE TITLE
[Discussion] External functions use cases

### ISSUE THREAD

**Issue by facelesspanda** [inkle/ink#131]
Hello,

I fail to understand the real value of externals functions.

The way I see it, Ink is a middleware language between the writer and the developpers: the writer writes the ink script, the developpers develop the game and in some ways call out for the ink script and get text to display, be it character dialogues, narration, or object descriptions.

A team may settle conventions for parsed ink lines in the game (you can see this in the Unite presentation for Ink, where character dialogues are created with a `name:` pattern), but that should be it: the ink script should process a narration flow, provide narrative info to the game, and not much more.

I can understand the use of ink functions, when you have complex character statistics that will change the narrative but not the gameplay, but external functions are functions that are executed by the actual game engine, so they resort to game development and game flow, thus have no narrative value (that I can see) and should not be called in a narrative script.

The examples that I can see here and there are examples such as `3 times 4 is {multiply(3, 4)}.` or `~image("file.jpg")` but in both cases I fail to see the point of having a bound external function: Mathematical functions can be written in the ink file, and things like displaying an image could very well be done by a text parser at the reception of ink text info.

Anyone with a light to help me see what I can't yet?

**Comment by nullObjectPtr** [comment]
It really depends on the kind of game you are making. Simpler uses if ink may not have much need for external functions. 

Games that want a tighter interaction of dialog and gameplay would need them more. On the project I am working on, external functions are absolutely essential. They were one of the primary reasons we chose Ink over others as our narrative engine.

1. Read info from an external gamestate.

A (silly) use case:
Image writing a dialog that was tailored to react to the health of a character. Characters close to death would get existential, and quote Jean-Paul Sartre all the time. A Character's health is modified during turn-based fight sequences, outside of ink control. An external function would be needed to read this data.

2. Write info to external gamestate.

Use case. A hard-to-reach part of a dialog tree would result in rewarding the character with 100 gold. Gold is spend in a shop on battle items, completely outside of the purview of ink.

**Comment by joningold** [comment]
We use them for things like unlocking routes in 80 Days, or starting off a
combat sequence in Sorcery - so things that happen mid story but aren't
story.

Jon

**Comment by joethephish** [comment]
They can also be used for functionality that are simply isn't available within ink, for example:

`The time is {currentTime()}. sin(0.5) = {sin(0.5)}.`

...or you could use them for more expensive calculations that you don't want to do within ink, or that you don't want to re-implement in ink.

**Comment by facelesspanda** [comment]
Thanks, @joethephish , that was the example I needed.

Well, to be honest, if there was no external function in Ink, for this kind of use, I would have had a simple variable, that I would set from the game with the API with something like `story.variablesState["Time"]=MyTimer.currentTime` or something.

But the sin one, yeah, complex math stuff in understandable.

And @nullObjectPtr the way I do both of your use cases is with variable setting from the game (as I just said with the time thing), and a custom text parser.
Well, it depends how you're making your game, I guess, but in my Unity game, I've created a C# `[Command]` attribute that takes a name, a pattern, and a priority, where named capture groups in the pattern are then bound with reflexion when the game is launched to the C# class's fields and properties.
So each time my parser parses a correct command, it creates an object of the correct class and sets the public fields and attributes according to the named capture groups, and it's safe to use those in the overriden `Execute()` method of the custom command class.
You could create a this class: 
```
[Command("Quake", @"^QUAKE:(?<duration>\d+)$", Priority.Normal)]
public class QuakeCommand : Command
{
    public float duration { get; set; }
    public void Execute()
    {
       //code to shake the game camera for *duration* seconds.
    }
}
```
So you can virtually tell anything to the game with just text from ink.

I much prefer this method because it doesn't need definitions and actual binding. There's a reflection lookup when the game is launched (plan to be optimized later to a build-time lookup), and then it's just tests. In most cases there are not going to be dozens of commands in a game, so tests don't take much long (when you're doing a narrative game section, you're not looking for fast paced text action anyway, so the margins are larger). External functions need to be declared, then bound, and if it's declared and not bound there are errors, and if it's bound without being declared there are errors too.

**Comment by joethephish** [comment]
Yeah, I agree, text parsing is a really nice way of doing things, and as you say, the overhead of declaring / binding / coping with errors when functions aren't bound is a good thing to avoid.

I do think that it's strongly down to personal taste/style and there being a few ways to achieve the same thing.

External functions may rarely be the best solution, but I do think they're a valuable part of ink nonetheless.

**Comment by facelesspanda** [comment]
Yeah, in the end it's a matter of what you're most comfortable with. Now I understand their values better :)

Thank you all for your input!

**Comment by micabytes** [comment]
Been away on vacation for a few weeks, but I'll just weigh in with a comment or two as I use this a lot in P&T2.

I think it really depends on how you construct your game - i.e., the balance of the narrative and the non-narrative part. Encoding stuff in the text is fine if the narrative aspect of the game is the main part, but in something like P&T2, where here is a massive game world (a typical game in P&T2 has, for example, a few hundred of game characters, each with their own states), that is not a tenable proposition.

In fact, I haven't even implemented external functions in jInk (yet), and instead simply went ahead and made game objects valid variables that allow method calls. In my use-case, a typical story snipped will usually spend the first few lines retrieving the game state required for its text. E.g.,
`
=== some_knot
VAR player = world.getPlayer()
VAR mate = world.getCompanion()
VAR friends = mate.isFriend()
"I am a {player.hasTrait("RUTHLESS"): ruthless : compassionate} person. That was {friends: fine | a point of contention} with {mate.getName()} {friends: and he readily agreed to a meeting | but he agreed to meet with me anyway}. 
`
Not the best example, but keep in mind that the companion can be any of a hundred characters with very different traits, and you can maybe see the complexity that would be involved trying to manage that in a script without composite variables..
