### ISSUE TITLE
INCLUDE not working

### ISSUE THREAD

**Issue by papataci** [inkle/ink#132]
i've tried spllitting my script into multiple .ink, but it's not working

anybody has a working example please?

**Comment by hoverbird** [comment]
Hey @papataci! Can you share an example that's working? Are all your .Ink files in the same directory? Are the file extensions correct? Are you testing your story in Inky, or some other environment?

**Comment by joethephish** [comment]
It should be fairly straightforward to get this right, especially if you're using Inky!

For example, say you have, in `main.ink`:

```
INCLUDE include.ink
This is main!
```

and in `include.ink`:

```
This is include!
```

where both files are in the same directory, it should all work.

**Comment by papataci** [comment]
you're right, i should've given an example, here
![inkincludes](https://cloud.githubusercontent.com/assets/9434229/17083886/fc75be56-51ad-11e6-966d-61634c25cbc7.jpg)
 it is in the form of a screenshot, the main.ink doesn't start the story

![Uploading InkIncludes.jpg…]()

**Comment by papataci** [comment]
ok, i found the problem: i need to call the first knot...
