### ISSUE TITLE
Project with main.ink conflicts with main.js on web export

### ISSUE THREAD

**Issue by joethephish** [inkle/ink#134]
As mentioned in #133, we should decide on a scheme for the name of the story .js file, so that it never conflicts with the template's main.js. Either we could use a consistent name for the story (e.g. story.js) or special-case it so that it only gets called story.js when there's a main.ink.

**Comment by y-lohse** [comment]
I think you meant to publish this in the inky repo? :)

**Comment by joethephish** [comment]
Oops! Thanks :-D
