### ISSUE TITLE
Crash if starts with INCLUDE or VAR

### ISSUE THREAD

**Issue by Natura-Time** [inkle/ink#136]
Hello there,

I'm on Mac and I use the terminal. When I try to include other files and/or declare variables at the beginning of my ink file, it stops immediately without any error message.
There is no syntax error and everthing is working if I put everything in one file and declare variables within a knot.

The only way to make it works with includes and declarations outside the knot is to put some text before, like this :

> Welcome to my story
> 
> INCLUDE basics.ink
> INCLUDE functions.ink
> 
> VAR hour = 0
> VAR minute = 0
> 
> -> Intro

So it's not a big deal but it should not work that way, isn't it ?

**Comment by joethephish** [comment]
Nope, you should definitely be able to put `INCLUDE` lines at the top, and that's something that we do ourselves very frequently!

Can you tell me:

* Mac/Windows/Linux?
* Where is it crashing? In Inky? In Unity? On the command line?

**Comment by Natura-Time** [comment]
It's written in the first line : I'm on Mac and I use the command line.

I compile and ... it stops immediately without printing anything.

**Comment by joethephish** [comment]
(Oh, apologies, you already said Mac + terminal in your initial message, my bad!)

This is odd, since we're on macs and not having this problem... could you try uploading a .zip of story files, and the exact line you're running in the terminal?

**Comment by Natura-Time** [comment]
[ink.zip](https://github.com/inkle/ink/files/390410/ink.zip)
I have this folder at the root so I do : ./ink/inklecate -p ./ink/eberstein/eberstein.ink

(And if you want to use it or improve it to add in documentation, I made a cheatsheet for Ink in the folder)

**Comment by joethephish** [comment]
Ah, the problem is simply that you need to divert to your first knot:

```
INCLUDE basics.ink
INCLUDE functions.ink

VAR hour = 0
VAR minute = 0

-> Intro

=== Intro ===
	It's {showTime()}.

	+ [Add 5 minutes] {addTime(5)}
	+ [Add 15 minutes] {addTime(15)}
	+ [Add 30 minutes] {addTime(30)}
	+ [Add 60 minutes] {addTime(60)}
	+ [Add 120 minutes] {addTime(120)}

	- -> Intro
```

A few people have had problems with this, we perhaps need to make it clearer in the documentation, or add a warning under certain circumstances.

The problem is that it's perfectly valid for your story to not do anything by default, since you might divert manually to specific sections within the context of a full game.

(Nice cheat-sheet!)

**Comment by Natura-Time** [comment]
Ooohh ! I see ! Thanks Sir !
You're making a great job with Ink !
