### ISSUE TITLE
Episodic Games and Saves

### ISSUE THREAD

**Issue by isakgrozny** [inkle/ink#138]
I'm grappling with this right now: I want to do an episodic game written in ink (using inkJS and implemented in something other than Unity) and I'm not sure how it'd be possible to link the episodes together and preserve choices across the whole narrative. Have each episode load the previous episode's save? Generate a file at the end of an episode with what choices were chosen and have the next episode load it, read it and set flags based on it?

Is there something simpler I'm overlooking?

**Comment by facelesspanda** [comment]
Well there's the INCLUDE feature that exists. You could for instance have `ep1.ink` with your ep1 story, and ep2.ink with your ep2 story BUT also `include ep1.ink`, so loading the story state would still work and the read-counts magic variables (ink paths for conditionals) would still be declared and valid, if you want to use those.

Though using this method, at ep5 your file's gonna be pretty huge.

I'd better have a `variables.ink` with your major story flags and everything that you think will persist (you're gonna have to do some pre-writing design to select how these flags and variables work), and populate those along the episodes. That's how I'd do it I think.

**Comment by joethephish** [comment]
On Sorcery we have some game-side code which extracts a particular (large!) set of variables to transfer between different stories. Having a `variables.ink` is a good idea, since it makes it clear the state that needs to be transferred.

One possible gotcha is that the read counts of knots/stitches wouldn't be transferred using this technique, so you need to be careful to create variables for any of those things that you specifically want to remember between episodes.

**Comment by joethephish** [comment]
(I wouldn't attempt to load the exact save JSON as it comes out of the ink engine between different story files though, we make no guarantee of compatibility between them.)

**Comment by isakgrozny** [comment]
By game-side code, do you mean an external function? I'd be interested in taking a look at it, even though I'm likely to be implementing my game with Javascript, not Unity.

**Comment by joethephish** [comment]
I mean, in JavaScript, once you're at the end of an episode, you would access each of the variables that's important for your save using `story.variablesState.$("myVariable")`.

**Comment by isakgrozny** [comment]
Aha, I see. That's handy and also pretty easy to do. Thank you!
