### ISSUE TITLE
Using variables to store divert targets

### ISSUE THREAD

**Issue by sdmolen** [inkle/ink#140]
I'm relatively new to ink and I'm struggling with a way to store a divert target into a variable. It gets a little complicated, but hopefully this bit will be enough for it to make sense.

Before reaching this knot, the player is talking to various people in a trade quest (trade this for that, and so on). Before coming into this menu, the player offers to trade, and variables are set. Each person has their own knot, which is defined like so:

```
=== TRADE2 ===
...
=COMMENCETRADE
    ~ currentSection = TRADE2
    ~ currentPerson = tradeperson2
    ~ neededItem = tradeperson2Item
    ->TRADEWINDOW
```
After which, they reach here to trade:
```
=== TRADEWINDOW ===
What would you like to give to {currentPerson}?
    + {hasJar} Jar
        ~currentItem = "jar"
        ->resolveTrade
    + {hasPicnicBlanket} Picnic Blanket 
        ~currentItem = "blanket"
        ->resolveTrade
    + {hasSandwich} Sandwich
        ~currentItem = "sandwich"
        ->resolveTrade
    
=resolveTrade
// /* For debugging
List Section: {currentSection}
List Person: {currentPerson}
List Item: {currentItem}
List Needed Item: {neededItem}
// */
{
    -currentItem == neededItem: -> currentSection.SUCESSS
    -else: -> currentSection.FAILURE
}
```

This is the output: 
> I might have something for you.
> 
> Frowning pirate: Arg, let's see what ya have.
> 
> What would you like to give to Frowning pirate?
> 
> Sandwich
> 
> List Section: 1
> 
> List Person: Frowning pirate
> 
> List Item: sandwich
> 
> List Needed Item: sandwich
> 
> Line 154: Tried to divert to a target from a variable, but the variable (currentSection) didn't contain a divert target, it contained '1'.

I'm not understanding why currentSection is coming back as a 1. Is there a way to store a knot's address as a variable?

**Comment by joethephish** [comment]
If you simply use the name of a knot like this:

`VAR myVar = knotName`

...then what you're actually doing is getting the read-count of that knot. Useful checking whether you've read it, or whether you've read it more times than some other knot. Since we wanted to make that as lightweight as possible, it comes at the expense of being surprising if you're doing what you're trying to do!

So, to fix it, what you need to do is:

`~ currentSection = -> TRADE2`

When debug printing, it should come out as `DivertTargetValue(TRADE2)`.

**Comment by sdmolen** [comment]
Awesome answer! Thank you!

**Comment by sdmolen** [comment]
I can divert to a knot, but not a thread of that knot. Let's say I have this:
```
=== TRADE1 ===
...
=SUCCESS
=FAILURE
=== TRADE2 ===
...
=SUCCESS
=FAILURE
=== TRADE3 ===
...
=SUCCESS
=FAILURE
```
And I'm using a variable like current section to keep track of where they're at while they go through the knot TRADEWINDOW. However, when they're done, I want to push them to a thread SUCCESS or FAILURE within the respective knot. As of now, I'm resolving this as such:
```
{ 
    -currentItem == neededItem: -> currentSection.SUCCESS 
    -else: -> currentSection.FAILURE 
}
```
Instead of taking me to thread I'm trying to get, it instead pushes me to the beginning of that knot. Is there any way to resolve this through this method or is it kind of stuck like this for now?

**Comment by joethephish** [comment]
Ah, no, I'm afraid you can't mix the variable part and the "static" part of the divert. You've have to do something like:

```
VAR currentSection = -> knot
VAR sectionSuccess = true
-> currentSection

== knot ==
This is the knot.
{sectionSuccess:-> SUCCESS|-> FAILURE}

= SUCCESS
Success!
-> DONE

= FAILURE
Failure :-(
-> DONE
```

Sorry... probably not the answer you were hoping for. @joningold, maybe you have a more elegant idea for this one?
