### ISSUE TITLE
Possible bug regarding retrieving bools using 'variablesState'?

### ISSUE THREAD

**Issue by Azurelol** [inkle/ink#142]
Hello! I started using Ink recently, been working on integrating it in my Unity project. I apologize if the following is not a bug but I am confused regarding what I am seeing.

Given the following variables in an ink file:
**VAR BoolVar = true
VAR IntVar = 5**

When I try to access them through Ink.Runtime.Story.variablesState, it works for the integer one. Attempting to do so with the boolean like so...
**var boolVal = (bool)Flags.variablesState["BoolVar "];**
... gives out the following error:
**InvalidCastException: Cannot cast from source type to destination type.**

Is this intended?

Edit: I forgot to mention that if I just try to print the resulting uncasted return object, it will be as an integer. In consequence, it does work if I use System.Convert.ToBoolean.

**Comment by joethephish** [comment]
Internally, booleans in ink aren't are separate type, they're just integers, so you'll need to convert I'm afraid!
