### ISSUE TITLE
Text not displaying?

### ISSUE THREAD

**Issue by royda** [inkle/ink#151]
Good day. I've looked for info regarding the following issue in the docs and came up empty. Maybe you all can provide insight? This works: 
```
=== do_stuff ===
    *   [Organize]
         Organize stuff
    *   [Jump]
        Jump up and down
    *   [Throw]
        Throw a ball
- -> END
```

This does not work:
```
VAR abc = false
VAR xyz = true

=== do_stuff ===
    *   [Organize]
        Organize stuff
    *   [Jump]
        Jump up and down
    *   [Throw]
        Throw a ball
- -> END
```

There are no errors, but the choices in the 2nd example do not show. What obvious thing am I missing? Thanks!

**Comment by y-lohse** [comment]
IIRC you need to divert to `do_stuff` manually in the second case (because of the variable declarations). Try something like

```
VAR abc = false
VAR xyz = true
-> do_stuff 

=== do_stuff ===
    *   [Organize]
        Organize stuff
    *   [Jump]
        Jump up and down
    *   [Throw]
        Throw a ball
- -> END
```

**Comment by joethephish** [comment]
Yup, that's right @y-lohse. This has confused a few people, it may be worth making the two examples above work the same.

So, I'd propose that we change the behaviour so that:

----

`Hello world`
...prints "Hello world"

----

```
== hello ==
Hello world
```

... does nothing

----

```
-> hello
== hello ==
Hello world
```

... prints "Hello world".

**Comment by y-lohse** [comment]
I wonder if that wouln't end up confusing more people? The default to first knot keeps things relatively simple for a beginner.
I also think you only run into this issue by the time you start adding variables, so maybe repeating the warning about the default knot at that stage of the tutorial might be enough. I don't have a strong opinion on this either way :-)

**Comment by royda** [comment]
I think your suggestion makes sense @joethephish. Actually that's really the way it is right now, no? Right now, without variables the first knot auto-executes for some reason. Why is that first knot so special when there aren't any variables? :) The idea has a :+1: from me

Also, thanks for the help gents!
