### ISSUE TITLE
Day progression and time of day functions?

### ISSUE THREAD

**Issue by isakgrozny** [inkle/ink#154]
This is more of a game code question than anything, but I can't think of anywhere else to ask and it's something I've been struggling with for a little bit.

I'm trying to figure out how to implement a time passing mechanic in my game - so that one knot/storylet/chunk of story can take a predefined amount of time and advance the in-story clock by that amount of time. So, say, there are 24 turns available in a day and a given choice takes up 3 hours (3 turns). Doing that choice would reduce the number of available turns to 21. When the total turns reach zero, the next day begins (and the game increases the day count variable, to keep track of how many days have passed).

I also want it to work out so I can ask the game for the time and calculate whether it's morning/evening/day/whatever based on that, so I can vary what events are available at certain in-game locations based on the time of day.

I'm really not sure how to go about doing this. Also, I would probably be implementing this with JS and inkJS, not C#, so if the solutions are external to ink, that's the language I'm using.

**Comment by micabytes** [comment]
Haven't checked the syntax, but basically something like this?

```
VAR hour_of_day = 0
VAR day = 0

=== pass_time( hours_passed )
~ hour_of_day = hour_of_day + hours_passed
~ days_passed = hour_of_day / 24 
{ days_passed > 0:
    ~ hour_of_day = hour_of_day - (24 * days_passed)
    ~ day = day + days_passed
}
```

**Comment by isakgrozny** [comment]
Aha, thank you! That was immensely helpful and set me on the right track.
