### ISSUE TITLE
Discussion: Optional list elements

### ISSUE THREAD

**Issue by jkant** [inkle/ink#156]
I was wondering if there was a way to achieve the functionality I am attempting here:

=== function syn_happy() ===
{~Happy|Delighted|{_fromThe70s:Jazzed}}

The problem with the above example is that if a character is NOT from the 70s, there is a chance that nothing will be returned, where I really just want it to return either Happy or Delighted.

Is something like this possible through other means? If not, it would be a great feature... :))

**Comment by joethephish** [comment]
I guess you want something like:

`{~Happy|Delighted|{_fromThe70s:Jazzed|Something else}}`

or: 

`{_fromThe70s:Jazzed|{~Happy|Delighted}}`

...?

**Comment by jkant** [comment]
I think the way to get the functionality I'm looking for would be to do something like:

`{_fromThe70s:{~Happy|Delighted|Jazzed}|{~Happy|Delighted}}`

But this would start to get very unwieldy as more synonyms and character attributes are added -- basically you would have to maintain a separate list of adjectives per character, regardless of how much crossover between them there may be.

**Comment by joningold** [comment]
You can work around it nicely with a function

== function happy
{~Happy|Delighted|{_fromThe70s:Jazzed|{happy()}}}


Cheers
Jon

**Comment by jkant** [comment]
Ah, nice idea - thanks for that one!
