### ISSUE TITLE
Story Variables

### ISSUE THREAD

**Issue by bateramos** [inkle/ink#16]
Hello, first of all, love this project. Very easy to use!

I'm creating a game that is very moldable, and I was trying to get all variables that were created on Ink and pass to a callback method when the -> END is reach.

I'm having difficult because story.variablesState hides his keys and I can't iterate to get all variables.
Just wan't to know if this has some reason or just that none one had this necessity before. If you're ok, i can modify this, exposing this class's keys.

**Comment by MattConrad** [comment]
I'd also like to be able to get (and also set, probably) all the story state at once. I was imagining direct access at any time, slightly different from what bateramos is saying, but +1 to the general idea.

Also, thank you very much for making **ink** available and free. Wow!

**Comment by joethephish** [comment]
@bateramos Yep, I'd be happy to expose the keys. I wonder what's better though - that, or implementing `IEnumerable`? Any opinion either way?

@MattConrad What's your use-case for getting/setting the entire set of variables all at once?

**Comment by bateramos** [comment]
@joethephish  I was thinking in implementing IEnumerable. I think that solve all of my "problems".

@MattConrad I think that if you want to set, it most be by a method. I think direct access can de dangerous because it can expose the complexity of this implementation. And also you can hold by mistake a Story reference from the GC by mistake.

**Comment by joethephish** [comment]
Great, well feel free to submit a pull request if you get `IEnumerable` working on `VariableState`.

Also agreed about wrapping the variable access, and I'm not entirely comfortable with even passing in an entire Dictionary of variable state. With `IEnumerable` you could still do this by hand if you really wanted to. I should also say that we have a variable observer system - an event that fires every time a variable is changed, so that would have to be supported either way.

**Comment by MattConrad** [comment]
I don't have any specific use case (or even a project yet). Only an idea that I might have multiple parts of a game modifying ink-relevant state, it might be handy to make or receive changes as a group, and I didn't see a way to do this easily.

(For updating, I had actually imagined a method accepting a dictionary, but I didn't say that too clearly.)

I'm happy to watch what happens here, this is moving way more quickly than I am. If I run into a specific scenario later where I think more is needed I'll open another issue or send a pull request.

**Comment by jjsonick** [comment]
I don't need to get/set the variables all at once, but I definitely need some form of IEnumerable for things I'm thinking regarding dynamic inventory, characters and items that move to different rooms/scenes, etc. - could be done with oodles of booleans everywhere but IEnumberable / Lists would be much better.  I'd be glad to test any implementation of that someone comes up with.

**Comment by joethephish** [comment]
The IEnumerable pull request is now merged!
