### ISSUE TITLE
Feature: Built in enum/flag/symbol system

### ISSUE THREAD

**Issue by joethephish** [inkle/ink#178]
Some kind of feature that combines the capabilities of standard enums, flags and perhaps Ruby-style symbols (effectively lightweight immutable strings that are treated like simple values). 

Perhaps implemented as a variable type that's stored internally as a `HashSet<string>`? Though it should also be possible to assign sequential int values to the enum values, so perhaps not.

@joningold has also been playing with a state machine internally which can store multiple pieces of concurrent state in a single value. I wonder if we can support something like this natively.

Ideally, I'd like to find an elegantly simple approach that can be implemented as a single feature that doesn't add too much bloat to the runtime.

Including _all_ of the above might be a moon-on-a-stick, but it's a just a brain-dump!

**Comment by joningold** [comment]
On the state machine stuff - I think what I've been playing with could
largely be achieved by adding the arrays of named "settable" enums; ink
could then look through the array to work out where in the "state list"
it's got to. (Although, I'd need arrays of these arrays to replicate what
I'm doing right now)

Jon

**Comment by facelesspanda** [comment]
Aren't `LIST`s kind of solving this ?

**Comment by joethephish** [comment]
Ah yes, that's exactly what those are :-) Closing!
