### ISSUE TITLE
Issue with labels

### ISSUE THREAD

**Issue by Fahrengeit** [inkle/ink#18]
Hello!
Studying the Ink now, testing examples that are in tutorial. And stumbled on some issue with labels, that exist in your own example, maybe it will be helpful: 
>  - (opts)
>     *   'Can I get a uniform from somewhere?'[] you ask the cheerful guard.
>         'Sure. In the locker.' He grins. 'Don't think it'll fit you, thought.'
>     *   'Tell me about the security system.'
>         'It's ancient,' the guard assures you. 'Old as coal.'
>     *   'Are there dogs?'
>         'Hundreds,' the guard answers, with a toothy grin. 'Hungry devils, too.'
>     // We require the player to ask at least one question
>     *   {loop} [Enough talking] 
>         -> done
> - (loop) 
>     // loop a few times before the guard gets bored
>     { -> opts | -> opts | }
>     He scratches his head.
>     'Well, can't stand around talking all day,' he declares. 
> - (done)
>     You thank the guard, and move away. 

What happens here, entering the "loop" label doesn't increase count (how many times we entered this gather), so choice [Enough talking] never appear - Ink thinks that loop == 0. Problem disappears, if we add symbol before list of diverts. So I think issue is with immediate divert in gather -  without at least one symbol Ink doesn't increase count for label.
It is not critical one, but if this is really an issue, maybe you can warn others about it till it'll be fixed.

By the way, very good project. Waited for it since the announcing and it totally worth the waiting, thanks for making it available.

**Comment by joethephish** [comment]
Thanks, good catch, including the workaround! For reference, here's a more minimal repro:

    - (opts)
        *   x
        *   {loop} [This opt should appear second time] 
            -> END
    - (loop) 
        // <- Add content here and it's fixed
        { -> opts | -> opts | }
        y

**Comment by joethephish** [comment]
Fixed in dbdd7f73b2b9d105d4bc6d4a816bb03d6df52f04.
