### ISSUE TITLE
How to return multiple variables?

### ISSUE THREAD

**Issue by royda** [inkle/ink#181]
Hey all,

I know that "return X" will return a variable from a function, but does Ink support the returning of multiple variables? I've gone over the doc several times and maybe I'm blind, but I can't find any reference to it.

Thank you

**Comment by joethephish** [comment]
Something like this?

```
VAR a = 0
VAR b = 0
VAR c = 0

Returned {var_ref_test(a, b, c)}, and referenced variables are now a = {a}, b = {b}, c = {c}.

== function var_ref_test(ref x, ref y, ref z) ==
~ x = 1
~ y = 4
~ z = 9
~ return 15
```
