### ISSUE TITLE
High CPU usage on Mac Builds running on El Capitan

### ISSUE THREAD

**Issue by foopod** [inkle/ink#185]
<img width="285" alt="screen shot 2016-09-20 at 9 39 38 am" src="https://cloud.githubusercontent.com/assets/3768616/18650071/1c4e770e-7f17-11e6-9dc5-e62822839f98.png">
The Inky Editor runs very slowly due to high CPU usage. I have tried both the 0.4.0 and 0.4.1 builds, but the issue persists. This only happens when working from a saved file, if I open the editor with a new file everything runs fine until I save it.

OSX El Capitan (10.11.6)
MacBook Pro (Retina, 13-inch, Early 2015)
2.7 GHz Intel Core i5
8 GB 1867 MHz DDR3

**Comment by joethephish** [comment]
Thanks for the report! Would you mind re-posting in inkle/inky? Thanks!

**Comment by foopod** [comment]
Just noticed I raised it on the wrong repo. Thanks!
