### ISSUE TITLE
Can't save a project in inky

### ISSUE THREAD

**Issue by Mitinuru** [inkle/ink#190]
Inky freezes after I try to save the project. I can give project a name, but after that nothing happens and Inky does not react anymore.

How can I prevent this behavior?

**Comment by joethephish** [comment]
Sorry to hear this! Can I ask what OS you're using? Anyone else having this issue?

**Comment by Mitinuru** [comment]
Hi again!

I have Windows 7, and it seems that the issue solved itself after Windows update and downloading inky. I still don't know what went wrong, but I am happy it works now.
