### ISSUE TITLE
How do I define the story's title? And the author?

### ISSUE THREAD

**Issue by rscarrasco** [inkle/ink#192]
When I exported a test story to web, I noticed that the contents of the `<title>` and the  first `<h1>` was the file name without the `.ink` extension. How can I change these values? And since we're already here, is there a way to set the author too?

**Comment by joethephish** [comment]
The intent is that you customise the HTML and JavaScript that's been generated, other than the <yourStory>.js which is your actual content exported by inky.

Having said that, there's future plans to allow you to specify this in a tag - see #122 for details.

**Comment by rscarrasco** [comment]
Ok then, thanks, @joethephish!
