### ISSUE TITLE
Feature request: Tunnels can override their return point

### ISSUE THREAD

**Issue by joningold** [inkle/ink#199]
New syntax: 

`->-> go_here_instead`

The knot-name following the `->->` is an "override" to the return. This causes the game to return from the tunnel, but then immediately divert away to `go_here_instead`, instead of continuing the flow as normal.

Use case: The following option might appear in several locations of the game:

`* [Go to sleep] -> sleeping -> `

But sleeping might have the following code:

```
=== sleeping == 
 { shuffle:
     - You sleep, and then wake. ->->
     - You sleep, but wake to find yourself somewhere new.... 
        ->-> woken_up_in_ 528_AD 
 }
```

...which allows a sleeping player to be surprise-teleported.

**Comment by joethephish** [comment]
Included in 311aef73ce1779c7fdd6df5b8dbd7ee37d16badb.
