### ISSUE TITLE
Strange character encoding bug?

### ISSUE THREAD

**Issue by sequitur** [inkle/ink#204]
While working on an experimental web frontend for inkjs, I found that JSON.parse was choking on the json files that inklecate outputs, at least when those files are inlined in the html itself. The error was pretty obscure: Unexpected token at position [some low number], meaning somehow the JSON parser had choked in the whitespace (or apparent lack thereof) between the end of the opening script tag and the open curly brace of the Json itself (!!!).

This issue can be worked around in one of three ways: Running the resulting JSON through a validator, which seems to clean it up, or running it through String.trim() (this is in javascript, of course), or just manually deleting the start of the file in a text editor and re-adding that opening {.

Looking at the output from inklecate in a hex editor shows the culprit: the first three bytes (EF BB BF) before the actual { (7B, for those of you who don't have an ASCII table handy). I have no idea what those three extra bytes are supposed to be or where they come from. Is Inklecate's output supposed to be in an encoding other than UTF-8?

**Comment by joethephish** [comment]
It's a byte order mark: https://en.wikipedia.org/wiki/Byte_order_mark

However, you're not the first to have issues with this. I had never seen it before another user requested that we add it, because it can help compatibility in some situations (argh, I can't remember what exactly though, which isn't very helpful!)

But given there have been several reports of incompatibility *because* of the BOM, I think this is the final straw - we should remove it!

**Comment by joethephish** [comment]
Hmm, although see this quote from that article on Wikipedia:

> Microsoft compilers and interpreters, and many pieces of software on Microsoft Windows such as Notepad treat the BOM as a required magic number rather than use heuristics. These tools add a BOM when saving text as UTF-8, and cannot interpret UTF-8 unless the BOM is present, or the file contains only ASCII bytes.

So, it'll apparently entirely break on Windows in certain potentially common apps. The flip side is that some software on other platforms won't manage to load it (though it's *relatively* uncommon in my experience). And some developers like you would have to strip it by hand (by doing something like `data = data.replace(/^\uFEFF/, '');`).

Would be interested to hear anyone's thoughts on this!

**Comment by sequitur** [comment]
I'm fine with leaving it as is if taking it out potentially breaks other stuff; stripping it out before inlining it into the html file is easy enough to do, though maybe it's worth leaving a note in the documentation because the BOM will choke some JSON parsers in some cases (for instance it looks like Node's fs.readFile doesn't automatically strip BOMs, so if you were making say an Electron-based inkjs interpreter you might run into problems).

**Comment by joethephish** [comment]
Yeah, it's annoying that it's not standardised given it's such a basic format (come on, text!)

But yeah, agreed, better to leave it in, sigh.
