### ISSUE TITLE
"Bug": Not is greedier than one might expect

### ISSUE THREAD

**Issue by joningold** [inkle/ink#208]
This is unfortunate: 
```

- (top)
    { top <= 3 }    is TRUE
    { not (top > 3)}  is TRUE
    { not top > 3}  is FALSE 
    
```

**Comment by joethephish** [comment]
I'm afraid this is "works as intended". You re-write it as `!top > 3`, or to use another comparison operator that makes more sense `!true == false`. `not` should definitely bind more tightly than a comparison operator I'm afraid...

**Comment by joningold** [comment]
I feared you might say that :) always a shame when syntactic sugar, um,
comes back to rot your teeth

Jon
