### ISSUE TITLE
Ink does not support accentuated characters

### ISSUE THREAD

**Issue by rubereaglenest** [inkle/ink#21]
Hi guys,

I've tested the thing in Windows and Inklecast does not support accentuated characters. They are always substituted by a ? character.

In the beginning I though it could be just a thing of the inklecast build in windows, but simply, if I export the source to JSON, the output still does not support that special characters.

So this basically means we could not create games with Ink in any language different than English. That is, no Spanish, no French, no Russian, etc.

That's all, good work, I'm enjoying studying Ink a lot. Regards.

**Comment by Fahrengeit** [comment]
You should change the Encoding of your file. If it is ANSI, than there will be no other languages, yes. If you'll change to UTF-8, for example, everything should work. 
In cmd it still won't show up if you don't change the encoding in command line itself. You should use "chcp" for changing encoding, ex. for UTF-8: chcp 65001
I've tested it only in Russian, but can't see a reason why it shouldn't work with other languages. Give it a try.

**Comment by rubereaglenest** [comment]
Awesome! it works! Thanks a lot. I'm a disaster with this kind of things.
