### ISSUE TITLE
Running Ink on Windows

### ISSUE THREAD

**Issue by lando7** [inkle/ink#217]
Forgive this newbie question.
How do I run Ink on my PC?
I have gone through the build steps and everything is where it was said to be and I have .NET.

I am new to programing thats why I thought Ink would be a great oppurtunity to write interactive fiction along with Unity, but I can't figure out how to run Ink. When I try to open inklecate.exe a window flashes open but it immediately closed. What am I doing wrong? Can I use Inky if the build is done right for Ink?

**Comment by Stratege** [comment]
inklecate.exe works via commandline arguments. Open a commandshell (cmd.exe being the default on Windows) then navigate into the folder with inklecate.exe and run it via simply typing inklecate.exe and pressing enter. This will display various options, presumably you want -o which compiles your ink file for later use. And for a very simple text interface add -p as param as well. 
How one properly gets Ink to integrate with Unity is something someone else has to answer though.

**Comment by lando7** [comment]
@Stratege Thanks for the help!
