### ISSUE TITLE
Conditional actions and removal of impossible choices

### ISSUE THREAD

**Issue by Snayff** [inkle/ink#223]
Hi Everyone,

I have just been making my initial foray in to Ink and have been playing with the tutorial/documentation. Unfortunately, I am not a confident coder and I am hoping you can point me in the right direction. I am currently using a custom language (made on commission!) for an interactive fiction type game. In that I am able to create conditionals for each action and if the action is not possible it will remove the choice before the player sees it. However, I would like to make use of Ink for all of the other wonderful extras. 

(rough) Example:
- You see a stone in front of you.
-  (if Strength > 5) Lift the stone
  Walk around it.

Any suggestions on how I would implement this in Ink? Or something similar? Any support would be greatly appreciated! Apologies if I have missed something really obvious!

**Comment by Stratege** [comment]
very simply actually:

VAR Strength = 6

You see a stone in front of you.
  * {Strength > 5} Lift the stone
  * Walk around it.

try it with Strength set to higher than 5 and lower or equal to 5 to see the difference. The condition code can be more complex if desired.

**Comment by Snayff** [comment]
That's so simple! It does it for me! 👍  Thank you very much, Stratege.
