### ISSUE TITLE
Multiline, multi-condition if statements break if there's no newline after the opening brace

### ISSUE THREAD

**Issue by hoverbird** [inkle/ink#224]
This seems like unintended behavior. The following code causes an error on Line 3 ("Expected an '- else' clause here rather than an extra condition.")

```
"Hello," { - playerLocation == COUNTER:
    <> I say as I kick my feet on the counter.
 - playerLocation == HALLWAY:         
    <> I say as I lean into the hallway.
 - else:
    <> I say with a smile.
}
```

but the following code works fine:

```
"Hello," { 
 - playerLocation == COUNTER:
    <> I say as I kick my feet on the counter.
 - playerLocation == HALLWAY:         
    <> I say as I lean into the hallway.
 - else:
    <> I say with a smile.
}
```

We were happy to figure out what the issue was, and it's easy to work around, but I'm reporting it here in case it trips up other people. Thanks again for all of your work in designing and polishing Ink— everyone who's used it at Campo is in love with this tool!

**Comment by joethephish** [comment]
Oh dear. So, I was very proud of my conditional syntax, where multiple styles of if-like statements and switch-like statements are rolled up into almost exactly the same syntax, but it seems to be causing issues as a result of the similarity between them :-(

Unfortunately in your first example, the reason for the error is that your first "branch" is actually a value, in this style of statement:

```
{ didnt_vote:
     Terrible, terrible consequences.
  - else:
    A smidgeon of hope.
}
```

i.e. it's a simple "if/else" clause. But in your case, the value at the initial expression is `-playerLocation == COUNTER` - i.e. negating the value of `playerLocation`, then comparing it to `COUNTER`, giving a boolean (which is stored in ink as an integer). So your leading dash-style bullet is actually interpreted as a negation.

Note that the "initial expression to use for comparison" is also used in switch-style statements (just in case you aren't already confused):

```
{ x:
   - a: x is equal to a
   - b: x is equal to b
   - else: x is equal to something else
}
```

...but what you're looking for is a conditional without the initial value for comparison, hence needing the initial newline:

```
{
    - expr1: Expression one is true
    - expr2: Expression two is true
    - else: Something else is true
}
```

**Comment by hoverbird** [comment]
Ahh, I think I'm only now grokking that the "simple" inline if statement (with no `-`) is really a switch statement. I read that in the README but didn't fully get it. I think that's pretty nice, actually! 

I wasn't aware that `-` did double duty as logical NOT, which I think might actually be more confusing & problematic than the switch/conditional similarity. But I digress.

Thanks for explaining what's going on!

**Comment by scotthammack** [comment]
I know this is from four years ago, but I'm here because we've gotten tripped up by this a couple of times too. I think this behavior should be considered a valid bug. The documentation for extended if/else blocks claims that "as with everything else, the white-space is purely for readability and has no syntactic meaning." But in this case, that's not true; the presence or absence of a newline does change the meaning. If nothing else, a caveat in the docs would be helpful.
