### ISSUE TITLE
[Crash] Tunnel forward to parametrised stitch crashes

### ISSUE THREAD

**Issue by joningold** [inkle/ink#229]
```
-> b ->  

=== b === 
    ->-> a(true)

=== a(x) ===
    {x} 
    -> END
```

Crash caused by the parametrised "tunnel back to a" statement

**Comment by joethephish** [comment]
My hazy memory about this is that it would be significantly more difficult to implement parameters, but I'll look into it. At the very least it shouldn't crash, certainly!

**Comment by joningold** [comment]
It's not actually too hard to work around, you just do

->-> next
- (next) -> a(true)

instead. But as you say, it shouldn't crash ;)

jon

**Comment by joethephish** [comment]
Right, yes, my hazy memory was correct, it was quite tricky, but now done / supported! (Commit fb300dc5a65eb1ee602abe7695c56e18e7aec8a6)
