### ISSUE TITLE
List expressions?

### ISSUE THREAD

**Issue by hoverbird** [inkle/ink#234]
I've been finding myself needing to store the output of a shuffle in a variable— for example, in a stitch with some randomness, I want to be able to reference the results of the shuffle in more than one place. 

One workaround for this is to wrap the shuffle in a function, and then have each element be a `return` statement with the desired content, and then `~ temp my_randomized_reusable_content = shuffleThatList()`.

This works fine, except when the shuffled content contains diverts— then I'm stuck, since diverts can't be used within a function.

**Comment by joningold** [comment]
Lists would totally be useful; in the meantime I generally work around this
using enums; so I use a shuffle in a function to return a number which I
store, then pas that as a parameter into other functions/tunnels that
contain the actual content I'm using. (Tunnels are a good way to call up
blocks of content that need diverts.)

If you don't mind repetitions, you can also just use RANDOM(x) to generate
a random number.

Jon
