### ISSUE TITLE
Trojan detected when downloading 0.6.3

### ISSUE THREAD

**Issue by angusmf** [inkle/ink#237]
I'm unable to copy inky or even the source code for the unity integration to my machine without windows 10 defender telling me there is a Trojan and removing it. Here is the info page for the virus:
https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fPeals.A!cl&threatid=2147690472&enterprise=0

**Comment by y-lohse** [comment]
From that page : 

> NOTE: On December 6, 2016, an incorrect detection for our cloud-based protection for Trojan:Win32/Peals.A!cl was identified and immediately fixed. To ensure that this issue is remediated, you can do a forced daily update to download your Microsoft antimalware and antispyware software. For details, see Updating your Microsoft antimalware and antispyware software.
