### ISSUE TITLE
Erros with Inky compiler on linux

### ISSUE THREAD

**Issue by cacaudomal** [inkle/ink#241]
![errorinky](https://cloud.githubusercontent.com/assets/24619847/21285874/f9deb094-c42b-11e6-9c96-236e3891cb89.png)

I'm using Ubunt 16.04 and wine 2.0
I've tried all the solutions posted on the site and some more.

**Comment by neuroneuro15** [comment]
I have the same issue, with version 0.7 on Ubuntu 16.04.  It seems to be referencing a .exe file--isn't this only for Windows?

**Comment by Mastodon-** [comment]
Installing mono seems to get rid of the problem (no need to install wine in my experience...).

**Comment by arranf** [comment]
I needed to install `mono-complete` as opposed to `mono-runtime`.
