### ISSUE TITLE
Compiler failing breaks  .ink file 

### ISSUE THREAD

**Issue by freejsf** [inkle/ink#243]
Using the Unity (5.5.03f) Ink integration on Windows. I tried to compile the file to JSON in the Ink Editor (not in Unity), the compilation failed with a

> Ink Compiler timed out for .../Hansel and Gretel/Hansel and Gretel/Assets/Story/Ink/Hansel and Gretel.ink.
> . Check an ink file exists at this path and try Assets/Recompile Ink, else please report as a bug with the following error log at this address: https://github.com/inkle/ink/issues
> Error log: 

The file does exist at that adress. The Ink file itself looks afterwards as if all otherwise hidden markup signs like "\\n" etc are added:

`",{"->":"kill_time"},{"#f":7}]}],["ev","str","^I shrug.","/str","/ev",{"*":".^.c","flg":20},{"c":["^\"Hansel, maybe they will, maybe they won't. Probably too soon to be sure?\" I answer indecisively, well aware of the bitter truth.","\n","\n",{"->":"kill_time"},{"#f":7}]}],{"#f":3}],"what_now":["^\"So what do we do now?\" he asks.","\n",["ev","str","^You know what.","/str","/ev",{"*":".^.c","flg":20},{"c":["^ \"Same as last time\" I say, \"we wait for the moon to rise and then follow your trail back to our home.\"","\n","\n",{"->":"break_up"},{"#f":7}]}],{"#f":3}],"kill_time":["^We keep waiting a little longer. Eventually Hansel sits down, tears in his eyes he says quietly:","\n","^\"I know they're not coming back.\"","\n","^I don't know what to say. He is right. ",{"-`

Recompiling doesn't help.
No sure what I did wrong - possibly never compile in the Ink editor?

**Comment by joethephish** [comment]
Some of the things you're describing are a bit confusing/contradictory, perhaps it's a confusion over terminology:

* You say you're trying to compile the file to JSON in the "Ink Editor" (Inky, right?) - but the compilation error message looks like it comes from the Unity integration plugin. If you don't want to compile via Unity (why not?) then you can switch it off on the InkLibrary.
* You say "the ink file itself" - but the excerpt is from the compiled JSON.

As for the error itself (from Unity) - not sure I'm afraid! Can you post the ink file that causes the error?

**Comment by freejsf** [comment]
Thank you for answering so quickly and sorry, if my post was confusing. Youare right with your assumptions and I just realized what I did wrong:

When going on Export file to JSON in inky, the default choice windows gives me, is to overwrite story.ink
If I confirm that, I have the exact result I got: 

The data that's supposed to go into the JSON file goes into the ink file, which leads to a compiler crash in Unity when trying to recompile.
