### ISSUE TITLE
How to set a global variable as a "divert" statement, from Unity that is.

### ISSUE THREAD

**Issue by AntoineIturbide** [inkle/ink#246]
_Hi, I'm using Ink for a school project alongside Unity._
_This is a really great library I'm thankful for._
_Please, continue improving it._
_Thank you to for your hard work._

_Now to the issue..._

In the ["Running your ink" documentation](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#settinggetting-ink-variables) you well explained how to set Ink global variable as both the **int** and **string** types from within Unity, but I couldn't find a way to set a global variable has a **"divert" statement**. [Although it's possible from the Ink file](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#advanced-storing-diverts-as-variables), I'd like to know how to do the same **from Unity**.

**Comment by joethephish** [comment]
Yes, I'm afraid it's not possible right now :-( you can *get* a divert target and it casts it to a string, but you can't set one. Sorry!

**Comment by cduquesne** [comment]
Hi,
I think it's doable by changing the accessibility level of the 'Path' class from Ink assembly, but it's probably not recommended ? (as divert target are Path)

**Comment by AntoineIturbide** [comment]
It's ok, thank you for your time @joethephish.

I did as you said @cduquesne and it works very well, for my purpose at least. Thank you very much.

### For those who would like to do the same thing :

#### Setup :
I went on the `Path.cs` file and changed the `Path` class from `intern` to `public` (with the associated dependency changes). Also, I added `using Path = System.IO.Path;` to files that had ambiguity errors because they where using the `System.IO.Path`.

#### The Ink file :
```
VAR DIVERT = -> fail

The narative starts.
-> DIVERT

=== fail
You weren't able to set the DIVERT variable as a "divert".
-> DONE

=== succes
You successfully set the DIVERT variable as a "divert".
-> DONE
```

#### The c-sharp script :
```
using UnityEngine;
using Ink.Runtime;

public class DivertTest : MonoBehaviour {
    
    public TextAsset inkJSONAsset;
    private Story story;

    public void Start() {
        story = new Story(inkJSONAsset.text);

        Path newDivert = new Path("success");
        story.variablesState["DIVERT"] = newDivert;

        if (story.canContinue) {
            Debug.Log(story.ContinueMaximally());
        }
    }
}
```
