### ISSUE TITLE
Including a file in a parent directory

### ISSUE THREAD

**Issue by wilg** [inkle/ink#247]
Is this supported? I've tried `INCLUDE ../shared.ink` and `INCLUDE ./../shared.ink` and various other things. The first one seems to work in Inky. Couldn't tell exactly from the code whether it's intended to work in Unity.

**Comment by joethephish** [comment]
It's not "officially" supported... if it works in some places and not others, it's probably just a side-effect of the way the specific file handling API works in the target environment (.NET v.s. Node).

**Comment by wilg** [comment]
It would be a useful feature, my use case is including a library of functions into many separate ink stories.

**Comment by darbotron** [comment]
seconded! 

I'm seeing the same issue - ../Common/xxx works fine in inky, but not when compiling from the command line in Unity

INCLUDE as a feature is massively limited by this - relative file paths are one of the lynchpins of library code :)

Alex

**Comment by HashBuoy** [comment]
https://github.com/inkle/ink-unity-integration/issues/39

It's resolved now, tested successfully.
