### ISSUE TITLE
Not finding all the knot tags I expected

### ISSUE THREAD

**Issue by Paulloz** [inkle/ink#249]
Hello there!
It seems whether I misunderstood my reading on #122 or I'm experiencing some unwanted behavior with knot tags.

I'm using [0.6.4](https://github.com/inkle/ink/releases/tag/0.6.4) (outside of Unity).  
Here's my test `.ink` file:
```
Here we go
-> knot

== knot ==
# knot tag
Knot content
And some content with a line tag # line tag
-> DONE
```
Which compiles to:
```json
{"inkVersion":15,"root":["^Here we go","\n",{"->":"knot"},"done",{"knot":[{"#":"knot tag"},"^Knot content","\n","^And some content with a line tag ",{"#":"line tag"},"\n","done",{"#f":3}],"#f":3}]}
```

I'm logging on each line the text, how many tags there is in `.currentTags` and the tags themselves. Here's what I'm seeing in my logs:
```json
"Here we go", 0, []
"Knot content", 1, ["knot tag"]
"And some content with a line tag",  1, ["line tag"]
```

On the third line of text, am I not supposed to find both `"knot tag"` and `"line tag`" in `.currentTags`?

**Comment by joethephish** [comment]
Nope, this is working as expected. Even when the tag is on the line above, it is still attached to just one particular line.

The only other thing is that any tags at the top of a knot are *also* accessible through the `TagsForContentAtPath` method, e.g. `story.TagsForContentAtPath("knot")` ==> `knot tag`, which is useful for adding metadata to the knot itself.

**Comment by Paulloz** [comment]
Ok, I was asking because in [this comment](https://github.com/inkle/ink/issues/122#issuecomment-250187530) you were saying this which seems to state another behavior:
> then story.currentTags will give you a list that contains the initial "a knot tag" and "another knot tag" since it's associated with the line that was just generated.

Anyway, thanks for the answer!

**Comment by joethephish** [comment]
Right, so to give another example:

```
== knot ==
# one
# two
This line has tags one, two, three and four. # three # four
# five
This line has tags five and six. # six
This line has no tags at all.
# seven       // this tag isn't associated with any line
```

Meanwhile...

`story.TagsForContentAtPath("knot")` will yield `["one", "two"]`.

Clear? :)

**Comment by Paulloz** [comment]
Yep ^^
