### ISSUE TITLE
Save/Load Methods

### ISSUE THREAD

**Issue by Fahrengeit** [inkle/ink#25]
Hello,
Maybe I didn't find it in tutorials, but what is the best way to make saving/loading in game? 
Am I right, we can't do anything about internal variables, that count how many times player diverted to some knot, stitch, or chose option with label on it? It seems that we can't get any value from them in C# and we can't give these values to global variables. And it seems that there is no reset for them besides restarting the story too.
Am I missing something big here, something like states we can address to and get all variables on that moment correctly? Or should I create my own system with global variables that will duplicate the work of knots, stitches, labels for everything I want (it is still a good question how to work with conditions that depend on "entrance count", not on variables), and with every load I should restart the story? Or work only with variables if I want to successfully save and load it?
I don't believe that saving is a complicated thing, when everything in Ink is so convenient. I hope you can give a hint :)

**Comment by twheinen** [comment]
I would also like to hear from the developers about this. Saving and loading is the main roadblock keeping me from using ink in my current project. I can see in the roadmap you plan to implement "save state from runtime". I was curious how soon this feature might be implemented, or if there is a recommended way to save story progress. Thanks!

**Comment by joethephish** [comment]
Yeah, sorry, this is one of our biggest missing features right now (hey,
it's alpha), and one that we should probably prioritise. I'd be interested
if you guys have an opinion on what form you'd like the save state to take?
Previously we've always serialised to json, but let me know if you have a
strong opinion either way!

**Comment by twheinen** [comment]
I don't have any preference personally, but json serialization sounds fine to me. As long as there are simple methods for saving and loading story state, I'm happy. Also, it would be very useful to be able to retrieve knot and stitch values from the code if it's possible. Thank you for releasing such a great tool by the way!

**Comment by joethephish** [comment]
What do you mean by "knot and stitch values"? The read counts?

**Comment by twheinen** [comment]
Yes, the read count is what I meant. It would make it much easier to trigger in game events based on which choices the player has made.

**Comment by Fahrengeit** [comment]
Yeah, read counts. Because sometimes you need to "forget" that you've been somewhere - or this kind of thing should be done with variables instead? It would be convenient, if you'll have access to counts like to global variables, because even now you can throw away read counts from knots and labels, make story using them and even implement some sort of save feature, because we have access to everything from the Unity.
It's interesting, how ink.runtime knows where he is in story at the moment, in what form it keeps state right now? 
And am I right that nothing stops to try writing stories like it is now, just wait for Save state feature to apear in Ink Runtime and then quickly add it to project?

**Comment by joethephish** [comment]
Yeah, I'd definitely say it would be bad practice to "poke in" read counts to make the story "forget" certain things - definitely a good case to upgrade to variables.

During runtime, the story effectively stores a path to the current piece of content, a bit like a program counter in a CPU.

Yup, if you don't need save state *right now* you can certainly go ahead and develop your game, until we implement it, at which time you can add it - that's what we're going to do!

**Comment by twheinen** [comment]
I was assuming the read counts would be read only, and not editable from the code. I don't see any harm in giving users the option to view the read counts from the code if it makes the game logic simpler. I agree that editing read counts from code would probably be a bad idea.

**Comment by joethephish** [comment]
Yeah, agreed @twheinen!

**Comment by twheinen** [comment]
Also, is it true that the ChoosePathString method resets the read counts? I haven't tested it myself, but that's what @Fahrengeit said in the initial post. That would be a big problem in my game as it's not a linear narrative. I am planning on using ink for dialogue in an rpg game, but I would be making frequent use of the ChoosePathString method to jump around the story. If the read counts reset every time, it would be much harder to keep track of which knots and stitches the player has seen.

**Comment by joethephish** [comment]
@twheinen ah, I didn't read the initial post closely enough. No, it's not true: ChoosePathString definitely doesn't (or shouldn't!) reset read counts. Any proof of an example where read counts aren't being maintained correctly should be reported.

**Comment by Fahrengeit** [comment]
True enough about editing read counts, but agree with @twheinen, read them can be useful. 

Great. I hope implementing save feature wouldn't take too much time, though I would keep in mind other methods for saving story.

And I will try again now ChoosePathString, maybe I mislooked something and read counts reseted by my mistake.

**Comment by joethephish** [comment]
Hey guys, save state is now available, see the latest 0.2.0 release: https://github.com/inkle/ink/releases/tag/v0.2.0-alpha.

I've added a task to open a public API for read count to our internal bug tracker, so hopefully I'll get that done soon!

Closing this issue for now.

**Comment by Fahrengeit** [comment]
Wow, that was fast. 
Thanks a lot, definitely will try today.

**Comment by Fahrengeit** [comment]
Don't know if I'm missing something, but I can't access to Ink.Runtime.Story.state. First it gave me the error, that there is no definition of method for "state", but then I noticed more believable error - "state" is inaccessible due to its protection level. Is there a chance that it stayed private for default or some other reasons?

**Comment by joethephish** [comment]
Oops, sorry about that! I'll push out a new build soon...

**Comment by joethephish** [comment]
Okay, fixed in latest release (0.2.1)

**Comment by Fahrengeit** [comment]
Yeah, thanks! Everything works now.
