### ISSUE TITLE
[Question/Request] Return from a knot

### ISSUE THREAD

**Issue by rubereaglenest** [inkle/ink#264]
I know that we can't "return" from a knot or stitch as if it was a subroutine, as documentation says:

> Knots and diverts combine to create the basic story flow of the game. This flow is "flat" - there's no call-stack, and diverts aren't "returned" from.

But, I wish it could be that way. For example I have a room in a knot with several stitches showing the interaction with the furniture of the room. I would like to have a stitch that is the action "look around", that could be called from everywhere in the room, and then return to the proper knot.

And, Sorcery! does something like these, you Ink, have instances of events that could happen at any moment in the complex flow of time and space in that marvellous universe. So I imagine what you are doing is to call ink scripts from Unity, and then call back to the proper map node. But I wish this could be a feature of the scripting language.

Or maybe there's a way to simulate this within Ink?

Regards.

**Comment by ZephyrRaine** [comment]
I think you can use threads for this. You can actually pass diverts as functions parameters within Ink. Here's an example from the WritingWithInk documentation : 
```

=== outside_the_house
The front step. The house smells. Of murder. And lavender.
- (top)
    <- review_case_notes(-> top) 
    *   [Go through the front door] 
        I stepped inside the house.
        -> the_hallway
    *   [Sniff the air]
        I hate lavender. It makes me think of soap, and soap makes me think about my marriage. 
        -> top

=== the_hallway
The hallway. Front door open to the street. Little bureau.
- (top)
    <- review_case_notes(-> top) 
    *   [Go through the front door] 
        I stepped out into the cool sunshine. 
        -> outside_the_house
    *   [Open the bureau] 
        Keys. More keys. Even more keys. How many locks do these people need?
        -> top

=== review_case_notes(-> go_back_to) 
+   {not done || TURNS_SINCE(-> done) > 10} 
    [Review my case notes] 
    // the conditional ensures you don't get the option to check repeatedly
    {I|Once again, I} flicked through the notes I'd made so far. Still not obvious suspects.
-   (done) -> go_back_to


```
I'm not sure it's what you're looking for but seems relevant.

**Comment by joethephish** [comment]
What we meant by that in the documentation is that knots and stitches are flat *by default*. In fact, this is exactly what tunnels are for:

```
-> bedroom

== bedroom ==
- (top)
You're in the bedroom.
+ [Look around]
    -> look_around ->
    -> top
+ [Leave] You walk out -> END

= look_around 
There's a bed in the corner.
->->  // "tunnel return" - it's like a return statement
```

Or, as @ZephyrRaine says, you can use threads, useful if you want to pull in choices from another knot/stitch.

```
-> bedroom

== bedroom ==
- (top)
You're in the bedroom.
<- look_around
<- leave

= look_around 
+ [Look around] There's a bed in the corner. -> top


// A knot, so you could re-use it in other places than the bedroom.
== leave ==
+ [Leave] You walk out -> END
```

**Comment by rubereaglenest** [comment]
AWsome! Thanks guys, this is VERY useful. I'm reading step by step in the documentation, and trying to apply it to a game, and you know, sometimes need comes more quick than learning :)

**Comment by rubereaglenest** [comment]
Just a brief question. Should we close the discussion threads? I mean, for readability and discoverability.

**Comment by joethephish** [comment]
Good question! I'd say try to close, but I realise there's quite a lot of stuff here that's been left open because of open questions etc...!
