### ISSUE TITLE
Converting number to values doesn't appear to work

### ISSUE THREAD

**Issue by y-lohse** [inkle/ink#278]
[This example from the docs](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#converting-numbers-to-values) produces the following error:

```
`ERROR: 'list.ink' line 2: initial value for a variable must be a number, constant, list or divert target
```

**Comment by joethephish** [comment]
Ah, yeah, you can't create a list value from that style of "constructor" during declaration. I have amended the docs. Thanks!
