### ISSUE TITLE
(Unity) bool as a variable state

### ISSUE THREAD

**Issue by wearywitness** [inkle/ink#284]
Hi,

I'm still new to ink with its integration to unity. Trying to get ink variables to be read in unity. 
When I try it with an int, it works very well, for example in C# Unity:
int conversations = 0; 
conversations = (int)story.variablesState ["conversations"];
This one reads very well and I've declared it as VAR conversations = 0 in the ink file's global scope.

However, when I try the same with a boolean:
bool bigEvent = false;
bigEvent = (bool)story.variablesState ["bigEvent"];
It doesn't read at all even though I've declared it in the ink file's global scope as VAR bigEvent = false
Gives me an error: InvalidCastException: Cannot cast from source type to destination type.

Could someone please tell me why?

Thanks!

**Comment by joethephish** [comment]
Boolean variables in ink are actually stored internally as ints. If you're familiar with C, this might seem like an old school way of doing things, but actually it's for easy refactoring when you decide to turn a variable from a boolean into a counter, which is quite common in narrative logic. For example, when converting "did you pick up a daisy" to "how many daisies did you pick up".

So, on the game side you could either use `System.Convert.ToBoolean`, or simply check `bool isTrue = yourVariable != 0`.

**Comment by wearywitness** [comment]
Thank you, that was clear. It worked out very well :)
