### ISSUE TITLE
Shuffling order of choices

### ISSUE THREAD

**Issue by nicholasderk** [inkle/ink#295]
I'm working on a project with a similar raise and lower tension mechanic in 80 Days, and each of my choice sections has a minimum of 3 choices.

I'd like to randomize their position so, unlike Mass Effect where upper is paragon and lower is renegage, the player would have to deduce based on the language of the choice as to whether this will raise or lower the tension since the player can never rely on the ordering to game the variables.

I've tried {~ and { shuffle: but they both give me an end of line error.

**Comment by joningold** [comment]
You'll have to either write them in a random order each time (that's what
we do); or shuffle the choice list array on the game side before you put
them onscreen. (That's not hard; you just need to find the place in the
code where that happens in your unity project / in the js exported file.)

Jon
