### ISSUE TITLE
Bug: More fallback craziness

### ISSUE THREAD

**Issue by joningold** [inkle/ink#306]
```
*   {true} -> 
    limes
    -> done
    
*   -> 
    lemons
    
-   (done) Gathered!
    
    -> DONE
```

produces 

limes
Gathered!
Gathered!

Note it'd be cool if the first fallback was used, and it's existence meant the second wasn't, so you could have multiple fallbacks without needing a condition on the last one.

**Comment by joethephish** [comment]
Fixed in ebf4c4016302c456b1363c903db2795d961f240a.
