### ISSUE TITLE
Bug: can't || the results of intersections

### ISSUE THREAD

**Issue by joningold** [inkle/ink#308]
I'm not sure this is a bug rather than a casting issue, but I'm not sure how to work around it if so:

```
LIST a = ho, hum
LIST b = ho, hum
LIST c = ho, hum
LIST d = ho, hum

{(a ^ b):
    yup 
}
{(a ^ b) || (c ^ d):
    nope
}

```

The first conditional is fine (and false). The second fails, however, with the error

`Line 9: Cannot perform operation '||' on List`

It seems to think I'm trying to "or" two lists, as opposed to simply assuming I mean them to be bools.

**Comment by joethephish** [comment]
Okay, previously we had the `and` operator meaning "union" - i.e. `(A, B)` and `(B, C)` resulted in `(A, B, C)` - it was the same as the `+` operator. This was purely so you could write the nicely english-like `~ items = cloak and dagger`, but given that `+` is just as good, I've converted `&&` and `and` to being logical boolean operators, checking whether the lists have any items in them. And I've now supported `||` and `or` in the same way.

Done in a75479741430b95f7ab8f8be3806a8f26168f44f.
