### ISSUE TITLE
Improve defensiveness when loading saved state after story source changes

### ISSUE THREAD

**Issue by joethephish** [inkle/ink#310]
Currently the runtime story isn't very good at coping if you:

 * Play through the story, save the state 
 * Make edits to the ink, recompile the story
 * Reload the previously saved state in the new version of the story

There are a multitude of reasons for this. We should identify some of the biggest / most common, and try to recover from these situations where possible.

This is relevant especially during development where you need to iterate on a particular scene, but is also very important for making story fixes after release, or even writing new content updates after a game's release.

Identified issues:

 * Variables added / removed / renamed
 * Knot / stitches added / removed / renamed
 * ? (*TODO: Update this issue with a more exhaustive list*)

**Comment by Paulloz** [comment]
What I experienced about this (I could be wrong):
 * changing the number of options in a choice seem to be an issue
 * adding a new variable did not seem to be an issue as long as I inserted it in the json state before loading it

**Comment by joethephish** [comment]
Good catch, thanks! We're due a serious audit of this soon.

**Comment by ringlas** [comment]
Can't wait for future updates on this.

**Comment by DawncallerDE** [comment]
Looking forward to progress on this!
Also, is there a list or doc about what story changes will currently break the savestate?

**Comment by joethephish** [comment]
Sorry, I should've closed this issue back when we did a lot of work on this for the [release of version 0.8.1](https://github.com/inkle/ink/releases/tag/0.8.1).

There will always be the risk of things going wrong if you update the story content of a game in production, but there are various ways to mitigate it:

* Don't delete content, instead simply un-link it
* Try to save when the game state is at a "high level point" -- i.e. ideally not in a tunnel (in case the return point changes) and ideally not at a choice point if there's a likelihood that it may change.
* Try to keep your content named and fairly granular - i.e. don't save in the middle of big long weave without jumping between named knots/stitches, since as you add or remove content things can go out of sync.

We can't really ever guarantee perfect robustness, but for that past release we improved the situation dramatically. It was primarily designed for easy iteration while in development, but should also help if you need to change content for a game in product, subject to testing!
