### ISSUE TITLE
Creating a Loop / previous choices

### ISSUE THREAD

**Issue by Chroniric** [inkle/ink#311]
Hi all,
I'm trying to make a 'temporal loop' in my interactive fiction. The idea is ismple : the reader can re-read a paragraph he has already read and make another choice.
If the reader has previously read the paragraph, his previous choice doesn't appear. What can I do to fix this ?
Thanks - 

Here is an example of the loop :

```
//TEST TEMPORAL LOOP
->BEGIN
= BEGIN
* yes
->LOOP
* no
->LOOP

= LOOP
* REWIND ->BEGIN
->DONE
```

**Comment by joethephish** [comment]
Simply use sticky choices - use `+` instead of `*`:

```
//TEST TEMPORAL LOOP
->BEGIN
= BEGIN
+ yes
->LOOP

+ no
->LOOP

= LOOP
+ REWIND ->BEGIN
->DONE
```

**Comment by Chroniric** [comment]
Hi Joe,
Thank you for that.
(I have to re-re-read the documentation to really understand how the sticky choices works.
++
