### ISSUE TITLE
Bug: collision between list values and stitch names

### ISSUE THREAD

**Issue by joningold** [inkle/ink#314]
The following code compiles but hits a run-time error ("can't compare List and Int"). It should either fail to compile because the list name and the stitch name collide, or deduce the type correctly. (I suspect it should fail to compile.)

```
LIST colours = red, blue, green

- (red) 
    *   {red > 1} Red?
```

**Comment by facelesspanda** [comment]
I raise my hand in the compilation error side.
`LIST` declarations and labels are both full of names we (writers) want to use as variables. If they collide, it's no good at all, for our brains if not for the game.

**Comment by joethephish** [comment]
Much stronger name collision checks added in b419295ddbf6baa49a6523a3db098c145420c8ad.
