### ISSUE TITLE
Web export is changing numbers?

### ISSUE THREAD

**Issue by TLCMunchkin** [inkle/ink#319]
Hi,

I came across this weird little error and have no idea whether it's a bug, or if I'm doing anything wrong! It's actually pretty simple. 

I have a very simple percentage calculation set up. All the Variables as floats, because that's what I want my output to be.

```
VAR currentHealth = 0.0
VAR maxHealth = 200.0
VAR interfaceHealth = 0.0

=== function health (k) ===
~ currentHealth = currentHealth + k
~ interfaceHealth = (100/maxHealth)*currentHealth
```

My issue is that while this seems to work perfectly fine in the Inky editor, as soon as I export it for the web - without changing a SINGLE thing in the java code, it doesn't seem to work. If maxHealth is 100 and all the other numbers used are integers, it will work, but as soon the calculated interfaceHealth happens to be a float it will stop working. Trouble shooting this was making me nuts, so what I did at the end is just open a blank ink file, add that function and then really just do this: (this is the entire file)

```
VAR currentHealth = 0.0
VAR maxHealth = 200.0 
VAR pHealth = 0.0 
-> loop

=== loop ===

This is just a test.
Health: {interfaceHealth}

+   [Raise Health]
    ~ health(5)
+   [Lower Health] 
    ~ health(-5)

-   -> loop

=== function health (k) ===
~ currentHealth = currentHealth + k
~ interfaceHealth = (100/maxHealth)*currentHealth
```
 
And the same happens. In the ink editor:
<img width="308" alt="screen shot 2017-05-17 at 15 33 36" src="https://cloud.githubusercontent.com/assets/24683763/26156354/54488f08-3b16-11e7-83d7-4cfab7981c19.png">

Without changing a single file from the direct web export, when I open the index file with Chrome, this is what I get:
<img width="468" alt="screen shot 2017-05-17 at 15 34 04" src="https://cloud.githubusercontent.com/assets/24683763/26156396/7dcdf124-3b16-11e7-94ae-2e7a6a73ece9.png">

Am I doing something wrong? I've reduced this whole thing to such a basic process and everything looks good in inky, it seems like this might be a bug. But then again, it's such a basic thing, it baffles me a bit. Did I do something wrong and if so, what? Or if this is a known bug: is there an easy workaround I could use?

Thanks in advance for any help you can come up with.

EDIT: thought I might add this info if needed.
I use Version 0.7.1 for Mac OS X that I downloaded from: https://github.com/inkle/inky/releases/tag/0.7.1

**Comment by y-lohse** [comment]
Hi, this is indeed a sort-of bug with the web player. [here's](https://github.com/y-lohse/inkjs/issues/39) a previous bug report on that. From what's there and from what I recall, the ink engine for the web treats numbers like `100.0` as integers instead of floats, which is probably causing the problem here.

I'll try to look for a fix again at some point, but last time I came up empty. As a workaround, you can do the sensitive math in javascript instead of ink, or use "less" round numbers when possible (javascript is not great at this number thing).

**Comment by TLCMunchkin** [comment]
Oh, how unfortunate! I think I can work around this for now, but I was going to use this a lot, considering it's a very riddle/puzzle heavy game so this will complicate a lot of stuff.

At least I can blame javascript again instead of myself, haha.
Thanks a lot for your fast reply, I'll keep an eye out in case you find a fix one day.

**Comment by joningold** [comment]
You could try doing your multiplication before the division, which should
lessen the effect of the rounding error. So

(100 * currentHealth) / maxHealth

Jon
