### ISSUE TITLE
Issue with Newtonsoft.Json in Unity build (solved)

### ISSUE THREAD

**Issue by Fahrengeit** [inkle/ink#32]
I've met a problem after building the application in Unity, Log showed this type of error:

> TypeLoadException: Could not load type 'Newtonsoft.Json.Linq.JArray' from assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.

If it's not so obvious and I just didn't know anything about it, maybe it's worth to add a solution for such cases in RunningWithInk documentation: In "Edit -> Project settings -> Player -> Other settings"  you should set API compatibility level from .NET 2.0 subset (default one) to .NET 2.0.

**Comment by joethephish** [comment]
Ah, good point. You're not the first to notice this - I'll make a note in the docs as you say.
