### ISSUE TITLE
How do I share an ink story online?

### ISSUE THREAD

**Issue by ElanaE** [inkle/ink#320]
After finding out that inkle no longer has the bandwidth to host all those inklewriter stories, I'd like to switch to ink/y. What I'm trying to find out now is how to share a multiple-choice story as a link on my website, just like inkle did with this demo story "The Intercept": http://www.inklestudios.com/misc/The_Intercept_Inky/
What would I have to do with the html document and the accompanying file folder I get when exporting an inky story for web in order to be able to share this way? I am using wix and, just like other website builders, they don't accept html docs or anything related.

Thanks!

**Comment by lhughes41** [comment]
Look up Quill:
http://jeejah.xyz/quill/
Best of luck,
  Luke

**Comment by joethephish** [comment]
You just need to use any web host that supports HTML upload. A good one specifically used for indie games is https://itch.io Good luck!

**Comment by ElanaE** [comment]
@lhughes41 I'm not sure if that will solve my hosting problem. Quill seems to be an alternative to inky, but I might misunderstand its purpose.

@joethephish This page looks interesting! Just have to find out if I'd be able to upload purely text-based stories in the Choose Your Own Adventure style, like that The Intercept example I linked above, no graphics or anything like that.

Thanks for taking the time to anwer!

**Comment by ElanaE** [comment]
Itchio is indeed all I needed. Thanks!

**Comment by joethephish** [comment]
Awesome, glad it works for you!
