### ISSUE TITLE
ToC for documentation

### ISSUE THREAD

**Issue by davelowensohn** [inkle/ink#323]
I spend a lot of time searching through the online documentation, so I made a fork & added hotlinked tables of contents for everything in /Documentation with [markdown-toc](https://atom.io/packages/markdown-toc). Cleaned up some whitespace too. Feel free to merge into master if you think this is useful!

**Comment by manuq** [comment]
I think this PR should be closed, as per the discussion in https://github.com/inkle/ink/issues/498#issuecomment-443410150.
