### ISSUE TITLE
[Question] Native iOS ink runtime?

### ISSUE THREAD

**Issue by russellquinn** [inkle/ink#326]
Does anyone have any experience getting an ink runtime running natively for iOS? (without Unity)?

Thanks.

**Comment by facelesspanda** [comment]
I don't speak from experience because I never worked with apple products, but from what I understand, if you want to run Mono on iOS, you should look at the [Xamarin platform](https://www.xamarin.com/)

**Comment by joningold** [comment]
We've never done it, but you might be able to use the JS port,
https://github.com/y-lohse/inkjs - there's a way to run JS inside iOS code,
I believe?

cheers
jon

**Comment by joethephish** [comment]
Yeah either approach should be possible I think. Mono is probably harder to set up, and I'm not sure whether Apple still has issues with JIT (just in time compiled bytecode). You could compile it natively using AOT (ahead of time compile, it's what Unity can do), but I'm not sure how you'd like it to the native iOS code.

JS is much simpler - iOS has tech called JavaScriptCore so it should be straightforward to set up. JS is much slower to run though (after all it's running a scripting language within a scripting language! And ink's goal was never to be super speedy.)

**Comment by russellquinn** [comment]
Thanks for the thoughts! I'm going to try and get the JS approach working. Should be a simple enough wrapped from the looks of it. I'll open source it, if I get it working.

**Comment by russellquinn** [comment]
Hey! I got the JavaScript port working and built an Objective C wrapper. It's here: https://github.com/russellquinn/ink-iOS
