### ISSUE TITLE
[Question] Should tags work in choices?

### ISSUE THREAD

**Issue by russellquinn** [inkle/ink#331]
If I do:

`* [Yes] Yeah, it's me #player`

and the player picks this choice, then I call `continue`, I get:

`currentText = "Yeah, it's me"`
`currentTags = null`

(I'm using inkjs with my iOS wrapper, so there could be something happening there, but I just wanted to check on expected behavior.)

**Comment by joethephish** [comment]
Hmm, just reproduced this. It seems that a recent change I made to the way that choices are compiled meant that the tag only gets pushed out on the next line. I've made a fix in commit 1c3308a8e4e92d88bb7a14ae899884f5b2715dde so it'll be in future releases. This may be very annoying for your particular case, but I believe the tag should be there on the line afterwards?

**Comment by russellquinn** [comment]
@joethephish Ah, thanks. Yeah, the tag seems to be added to the line after the choice (which is actually a further problem for me, as that line has the incorrect tag.)

As I'm using inkjs, I guess it's a bug that needs to be fixed there too. I'll take a look. Thanks again.

**Comment by joethephish** [comment]
It's a bug in the ink compiler, so once I release a new build it'll automatically work in inkjs too :) (yay reaping benefits of an intermediate representation!)

**Comment by russellquinn** [comment]
Aha, got it. Great :)

**Comment by bladeSk** [comment]
This is still happening (or perhaps happening again) in the current [Ink Unity Integration](https://www.assetstore.unity3d.com/en/#!/content/60055) - v0.7.5 (Dec 07, 2017). A choice line with tags has no tags and they're moved one line below, which causes major issues in our story.
