### ISSUE TITLE
Show random list element each time?

### ISSUE THREAD

**Issue by JoshuaGrams** [inkle/ink#337]
So...shuffles loop, and shuffle each time you are at the beginning. So in `{~Mon|Tues|Wed|Thurs|Fri|Sat|Sun}` you will get all the days of the week in a random order, then all the days of the week in a different random order, and so on.  Which is fine, and often useful.  But I have a situation where I want each list item to have an equal chance to occur each time (i.e. you might get five Thursdays in a row, though it would be unlikely).  Is that possible?

**Comment by joningold** [comment]
Not so conveniently but the following isn't too bad:

{ RANDOM(1,7):
- 1: Monday
- 2: Tuesday
Etc
- 7: Sunday
}

Obviously it's annoying for more flexible examples having to count the
entries each time and keep that in sync. You could wrap this as a function,
do RANDOM(1,100) and have an else clause that calls the function again, so
it keeps going until it gets a result.

Jon

**Comment by JoshuaGrams** [comment]
Ah, that'll work.  I didn't know about the RANDOM function: is there a function list somewhere?

**Comment by wqa** [comment]
In some form, https://github.com/inkle/ink/blob/master/ink-engine-runtime/ControlCommand.cs

**Comment by joethephish** [comment]
Or perhaps slightly more accurately...? https://github.com/inkle/ink/blob/master/inklecate/ParsedHierarchy/FunctionCall.cs
