### ISSUE TITLE
Sticky choices not sticky

### ISSUE THREAD

**Issue by nullObjectPtr** [inkle/ink#34]
I'm seeing a behavior with InkEngine.dll where a sticky choice disappears from the choices list after a call to Story.Continue. Choice is properly sticky in play mode with inklecate. Curious as to why play-mode and engine dll differ. Will update this issue with minimal example soon. On version 0.2.0 alpha.

I will test with 0.2.1 alpha and will also provide minimal example soon.

**Comment by joethephish** [comment]
Hmm, it could potentially be a misunderstanding of how exactly it's meant to work. Can I just check that we're on the same page? Take this example:

    == test ==
    First line.
    Second line.
    + Choice 1
    + Choice 2
    - -> test

The first `Continue()` should produce "First line.". The second `Continue()` should produce "Second line." and the list of choices should then exist, with `canContinue` false. As soon as you choose a particular choice, then the next `Continue()` call should reset the choice list (perhaps this is surprising to you for some reason?), and the output text should be either `Choice 1` or `Choice 2`. Calling `Continue()` again will loop you back to the start.

On the second loop, after producing "Second line." again, the choices would come up again, whereas with normal choices, they wouldn't get generated again.

Does that make sense?

**Comment by nullObjectPtr** [comment]
Does make sense. Using exactly the example you've provided I've been stepping through. When I loop back around, after having selected Choice 1 or Choice 2, I am seeing that the currentChoices list now only has one member.

**Comment by joethephish** [comment]
Oh! Ok, thanks, I'll try to reproduce...

**Comment by nullObjectPtr** [comment]
Awesome :-) I'll clone from the repo and see if I can help track this down.

**Comment by joethephish** [comment]
I assume this is when you're testing in Unity?

**Comment by nullObjectPtr** [comment]
Yup.

**Comment by nullObjectPtr** [comment]
Okay, I've got the project up and running. I've been debugging my test case. I noticed that the value of onlyOnce for my Ink.Runtime.Choices instance is set to true. 

I only skimmed this code briefly, so apologies if i misunderstood something. 
Is the bug perhaps in Ink.Runtime.Choices when setting the flags.
`if ((value & 16) > 0) onceOnly = true;`
only sets the flag to true, never false. However the default constructor for Choices sets this to true by default.

**Comment by joethephish** [comment]
Yup, great catch! The bug was in the serialisation then. I'm going to revise the bit flag code to be:

    hasCondition = (value & 1) > 0;
    hasStartContent = (value & 2) > 0;
    hasChoiceOnlyContent = (value & 4) > 0;
    isInvisibleDefault = (value & 8) > 0;
    onceOnly = (value & 16) > 0;

I'll get a test written for that and push out a release soon.

**Comment by joethephish** [comment]
Okay, this fix is now in release 0.2.2 (https://github.com/inkle/ink/releases/tag/v0.2.2-alpha)

**Comment by nullObjectPtr** [comment]
Awesome! Thanks Joe.
