### ISSUE TITLE
not List ? element causes run-time error

### ISSUE THREAD

**Issue by joningold** [inkle/ink#353]
So, I get why this happens, but would it be possible to have a warning for it..?
```
LIST Sausages = Cumberland, Chipolatta

{not List ? Cumberland } 
```
fails because it tries to do `0 ? Cumberland`.  

Note that it's  good it doesn't treat "not List" as inverting or () !! As that would be even worse / harder to track down.

**Comment by joethephish** [comment]
Hmm, I wonder if it would be okay to just make `?` bind more tightly than `not`, or whether that would create another problem elsewhere...

**Comment by joningold** [comment]
I use "x + y ? z" though now I come to write that I wonder if it really
does what I think it does.

Jon

**Comment by joethephish** [comment]
Oh, looking at the compiler, I'm reminded that unary operators *always* bind more tightly than all binary operators. Which kinda makes sense given how they're normally used (only `!` and `-` for negation). Would require either a massive hack or quite a lot of work to engineer around it.

For reference anyway, here's the precedence list for binary operators as defined in the compiler code. See comment above `?` operator.

```
RegisterBinaryOperator ("&&", precedence:1);
RegisterBinaryOperator ("||", precedence:1);
RegisterBinaryOperator ("and", precedence:1, requireWhitespace: true);
RegisterBinaryOperator ("or", precedence:1, requireWhitespace: true);

RegisterBinaryOperator ("==", precedence:2);
RegisterBinaryOperator (">=", precedence:2);
RegisterBinaryOperator ("<=", precedence:2);
RegisterBinaryOperator ("<", precedence:2);
RegisterBinaryOperator (">", precedence:2);
RegisterBinaryOperator ("!=", precedence:2);

// (apples, oranges) + cabbages has (oranges, cabbages) == true
RegisterBinaryOperator ("?", precedence: 3);
RegisterBinaryOperator ("has", precedence: 3, requireWhitespace:true);
RegisterBinaryOperator ("!?", precedence: 3);
RegisterBinaryOperator ("hasnt", precedence: 3, requireWhitespace: true);
RegisterBinaryOperator ("^", precedence: 3);

RegisterBinaryOperator ("+", precedence:4);
RegisterBinaryOperator ("-", precedence:5);
RegisterBinaryOperator ("*", precedence:6);
RegisterBinaryOperator ("/", precedence:7);

RegisterBinaryOperator ("%", precedence:8);
RegisterBinaryOperator ("mod", precedence:8, requireWhitespace:true);
```

**Comment by joethephish** [comment]
I guess the best thing is simply to check for this general syntax tree pattern very specifically: `(not A) ? B` (where A and B are any simple/composite expression at all because what the hell) ... and warn, as you say.

**Comment by joethephish** [comment]
Done in b8d0e84c47b40f47489a93b198d454956c31cdec
