### ISSUE TITLE
empty choice text produces numerical output

### ISSUE THREAD

**Issue by joningold** [inkle/ink#356]
The following source-text

`*	[] some text`

produces quite an unexpected result!

Note this is actually a blank choice; so we should probably fire off the warning, telling the player to shove in a "->".

**Comment by joethephish** [comment]
This is actually more of a bug in inky - the `1:` is from the command-line choice selection from inklecate. Have added a warning though in 4718d074b39a52b4e6c2fab692b0774b04ff04f3, and created an issue in the inky repo.
