### ISSUE TITLE
cycling links and interchangeable paragraphs

### ISSUE THREAD

**Issue by rubereaglenest** [inkle/ink#36]
Hi guys:

I wonder if Ink is capable of doing cycling links like in twine without further work on the engine part. Or for example, has whole paragraphs disappearing and changing upon a click, like you, Inkle, did in First Draft of the Revolution.

If so, how?

Regards.

**Comment by joningold** [comment]
Do you mean, changing text that's already been produced?

The answer to that is no, or rather, kinda: ink produces a stream of
content - options - content; so to "edit an existing paragraph" you'd have
to regenerate the whole paragraph by building a loop. But then it'd be easy
to cycle your options; just use a cycle for the text, or a counter, or the
read count of the paragraph itself.

Of course the UI layer would have to correctly display what was happening
and not produce a long stream of text.

Jon
