### ISSUE TITLE
Feature request: ? as a substring operator

### ISSUE THREAD

**Issue by joningold** [inkle/ink#364]
I've been using an (externally defined) substring function a lot recently; it occurs to me ? might be a good syntax for it:

"Hello world" ? "lo w"  => true 
"Hello world" ? "World"  => false 

And so forth. 

This conceptually mirrors the use for lists: does big list contains little list.

**Comment by joethephish** [comment]
Done in c0abc3daa016a83ae0a8cbc112844e4993294ccb. It's actually a 1-line implementation, but propagation into an ink + inky + inkjs release will take a bit longer I guess!
