### ISSUE TITLE
Show optional line on tap

### ISSUE THREAD

**Issue by onewolfgames** [inkle/ink#365]
Hi!
I have searched the issues-section, as well as the documentation. Maybe, I don't know the right words to search for...

I'd like to add an optional text, which will only unfold on tap.

Somebody, who ...
wasn't too afraid of something, but
wasn't even there.

Which by default should result in

Somebody, who ...
wasn't even there. 

If you tap on the "who ...", the sentence should unfold to

Somebody, who wasn't afraid of something, but wasn't even there.

Thanks in advance :-)

**Comment by joningold** [comment]
So this kind of thing is done on the interface layer, not inside the ink.
Whatever you're writing your game in - say you're using hte export to web
option in inky - will have some gamecode for printing out text paragraphs
and choices. You'll need to make those paragraphs come out one by one after
taps ... but that's just changing out the text is printed on screen. The
ink can stay the same!

cheers
jon

**Comment by onewolfgames** [comment]
Ah, ok. Thanks for the info!
Cheers,
Jörg
