### ISSUE TITLE
Newbie asking help for Gamebook project!

### ISSUE THREAD

**Issue by MindbendeR76** [inkle/ink#366]
Hello, I am asking help!
I am writing a really simple gamebook, sorting it as Fighting Fantasy / Lone Wolf / Forbidden Gateway style. There is no a barebone structure somewhere?
Sorry my bad English and my bad programming skills!
I am learning Ink and it's really a cool Language!
So, I wrote a bit of coding, but it gives me error on line 86, 117, 118, 119:
"ran out of content. Do you need a '-> DONE' or '-> END'?"
But why? Where is my mistake?

```
Title

* [Warning] -> ADV
* [Intro] -> INTRO
* [Player Creation] -> Player_Creation
* [Rules] -> INDEX
* [I already know the rules] -> PAR_0

=== ADV ===
blah..blah..blah..

* [Intro] -> INTRO
* [I already know the rules] -> PAR_0

=== INTRO ===
blah..blah..blah..

* [Player Creation] -> Player_Creation
* [Start] -> PAR_1

=== Player_Creation ===
blah..blah..blah..

*	Strength.
blah..blah..blah..
**	[Roll the die!]
VAR Strength = 0
~ Strength = RANDOM(1,6) + 3

Yout Strength is {Strength}.

***	Stamina.
blah..blah..blah..
****	[Ok, I got it!]
VAR Stamina_MAX = 0
~ Stamina_MAX = Strength + Strength
VAR Stamina_NOW = 0
~ Stamina_NOW = Strength + Strength

Your Stamina is {Stamina_NOW}.

*****	Mentality.
blah..blah..blah..
******	[Roll the die.]
VAR Mentality = 0
~ Mentality = RANDOM(1,6) + 3

Your Mentality is {Mentality}.

*******	Endurance.
blah..blah..blah..
********	[Ok, I got it!]
VAR Endurance_MAX = 0
~ Endurance_MAX = Mentality + Mentality
VAR Endurance_NOW = 0
~ Endurance_NOW = Mentality + Mentality

Your Endurance is {Endurance_NOW}.

*********	Dexterity.
blah..blah..blah..
**********	[Roll the die!]
VAR Dexterity = 0
~ Dexterity = RANDOM(1,6) + 3

Your Dexterity is {Dexterity}.


*********** [Player Sheet] -> Player_Sheet

=== Player_Sheet ===
Character's Attributes are:

Strength: {Strength}
Stamina: {Stamina_NOW}
Mentality: {Mentality}
Endurance: {Endurance_NOW}
Dexterity: {Dexterity}


* [Attribute Check] -> Attribute_Check

=== Attribute_Check ===
blah..blah..blah..

* [Exemple] Exemple_Check

=== Exemple_Check ===
blah..blah..blah..blah..blah..blah..

* [COMBAT_RULES] COMBAT_RULES

=== COMBAT_RULES ===
blah..blah..blah..

* [Exemple] Exemple_Combat

=== Exemple_Combat ===
blah..blah..blah..

* [Weapons & equip] WEAPONS_EQUIP

=== WEAPONS_EQUIP ===
blah..blah..blah..

* [Death] Death

=== Death ===
blah..blah..blah..

* [Index] INDEX

=== INDEX ===


* [Attribute Check] -> Attribute_Check
* [Combat Rules] COMBAT_RULES
* [Weapons & equip] WEAPONS_EQUIP
* [Death] Death
* [Start the adventure!] -> PAR_0


=== PAR_0 ===
Character's Attributes are:

~ Strength = RANDOM(1,6) + 3
Strength: {Strength}

~ Stamina_MAX = Strength + Strength
~ Stamina_NOW = Strength + Strength
Stamina: {Stamina_NOW}

~ Mentality = RANDOM(1,6) + 3
Mentality: {Mentality}

~ Endurance_MAX = Mentality + Mentality
~ Endurance_NOW = Mentality + Mentality
Endurance: {Endurance_NOW}

~ Dexterity = RANDOM(1,6) + 3
Dexterity: {Dexterity}

* [GO!] -> PAR_1


=== PAR_1 ===
Start the adventure!

->END
```

**Comment by y-lohse** [comment]
You need to tell ink what to do at the end of a knot or a stitch, so as the error suggest, you need to add `-> DONE` at the end of your knots. You can read more about that [here](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#advanced-a-knottier-hello-world) :)

**Comment by MindbendeR76** [comment]
Hi, ty, but i still don't understand...

My knots start with:

=== My_knot
and it end with a choice/link to another knot
* [Link] Somewhere_knot

In my long script above, the story flow ends at this choice:
* [Exemple] Exemple_Combat

I still don't know where to put END or DONE...

**Comment by joningold** [comment]
To pick out an example (I just pasted your text into inky and it showed me
the errors):

=== Death ===
blah..blah..blah..

[Index] INDEX

is one of the knots that ends with a warning, and so it should: that last
line isn't diverting anywhere (it isn't a choice either.) I suppose you
meant

* [Index] -> INDEX

(The * tells ink it's a choice; the -> tells ink that what follows is a
knot-name, rather than text content. )

The same fix makes on the other warnings sorts it out!

cheers
jon

**Comment by MindbendeR76** [comment]
Thank you!!
I was hitting my head against a brick wall, instead the solution was  so simple :D
