### ISSUE TITLE
Conditional blocks (if/else)

### ISSUE THREAD

**Issue by MindbendeR76** [inkle/ink#369]
Can you help?
How can I write a conditional function like this:

If (ATTACK_VALUE = 2) & (DEFEND_VALUE = 2): ~ TO_HIT_NUMBER = +7

**Comment by joningold** [comment]
{ attack_value ==2 && defend_value == 2:
~ to_hit_number += 7
}

But seriously, read Writing With Ink; it's got loads of examples and will
save you trying to guess this stuff!!

(Ink isn't like basic - you don't write conditional instructions as such;
you write blocks of content which can be run or not run (although those can
contain instructions, natch.))

Cheers!
Jon
