### ISSUE TITLE
More qsts about conditional syntax

### ISSUE THREAD

**Issue by micabytes** [inkle/ink#38]
This example :
```
{ 
    - x == 0:
        ~ y = 0
    - x > 0:
        ~ y = x - 1:
    - else:
        ~ y = x + 1;
}
```
Seems to have a superfluous ':' in the second switch (it outputs that character in inklecate). This is also the case with the if-then example above it. However, the ';' is not outputted.

Some older Ink version syntax left-overs? You have other examples that include neither the end-of-line colon nor the semi-colon, and the parser handles those fine, so it doesn't seem as if either character serves any purpose any longer.

**Comment by joethephish** [comment]
Neither colon nor semi-colon should be there. The fact that it compiles at all is a mistake too.

**Comment by joethephish** [comment]
(It's never been in ink syntax, so must be a mixture of C-style language typo + being due to having colons on the other lines or something!)

**Comment by joethephish** [comment]
Opened a "proper" bug issue, closing this one.
