### ISSUE TITLE
External function is called twice between paragraphs

### ISSUE THREAD

**Issue by KoltesDigital** [inkle/ink#381]
Hi,

When there's a function call (`~ functionName()`) between two paragraphs, the function is called twice: when showing the previous paragraph, and when showing the following paragraph.

I've set up <https://github.com/KoltesDigital/Ink-Bug-Function-Calls> to show this behavior.

I see this behavior as a bug. But maybe it is intended?

Cheers

**Comment by joethephish** [comment]
This has been answered before - here: https://github.com/inkle/ink/issues/253

It's a common question though, and we're looking to find a way to resolve it in future. But it won't be before we've shipped [Heaven's Vault](https://www.inklestudios.com/heavensvault) I'm afraid!

**Comment by KoltesDigital** [comment]
Thanks, I hadn't seen the question. And your explanations make sense. So it may pertain to my usage. On my project I show the sentences paragraph by paragraph, whereas in your bundled example, you concatenate all the paragraphs. What do you recommend to be able to break between each paragraph?

Good luck for the game!

**Comment by joethephish** [comment]
Ah, this is exactly why we have both `story.Continue()`, which goes forward paragraph by paragraph and `story.ContinueMaximally()` which produces all the content up to the next choice (or end of the story) in one go. Hope that helps!

(Note I've just updated the official documentation to mention the [external functions issue](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#important-notes-on-the-usage-of-external-functions).)

**Comment by KoltesDigital** [comment]
OK thanks!

Just my two cents. Actually the feature of post-glues would have an impact on the software architecture of any game that uses ink. Looking ahead for glues means that you can change a copy of the current state and see how it evolves. You seem to say that you used to have that before 0.6.4. Just in case it isn't the case, here is an exemple:

    hello
    ~ set("foobar")
    { is_set("foobar"):
        <> world
    }

If you really want the feature to be reliable, ink should render "hello world" without the actual game's foobar being set. This would implies that ink is somehow able to copy the game state, at least the subset that can change through ink. That puts a lot of constraints.

So I doubt about the relevance of post-gluing texts. On the other hand, I neither know nor use ink like you do, so I'm eager to know relevant use cases. Have you stumbled across situations that post-glues can only solve, or at least where other solutions are much more complex?

Of course this is just a design discussion, finishing HV comes first :)

**Comment by joningold** [comment]
I suppose the point is not that post glues are necessary - you could work
around not having them - but they are convenient for a writer; not having
to think about how they’re using glue lifts an overhead off the writer.

For the code side of things, external functions should never alter state.
If you want to alter state it’s better to use a variable observer, or write
a markup into the text and have the game pick it up and handle it. We quite
like that approach as the games log then shows what’s happened.

We’ve considered making a type of external function (and action) which
“stops” glue and is guaranteed to only fire once - we may do that, we may
not!!

Jon
