### ISSUE TITLE
How do you download ink and inky

### ISSUE THREAD

**Issue by Skyclaw27** [inkle/ink#386]
This probably sounds like a really silly question, but I honestly can't work out how to properly download ink and inky? I can't find instructions and I'm really lost. I'm on a MacBook if that's any help, I have unity and plan to use it with ink. I'm really grateful if anyone could possibly guide me on how to properly download and install the files? Thank you :)

**Comment by joethephish** [comment]
https://github.com/inkle/inky/releases

**Comment by Skyclaw27** [comment]
@joethephish Thank you for your reply but I don't know if I'm missing something? I still don't understand how to install it so that I may actually use it? I have downloaded the file into my downloads folder, but it isn't installed to use, am I meant to drag files from the folder or even the whole folder itself into a section of my Mac to install it properly? I'm sorry if you have written instructions on how to do this on the link you've given me, but I can't find find them, so if there are, could you possibly point me as to where they are? Sorry for the trouble and thank you for your time

**Comment by Skyclaw27** [comment]
@joethephish Never mind, after some thorough searching, I think I've found it, thank you for helping me :)

**Comment by joethephish** [comment]
In case you're still not sure:

1. Download the Inky_mac.dmg
2. Open it, it'll put an Inky "virtual disk" in the left sidebar of the Finder window like the good old days when you inserted CDs.
3. Open the disk, you'll see the Inky icon.
4. Drag the Inky icon into your Applications folder.
5. Open Inky from there.
