### ISSUE TITLE
Finding Dead Ends

### ISSUE THREAD

**Issue by justfinethanks** [inkle/ink#395]
hello! thanks for all the wonderful code. 

Is there a way to automatically highlight or show that the following condition has no outcome?  I have a large .ink and in quite a few places I have forgotten to place gathers leaving empty choices. I would think that they would be highlighted in inky, but aren't... Is there some test I can run on the .ink or .json?

problem scenario:
	*[Hi.]
	Hello.
	    **[How are you?]
	    **[How's things?]
            ->just_fine_thanks

i'm dumb and should have written:
	*[Hi.]
	Hello.
	    **[How are you?]
	    **[How's things?]
            --
            ->just_fine_thanks

**Comment by justfinethanks** [comment]
I've got a "fix" in place for this at the moment in my chooseChoiceIndex method where if Choice1 is selected and can't continue and isn't the last in the index, then index+1 is the backupChoice. 

I realize this is a terrible method of maintaining my narrative - and will probably lead to some amount of confusion to the reader in parts - but it's much better than the story coming to an abrupt end. 

Happy to hear any thoughts or fixes. I'm thinking that I'm overlooking something simple here.  Or perhaps I should've just been more careful writing the .ink!

**Comment by justfinethanks** [comment]
Any additional thoughts on this?

**Comment by joningold** [comment]
I feel like this is a bug / missing feature; we should warn in this case.

Jon

**Comment by joningold** [comment]
We've improved dead-end checking in the latest release!
