### ISSUE TITLE
Choices in condition get combined

### ISSUE THREAD

**Issue by bigwillch** [inkle/ink#398]
Hi. Thanks for this great tool, I'm really enjoying using it

I've run into an issue which I'm not sure if is a bug or is intended behaviour. I've made some simple example code to replicate the issue I'm having in my project

```
-> knot

===knot

    =start
        + Example 1 -> example1
        + Example 2 -> example2

    -> DONE
    
    =example1
    // example 1 shows just its own choices
        + Choice
        + Choice
        -
    -> knot
    
    =example2
    // example 2 seems to combine its choices with the ones in start
        {knot > 0:
        + Choice
        + Choice
        }
    -> knot
    
-> DONE
```

The issue I'm having is that the choices in example1 show on their own as I'd expect, but when wrapped in a condition as per example2 the choices seem to get merged with the ones in knot.start

I've found using the `-` at the end of the choices as this seems to be needed in example1, however that results in an error in example2

I'm sure I'm probably just misunderstanding how this should be working. Any advice would be much appreciated. 

Thanks again!

**Comment by joningold** [comment]
Hey!

So this is intended: choices are “collected up” until the flow stops or you
hit a gather point.

In particular, bracing choices as you do in example 2 is a way of including
some choices from one knot before getting more from another. (Threads are a
better way to do this but not always convenient)

So to make your example work you should probably just add a dash before the
-> knot.

Jon

**Comment by bigwillch** [comment]
Ah ok, thanks for the reply! That certainly fixes it in my example. I've not managed to get the same method to fix the issue in my project so there must be something else I'm missing, but I'll keep plugging away. 

Thanks again

**Comment by bigwillch** [comment]
Got it working! :)
