### ISSUE TITLE
Javascript port

### ISSUE THREAD

**Issue by amatiasq** [inkle/ink#399]
Hey there, I'm a Javascript-focused developer. I'm building a web game and would love to use Ink on it so I'll be more than happy of providing a Javascript runtime library.

Looking at the README I saw the warning about runtime not being stable yet, I'm quite short on time so I won't be able to do huge refactors on it. Do we have any schedule about when the runtime will be stable?

Can we use this issue to track and get notification on it?

**Comment by joethephish** [comment]
Actually there’s already a strong JS port: https://github.com/y-lohse/inkjs

We use it internally for prototyping so it’s pretty robust - about as robust as ink itself at this point.

The runtime is unlikely to change significantly for a while now, while we finish our own internal project (Heaven’s Vault). (I should probably update the readme!)

**Comment by amatiasq** [comment]
Awesome! huge step into adapting Ink in my project, thanks 👍
