### ISSUE TITLE
Getting an external boolean varible that crashes the file

### ISSUE THREAD

**Issue by Jetyl** [inkle/ink#400]
Hello!
I'm working on a team visual novel/time & stat management style game, and we're using Ink as the text engine for out game. however, we've been hit with an issue where an external function does not work as indented.

the function is like this:

`public bool GetValue(string ValueName)
    {
      return Game.current.Progress.GetBoolValue(ValueName);
    }
`

it is the only getter that has these issues, as our similar getters for external ints and strings work fine:

`
public int GetIntValue(string ValueName)
    {
      return Game.current.Progress.GetIntValue(ValueName);
    }
`
`
    public string GetStringValue(string ValueName)
    {
      return Game.current.Progress.GetStringValue(ValueName);
    }
`

and I've done all the checks on my end that the system returning the booleans is working. it is getting the various tagged booleans correctly, and in the correct state, but when it returns it to the ink file, that's where the errors come in.

VAR Test = true

EXTERNAL GetValue(value)
EXTERNAL SetValue(name, values)

-> Start

=== Start ===
testing my getters and setters for booleans
~SetValue("testvalue", true)
I have just set the test value in the progress book to true. this can be confirmed code side
~Test = GetValue("testvalue")
I have just gotten the test value from my progress book. it is of value  {Test:true|false}.
please let this work...
->END

no matter what, the last line says the value is false.

even more concerning, when I write the if statement like this

{Test == true :true|false}.

the file stops getting read at that point, and the game moves onto whatever is after that file.

I have rattled my brains on this, and why google-fu has completely failed me. any idea why this isn't working?

**Comment by facelesspanda** [comment]
Hi,

could you show us how you do your bindings?

**Comment by y-lohse** [comment]
Hi, 
This is "normal", because of [how external functions work](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#important-notes-on-the-usage-of-external-functions).
Have you tried using [variable observers](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#variable-observers) instead, and only setting the values ink-side?

**Comment by facelesspanda** [comment]
oh right I haven't seen the `SetValue` bit from the code sample.

**Comment by Jetyl** [comment]
hello

so, we can't have the variables just in the ink files, because of how we have our scenes setup, we have multiple ink files, one for every major scene. we need to be able to get info from our global "progress book" that we have setup, that way we can know what to do, if a thing in scene A needs to know what if bool thing B happened in scene C. variable observation wouldn't work for that.

as for how they are bound, I did not handle that, so I do not 100% know what they did, but this is the code they had 

`protected override void OnBindExternalFunctions(Story story)
    {
      story.runtime.BindExternalFunction(nameof(GetValue), (string valueName) => { GetValue(valueName); });
      story.runtime.BindExternalFunction(nameof(GetIntValue), (string valueName) => { GetIntValue(valueName); });
      story.runtime.BindExternalFunction(nameof(GetStringValue), (string valueName) => { GetStringValue(valueName); });
    }`

again, the int and string ones work fine

**Comment by joethephish** [comment]
So, the only thing that's special about bools is that within ink they get converted to ints, so that there's always an easy upgrade path from "did you do this?" to "how many times did you do this?".

Although the external function binding functionality should be able to deal with this, you might want to try assuming they're 100% always ints in ink and do casting on the C# side as they go in and out of your functions?

**Comment by Jetyl** [comment]
okay, I was wondering if you were doing something like that under the hood.

I changed getvalue to return either 1 or 0, and I am unfortunately still getting the same errors.

test variable, as an int, still gets false in that if statement, and when I want to declare it specifically, as in:

{Test==1:true|false}

it prints nothing, and automatically ends the entire ink file.

I'm wondering if its just not properly assigning the returned values from bound functions? like, after saying ~Test = GetValue("testvalue"), Test becomes null, or something?

**Comment by joethephish** [comment]
That's odd, because otherwise aren't the functions identical to your int versions, which do work...?

**Comment by Jetyl** [comment]
they are near identical.
 I just tried the int getter instead, and the same result of always false, or auto-ending the file...
:/

**Comment by joethephish** [comment]
Oh the ending might be because there's an error that you're not seeing - might want to check the contents of `yourStory.currentErrors` in C#...?

**Comment by Jetyl** [comment]
yep, there is an error there:

> RUNTIME ERROR: Attempting to perform operation on a void value. Did you forget to 'return' a value from a function you called here?

so yeah, trying to assign a value in ink with the getters is returning null, despite being not null on the C# side.

(also, strange the error only appears if I specifically make it ==)

**Comment by joethephish** [comment]
Oh, I think you need `return` keyword in there!

`(string valueName) => { GetIntValue(valueName); }` isn't equivalent to `(string valueName) => GetIntValue(valueName)` - you're not returning anything!

**Comment by Jetyl** [comment]
Yep! that was the issue! now all the getters work as intended
Thank you so much!

**Comment by facelesspanda** [comment]
you can close this now Jetyl 👍
