### ISSUE TITLE
Inequality test on a divert variable crashes runtime

### ISSUE THREAD

**Issue by joningold** [inkle/ink#402]
```
- (top)
    ~ func(-> top) 
    
=== function func(-> a) 
    { a < 0: 
        Oops. 
    }
    
```

**Comment by joethephish** [comment]
Hmmm. This should probably throw a `StoryException` rather than a `System.Exception` (so it gets caught internally and turned into an error rather than a crash) but I'd suggest what you really want here is:

```
- (top)
    ~ func(-> top) 
    
=== function func(-> a) 
    { READ_COUNT(a) > 0: 
        Not oops - read count is {READ_COUNT(a)}.
    }
```

**Comment by joethephish** [comment]
Converted to a clearer `StoryException` in 43d2d7224ada2ee8746ef785fbe906b572106a3c.
