### ISSUE TITLE
Getting a list of all Knots in a story.

### ISSUE THREAD

**Issue by Dougomite** [inkle/ink#406]
I'm doing a Unity game and want to use Ink for random encounters that the player can come across. I've created a story of Random_Encounters and have included all the random encounters 'ink' files into that story file.

I'd like to be able to grab a list of all the Knots in that story so that I can randomly choose one and/or manually track which stories have been seen. This means that all my Knots will have to be beginnings to an encounter but I can live with that since we still have stitches in case I need another level of structure. 

My current plan is to just have a bunch of tags at the top of the Random_Encounters story with all the Knots names, so I can grab that with the globalTags variable. I was hoping there would some other way that wouldn't rely on me keeping that tag list up to date and correctly spelled.

Is there any other way to get all the knots in a story?

**Comment by joningold** [comment]
Not easily; but I would move the logic into ink - so have a top level knot
called “choose_encounter” which acts as an index and diverts to a story
knot, using shuffles or logical tests or whatever you like to decide where
to go. Then when you write a new story knot you just add it into this index
and inkys autocorrect will check you’ve typed it right. (Also, you can test
the logic and content in inky)

Jon

**Comment by klootas** [comment]
Sorry to revive an old issue but I was just wondering if this is still the case.

I need to do the same thing - get all knots/stitches in a story, get all tags in a knot/stitch etc. I had a look at the compiled json and it looks like I could parse the info I need from there, but perhaps there is a cleaner solution?

And hey - thanks a bunch for this library!

**Comment by laura3119** [comment]
I found a solution to it that I wanted to share:
```
private static void GetAllKnotNames(string json)
    {
        JObject storyText = JObject.Parse(json);
        IList<JToken> results = storyText["root"]?.Children().ToList();
        if (results != null && results.Count >= 3)
        {
            Dictionary<string, object> knotDictionary = JsonConvert.DeserializeObject<Dictionary<string, object>>(results[2].ToString());
            List<string> keyList = new List<string>(knotDictionary.Keys);
            foreach (var key in keyList)
            {
                Debug.Log(key);
            }
        }
    }
```
Here are the usages I needed for this code to work:
```
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;
```

**Comment by HashBuoy** [comment]
I got the knots with the code pasted below. Still searching for the stitches.

```
Story _inkStory = new Story(enInkJsonFile.text);

Dictionary<string,Ink.Runtime.Object> namedContect = _inkStory.mainContentContainer.namedOnlyContent;

foreach (KeyValuePair<string, Ink.Runtime.Object> kv in namedContect)
{
    Debug.Log($"key:{kv.Key} Value:{kv.Value}");
}
```

**Comment by AdrienLemaire** [comment]
In javascript:
```js
const story = new Story(responseText)
console.log([... story.mainContentContainer.namedContent.keys()])
```

**Comment by Antony-de-Fault** [comment]
> I got the knots with the code pasted below. Still searching for the stitches.

@HashBuoy Did you ever figure it out for the stitches? Butting my head against this now.

**Comment by HashBuoy** [comment]
@Antony-de-Fault Nothing yet :(

**Comment by demicercle** [comment]
Hi there
I think I found how to get stitch of your ink story :
`private static List<string> GetKnotAndStitches(Story story)
    {
        var output = new List<string>();
        var knots = story.mainContentContainer.namedContent.Keys;
        knots.ToList().ForEach((knot) =>
        {
            output.Add(knot);

            var container = story.KnotContainerWithName(knot);
            var stitchKeys = container.namedContent.Keys;
            stitchKeys.ToList().ForEach((stitch) =>
            {
                output.Add(knot + "." + stitch);
            });
        });
        return output;
    }`

tell me what you think and hope that helps!
cheers

**Comment by Antony-de-Fault** [comment]
> tell me what you think and hope that helps! cheers

@demicercle This is the solution! Can't believe I didn't find this myself, I was very close. Many thanks! Tested it just now and it works fine.
