### ISSUE TITLE
autocomplete disabled in newest update?

### ISSUE THREAD

**Issue by jamiesirvo** [inkle/ink#41]
Sublime's autocomplete seems to be disabled in .ink files as of the latest build.  Manually setting autocomplete to true does not restore the functionality.  

If it helps, before build 7222bb2 I was using autocomplete regularly.

Thanks for your help!

**Comment by joethephish** [comment]
This is very odd. I just reversed the commit (which is intended to fix on-word wrapping rather than on-character) in order to fix autocomplete. And word wrapping is still working for me. Not sure how that's happened! Anyway the commit has been reversed - thanks! (in development branch for now)
