### ISSUE TITLE
VAR in a #Tag?

### ISSUE THREAD

**Issue by CarterG81** [inkle/ink#410]
How can we use variables in Tags?

`VAR name = "Bob"`
`#CreateSprite:{name}`
`//Parses as "CreateSprite:{name}" when it should parse as "CreateSprite:Bob"`

Do I have to just avoid using #Tags?

**Comment by joningold** [comment]
For this kind of stuff you should use text and parse it in code and remove
it before it outputs to screen.

Game text...
>>> CreateSprite:{name}
More game text...

For our games we use a mixture of this approach and tags; depending on the
circumstance.

Jon
