### ISSUE TITLE
Extending Shuffle - Random Name Generator

### ISSUE THREAD

**Issue by CarterG81** [inkle/ink#412]
If my understand is correct, when you use Shuffle {~Random1|Random2|Random3} Ink keeps track of which are used. So if I called Shuffle 3 times, it would call each result in the example a single time.

//Resulting in...
Random2
Random1
Random3
[Loop] //Random 1 2 or 3 again.

**Is there already a way to use the Shuffle feature, but with allowing duplicate results?**

This way, writing "Shuffle {~Random1|Random2|Random3}" can result in "Random1" being called multiple times in a row.

Normally I just use a random number, and then a switch.

```
~ temp ranNum = RANDOM(1,2)
{
-ranNum == 1:
    ~return "RandomName1"
-ranNum == 2:
    ~return "RandomName2"
}
```

However with hundreds of results, a Switch gets pretty ugly.

I see that in other methods, there are multiple options: Sequences, Cycles, Once-Only's. There is however only one randomized method: Shuffle.

-------------------------------------------------------
An example of why this is helpful
-------------------------------------------------------
I am creating a Random Name Generator, which includes hundreds of names.

```
=== function GetRandomNameFromDictionary_Medieval_Surname() ===
~return "{~Aarland|Aartse|Abalardi|Abaroa|Abbado|Abduvaliyev|Abeille|Aberasturi|Abineri|About|Abrahamse|Abrao|Abrassart|Abruzzi|Abse|Abt|Aburto|Accardo|Accola|Accornero|Achard|Acker|Ackermann|Acklin|Acquaviva|Acuna|Adam|Addinell|Adelung|Adenauer|Adeney|Adler|Adriaens|Adriaenssens|Adrianszen|Advocat|Aehrenthal|Aertsen|Afiata|Agafitei|Agani|Agarand|Agare|Agassiz|Ageet|Ager|Agina|Aginaga|Agirre|Aglietti|Agnelli|Agnolutto|Agosti|Aguerre|Aguilar|Aguilon|Aguzzi|Ahlmann|Ahmetaj|Ahmeti|Aiello|Aigner|Aixpuru|Aiza|Aizkibel|Ajello|Ajeti|Ajkler|Akaregi|Akordagoitia|Akutain|Alacoque|Aladár|Alagna|Alard|Alasia|Albani|Albarello|Albelin|Albergati|Alberigo|Alberro|Albers|Albert|Albertazzi|Alberti|Albertini|Albertoni|Albertrani|Albertse|Albertszen|Albertz|Alboreto|Albouraie|Albrup|Albusel|Aldair|Aldape|Aldobrandini|Alembert|Alessi|Alevi|Alexandre|Alexopolous|Alexopoulos|Alfieri|Alger|Alhmann|Alia|Alibali|Alicata|Aliee|Alighero|Alighieri|Alii|Alikaj|Alis|Aliti|Aliu|Aljie|Allard|Allaro|Allbach|Alloncle|Allori|Allucingoli|Allut|Alphand|Altabani|Altaner|Altard|Althape|Althusser|Alti|Altichiero|Altichioro|Altieri|Altmann|Aluztiza|Alvares|Alves|Alvintzi|Alyea|Alzate|Alzen|Amable|Amanar|Amann|Amati|Amato|Amberezzio|Ambre|Ambrogi|Ambrogiani|Ameche|...
//Names A-Z.
```

With the First Names, this is exactly what I need. I don't want there to be duplicate first names.

However with Last names, I do want there to be duplicates. Perhaps to see if users are cousins or blood related & give them a boost to loyalty to one another.

Am I approaching this all wrong? I'm trying to make my game highly moddable - so mostly written in INK, but if this is a barbaric way to handle a name generator I could always write it in JSON & C# (outside of INK) but that is not preferred.

**Comment by CarterG81** [comment]
As a nifty little hack, I did think that I could simply roll a random number to grab a duplicate Surname INSTEAD of getting a random one.

~ temp ranNum = RANDOM(1,10) //100% chance in 10% increments
{
-ranNum == 1: //10% chance for the new character to be a Cousin of Someone
    ~return {GetSurNameOfCurrentPartyMember}
-else: //Unrelated. New Unique Surname entirely.
    ~return {GetRandomSurName()}
}

This way it is actually significantly more probable to get a new recruit who is related to a current partymember. It's a hack, but it's not the worst idea.

**Comment by joningold** [comment]
That's a great solution; since it'll let you balance the duplication!

When I need "more random than a shuffle" what I usually do - which is
ridiculous, but works fine - is a random-length loop:

~ temp rollTimes = RANDOM(1, 20)
~ temp name = ""
- (top)
 ~ rollTimes--
~ name = {~Name1|name2|name3|name4|...|name50}
{ rollTimes > 0: -> top }

Meanwhile, note that we have a long-term plan to include some kind of
{#var: if 0 | if 1 | if 2 .. | else } syntax at some point, which would
allow for roll a random number / pick  up that index; for now though you
can achieve the same thing not too messily with block logic:
{RANDOM(1, 100):
- 0:
- 1:
- 2:
...
- 100:
}
