### ISSUE TITLE
How to observe LIST from ink engine?

### ISSUE THREAD

**Issue by kudo1017** [inkle/ink#414]
I searched all open issues here, and I know that there is a equivalent class named InkList in ink engine, but I still don't understand how could I monitor/get the items of any LIST defined in my *.ink script. I know that there is an API ObserveVariable() and it works just fine to me, and I wonder is there any similar API for LIST?

Please forgive me if this sound stupid, cause I couldn't find a better solution other than LIST to implement an inventory.

**Comment by joethephish** [comment]
You can use `ObserveVariable` to observe a list. Something like:

```
LIST myList = A, B, C
VAR mySubList = (B, C)
```

and in C#:

```
story.ObserveVariable("myList" /* or "mySubList" */, (InkList list) => {
    // do something with the list
});
```

I'm afraid the `InkList` API is undocumented, though there are a fair number of code docs if you look in `InkList.cs`. They aren't quite as straightforward to use as simple primitive values I'm afraid, but definitely doable!

**Comment by kudo1017** [comment]
Thanks, I get it!
