### ISSUE TITLE
How to validate Ink tags against associated data

### ISSUE THREAD

**Issue by MrMengis** [inkle/ink#415]
We're using the Ink Unity Integration and tags to drive our dialogue audio and lipsync. While we're auto generating the tags from our script, we still need to check that the compiled tags are:

1/ well formed
2/ an audio event with the same name exists
3/ a lipsync event with the same name exists

What's the best way to get the tags from the data? Do I just parse each line of the Ink myself or use the jsonAssets out of the InkLibrary? I'm thinking something along the lines of the following but it all gets a bit murky once we're talking about StoryState._outputStream

```
List<InkFile> masterInkFiles = InkLibrary.GetMasterInkFiles();
foreach ( var inkFile in masterInkFiles )
{
     // for each line in inkFile.jsonAsset

     // parse tags

     // validate tags
}
```

**Comment by joningold** [comment]
I would suggest parsing the ink files yourself, since tags are quite easy
to spot and the ink is plain text.They are in the main json file but the
structure there is definitely harder to iterate through.

Jon

**Comment by MrMengis** [comment]
Thanks Jon,

Dang! I was afraid you were going to say that. I guess we can validate that the Inks are compiled at least. It would be really nice to parse the json in advance for character lists and the such like but for pure validation then the text assets will be fine.

**Comment by joningold** [comment]
Note that parsing the json to get list key values isn't actually that bad;
they're stored somewhere near the top level (we do this in our HV
pipeline). So you might be able to get list values out if you load in the
story variable and look through the structure.
