### ISSUE TITLE
Warning for loose ends inside weaves

### ISSUE THREAD

**Issue by joningold** [inkle/ink#416]
The following source 

```
=== knot 
    *   Option 
```

doesn't produce a loose end warning; meaning it's pretty easy to accidentally create a flow that dies at runtime. If the compiler could detect this, and warn, that would be epic.

**Comment by joethephish** [comment]
Ah yeah, I noticed that before but forgot to log it, that's definitely a biggie.

**Comment by Tom-Julux** [comment]
Only partially related to this issue, but I think someone should create a test suite for ink. This is a pretty simple file and it should not be possible to mess flow up that easily....

I could do this in spring break (in may). Maybe I will also implement this enhancement then.

**Comment by joethephish** [comment]
There’s already a test suite in the C# ink codebase. Just need to add this obvious case!

**Comment by Loverclocker** [comment]
@ZephyrRaine 
I'm very interested by your auto-tester.
It'll be very useful for the project I'm actually working on.
Any chance to see it somewhere on the web or ...?

**Comment by joethephish** [comment]
Fixed in de744aef5416594b915017bfa95b978c8f0f8cf2.
