### ISSUE TITLE
Adding Tags To Shuffles?

### ISSUE THREAD

**Issue by robin7crows** [inkle/ink#422]
I'm attempting to procedurally generate objects with tags in an Ink script; those tags would then be interpreted by the C# harness. For example:

{~a worn leather coat # battered | a slick leather jacket # shiny | a neat uniform jacket # uniform}

The problem seems to be that the parser is looking for "|" as the terminator and stops dead at the unexpected "#". But if the parser simply ignored the "#" and returned the whole string, it seems as if that string (including the tag) should be valid.

I've tried several workarounds; so far the best I've been able to come up with is something like this:

~ temp coatAdj = "{~battered | shiny}"
{
	- coatAdj == "battered": {really battered | a little battered | not too shabby} #battered
	- coatAdj == "shiny": {oh so slick! | impossible smooth | finest synth-fab} #shiny
}

Is there a better way to do this? And/or would allowing tags in a list be feasible?

Thanks!

**Comment by joningold** [comment]
You can rewrite your shuffle as a multi line block

{shuffle:
- a worn leather coat #battered
- etc...
}

And that would let you do further variation on each line too.

{shuffle:
- a {~ruffled|torn|worn} leather coat #battered
- etc...
}

Jon

**Comment by robin7crows** [comment]
Thank you so much! I'll give this method a try.

Robin Todd | robin@7crows.com | a sci-fi girl in a sci-fi world |
post-scarcity utopian anarchist
