### ISSUE TITLE
Request: warning when passing knot instead of divert to a divert-expecting function 

### ISSUE THREAD

**Issue by joningold** [inkle/ink#425]
The following source generates a runtime error ("trying to use an int as a divert target"). It's the only time when we type parameters in the engine, so could we catch this at compile time? 

(Catch: the parameter passed in might be a variable, in which case you can't catch it. But in this case where it's known to be a knot-name -- could we at least issue an appropriate warning?)

```
-> a (a) 

=== a (-> x) 
    -> DONE 

```

**Comment by joethephish** [comment]
Fixed in f30c0bab97ccace6b941ccf24a678e006dc30d77.
