### ISSUE TITLE
Bug: Compiler crashes if you try to define a list with duplicate keys

### ISSUE THREAD

**Issue by joningold** [inkle/ink#427]
```
LIST list = a, b 

~ list = (a, a) 

```

Creates a compiler crash rather than an error (or a warning, really.)

**Comment by joethephish** [comment]
Fixed in bb50c8a27eee055e8ed53313b7d632fadc64e62e. And also fixed crash when there are duplicate items in list definition in 9c7c6552653104f853652f3f3ad86249cde5e106.
