### ISSUE TITLE
VAR Error - game breaks!

### ISSUE THREAD

**Issue by Vornad** [inkle/ink#431]
I tried using ink variables in my new game project, and this resulted:

Exception: RUNTIME ERROR: Variable 'quest' could not be found in context '-1'. This shouldn't be possible so is a bug in the ink engine. 
Please try to construct a minimal story that reproduces the problem and report to inkle, thank you!

     I have chopped the game down to a minimal size that still creates the error. Did you want me to submit the Assets folder somewhere?

**Comment by joethephish** [comment]
Are you able to reproduce the error in inky? It would be good to know whether there’s an issue with the ink, or whether it’s something related to the game specific implementation.

**Comment by Vornad** [comment]
Do you mean by using the Unity Ink Player? The variables do show up and function properly there.

**Comment by Vornad** [comment]
My apologies for not being clear in the first message. I'm using Unity 2017v3.1f1 to build a visual novel game.

After troubleshooting all afternoon, I finally resolved the issue by:

a) moved 	'story = new Story (inkJSONAsset.text);'   from the Awake() function into the Start() function
b) disabled  'Using System.Collections.Generic; '  from the header

I'm not sure why those two maneuvers would have an impact, but the variables are working now.

Thank you for your attention :)
