### ISSUE TITLE
Question: Get tags on a choice line?

### ISSUE THREAD

**Issue by KumoKairo** [inkle/ink#433]
Can't seem to find a way to get tags of a choice line
`Player: What should I do? #fe_neutral`
`*	[Drink 1966 French Shiraz] # PRC 10`
`	-> drank_wine`
`*	[Pour wine out.]`
`	-> poured_wine_out`
First choice has a *PRC 10* tag which I can't get via the `story.TagsForContentAtPath(choices[i].pathStringOnChoice)`, it returns Null. There are no additional methods related to tags.
 `story.currentTags` returns tags from a previous narrative line. ("#fe_neutral" in this case)

**Comment by joethephish** [comment]
Sorry, right now tags can't be added to choices :-(
