### ISSUE TITLE
Question: Loose end warning when tagging a knot

### ISSUE THREAD

**Issue by KumoKairo** [inkle/ink#435]
I need some Ink advice. Here's the setup
Each knot represents a scene (read - background and setup). There may be different stitches inside, to which we divert explicitly in previous knots. There also may be no stitches inside. Example:

```
=== Jason_apartments
# BG jason_apt
Jason: So, this is it. I like an apartment to feel like home more than apartment. #fe_happy
```
Tag for a knot works ok without any warnings because there is no stitch inside.
Another example:
```
=== headquaters_after_jason_meeting
# BG HQ
    = success
    Jerry: Great job. This is why you’re our top agent. #fe_happy
    ...
    = failure
    Jerry: …this…my…is…undeniably the worst…Now he’s gone. #fe_sad
```
Now it gives warning about loose end at the line with the BG HQ tag. The tag itself is working OK.
There's no actual content inside these knots outside named stitches, only this scene tag, so there's no actual way to insert -> DONE (as warning suggests) after it. Removing the tag also removes the compile warning, but we really want to tag the knot itself, not the individual stitches, as it will require unnecessary repetition and copying (making it error-prone)

What is the best way to tag a Knot with nested stitches without this warning?

**Comment by joethephish** [comment]
Ah apologies! That’s an oversight on my part, I’d have to fix the compiler to remove the warning. In the meantime, you could just add `-> DONE` after the tag so it doesn’t complain.

**Comment by joethephish** [comment]
Oh sorry, didn’t read your description properly. Does it complain if you add a DONE?

**Comment by KumoKairo** [comment]
Yes, that's what I've tried right away:
```
=== headquaters_after_jason_meeting
# BG HQ -> DONE
```
Still displays a loose end warning
