### ISSUE TITLE
Using Ink for user-generated content

### ISSUE THREAD

**Issue by Vaakapallo** [inkle/ink#439]
Hi,

Wondering how to implement user-created (or modified really) scenarios to a game. Is there any reasonable way to get a built game to read custom INK files? So that within the game there is a dropdown pointing to a folder of INK files that then can be plugged into a scene. The INK files would naturally have very strict rules for content/names etc.

Though I guess compilation of INK is platform-specific so it might get pretty hairy.

Anyone tried or have any other suggestions for pulling off something like this?

**Comment by joethephish** [comment]
The current version of the ink-unity integration plugin doesn't support this because of the way we compile the ink files. But we're very close to being able to include the ink compiler in the game itself (see this pull request: https://github.com/inkle/ink/pull/438).

It should already be possible if you don't mind getting your hands dirty code-wise and if you're using the latest version of Unity. There's an ink `Compiler` class that you can use to compile custom ink files in the game.

**Comment by Vaakapallo** [comment]
Oh, awesome! Great to know it's feasible. I'll check up on this when I start making the feature.

**Comment by KumoKairo** [comment]
@Vaakapallo see https://github.com/kumokairo/ink/tree/features/3_5_runtime
It's now possible to include ink_compiler.dll into your build and use it to call `compiler.Compile()` directly at runtime on any platform

**Comment by Vaakapallo** [comment]
Great! Incredible timing!

**Comment by Vaakapallo** [comment]
Been finally trying to get this to work, but keep running to "missing reference" issues. And when I get the Compiler recognized, it forgets references to non-inklecate Ink.

Any materials or examples to get the configuration down? Or how do I get Unity to actually use the dll properly. 

I'm using Unity 2018.1 and enabled the experimental features to use .NET 4.x

**Comment by KumoKairo** [comment]
@Vaakapallo Just pass a plaintext ink into a compiler and get plaintext back, it's just basic file/IO handling, absolutely nothing Unity-specific. 
Add a file open dialogue, let people pick their .ink files, read their contents and compile them using [`compiler.Compille()`](https://github.com/inkle/ink/blob/master/compiler/Compiler.cs#L44) then write the story as plaintext JSON (using [`story.ToJsonString()`](https://github.com/inkle/ink/blob/master/ink-engine-runtime/Story.cs#L195)) to disk somewhere you know your user-generated ink stories will be stored. 
To make things more clear - you **need** custom wrap code for these operations, but as you can see it's mostly trivial (but project-specific) stuff.

**Comment by KumoKairo** [comment]
@Vaakapallo do you still need help with this? If not, feel free to close the issue
