### ISSUE TITLE
[Cyrillic] Input caret does not match actual position

### ISSUE THREAD

**Issue by Phenomen** [inkle/ink#443]
Here is initial caret (text cursor) position: 
![2018-07-04_11-15-35](https://user-images.githubusercontent.com/138311/42262247-c986fa98-7f7b-11e8-8120-8b96b6db5039.png)

That's what I get when I press "backspace":
![2018-07-04_11-15-57](https://user-images.githubusercontent.com/138311/42262277-df7a68bc-7f7b-11e8-9067-e95cc277bdfd.png)

As you see it removed character **»** few positions away from caret.
It only happens when I have cyrillic characters in line.

**Comment by joethephish** [comment]
We use [Ace](https://ace.c9.io/) for the editor. Would you mind testing whether the little embedded editors have the same issue on their site? Thanks!

**Comment by Phenomen** [comment]
Yep, looks like Ace's issue: https://github.com/ajaxorg/ace/issues/2119
