### ISSUE TITLE
InvalidOperationException when calling RemoveVariableObserver with no specificVariableName

### ISSUE THREAD

**Issue by MrMengis** [inkle/ink#444]
With Story.RemoveVariableObserver() I'm getting an InvalidOperationException: Collection was modified; enumeration operation may not execute. System.ThrowHelper.ThrowInvalidOperationException when removing the observer: 

```
foreach (var keyValue in _variableObservers) { 
     var varName = keyValue.Key;
     _variableObservers [varName] -= observer;
 }
```
This can be fixed by making a temporary key list for iteration.

```
var keys = new List<string>( _variableObservers.Keys );
foreach ( var varName in keys )
{
	_variableObservers [varName] -= observer;
}
```

**Comment by joethephish** [comment]
Ooops, thanks! Fixed in f30ac66752746f25a577b1045b7f6747f7cbb893.
