### ISSUE TITLE
Divert target parameters confuse the loose end detector

### ISSUE THREAD

**Issue by joningold** [inkle/ink#456]
In the following:

```
=== knot1
*   (xx) {func(-> xx)} option
    Loose end.


=== knot2
*   (xx) {func2(xx)} option
    Loose end.
      
        
=== function func(-> x) 
    ~ return true
=== function func2( x)     
    ~ return true
```
knot2 is marked as having a loose end; but knot1 isn't, when in fact, both do. It seems the presence of a divert target breaks the compiler's ability to detect the end-of-flow.

[apologies if I've reported this before; i feel like i have but can't find the issue.]

**Comment by joethephish** [comment]
Fixed in a4b58197.
