### ISSUE TITLE
[Feature Request] Built in support for Actors/Conversant and Printed Notes/Synopses

### ISSUE THREAD

**Issue by snarlynarwhal** [inkle/ink#462]
**Actors/Conversant**

I want to use Ink with Dialogue System for Unity using their [Ink integration](http://www.pixelcrushers.com/dialogue_system/manual/html/ink.html).

I hate having to write the actor/conversant tags at the end of the line since like so:

`Fetch my sword! Quick! # Actor=Knight # Conversant=Squire`

It's ugly both in the markdown and when testing in Inky. I do want to see it, just not as a tag since every line has an actor. I'd like to write it and see it when testing as such:

`Knight to Squire: Fetch my sword! Quick!`

The Ink engine could automatically detect the actor and conversant and store them as tags while removing them from the line text. I imagine almost every game needs this functionality so building it in can make game ink files much prettier to read and write. Non-game creators can ignore it altogether or toggle it on/off in settings if they do want to use it.

**Notes/Synopses**

Secondly, I want to not only write the dialogue in ink but also the story. At the moment I use [Fountain](https://fountain.io/) to write the script for my game. Ideally, I'd use Ink entirely since Dialogue System for Unity can use Ink. Fountain is nice does not suite games like Ink does. 

That being said, I would like the ability to write [scene actions and descriptions](https://fountain.io/syntax#section-action) that the engine ignores or has the option to ignore, but still get printed to the screen in Inky for testing. Comments should probably remain unseen, but having a tag for visible [notes or synopses](https://fountain.io/syntax#section-notes) would be quite nice. Maybe users can toggle the visibility of notes in settings too.

**Comment by joningold** [comment]
You can do all of this, but you’ll have to parse the text output yourself.
So when you run ink, look at the text that comes out and do some work on
the string:
If it looks like
Name to other_name: text
Then extract the conversant and recipient directly.

You could have another type of notation for story content.

This is how we do things for Heavens Vault.

But we’re unlikely to add this kind of thing to a main ink library because
it’s specific to a particular game design!

**Comment by snarlynarwhal** [comment]
Dialogue System for Unity loads the ink .json file and handles the parsing/rendering. But I can write a tool to convert notes/synopses to comments and handle the actor/conversant stripping/tagging and output a "processed" ink file which once compiled can get loaded into the dialogue system. Thanks for the ideas, this should work just fine!

**Comment by joningold** [comment]
The trouble is ink has quite a broad target space - from straight-up branching stories (which wouldn't use it), through to text-generation for menus / HUD layers in non-dialogue games. So this is definitely "things for people to add for themselves" for us, I'm afraid!

(Thanks for the clarification re: dialogue system; I hadn't investigated it before! Cool that it integrates with ink, and I'm glad you can find a way to do your processing step.)
