### ISSUE TITLE
Previewing Choice Only Text

### ISSUE THREAD

**Issue by Jayowend** [inkle/ink#464]
First of all I just wanna say.. Ink & Inky are so awesome and friendly to use, even for students! Not to mention the documentation is really detailed and in-depth! Really fortunate to have discovered this open-source engine, so thanks for that. It helped my team and I on a school project, a point-and-click game in Unity (C#) and it was a godsend honestly. 👍 

Anyway, one thing we thought about doing was previewing choice-only text on mouse hover. I couldn't figure out how to grab the full choice text—including the stuff after the brackets [ ]—with Story.currentText, and I believe choiceOnlyText isn't publicly exposed at all. So I ended up doing previews in a sort of hacky way which was save the story state, run the single line immediately following the choice path, and then revert the story state. i.e.

```C#
            // preview next line
            // store current state to prepare for future traversal
            var storedState = story.state.ToJson();

            // begin traversal
            lookingIntoTheFuture = true;
            story.ChoosePathString(story.currentChoices[choiceIndex].pathStringOnChoice, false);
            if (story.canContinue)
                story.Continue(); // continue one line to full choice text

            var choiceFulltext = story.currentText.Trim(); // the full text

            // return to original state
            story.state.LoadJson(storedState);
            story.ContinueMaximally();
            lookingIntoTheFuture = false;
```
To get something like this:

![Example](https://i.imgur.com/DtBfvfl.gif)
![Ink Script](https://i.imgur.com/75A9vSl.png)

This seemed to work fine for us, but then again our story wasn't very complex, not many tunnels, threads, etc. and we weren't looking at performance much so YMMV. Maybe there's a better way to do this, though I thought I'd share a way in case anyone else is looking to do something similar. For the future it might be convenient to get choice-only text exposed like currentText.

**Comment by joningold** [comment]
Hey!

That's a pretty great solution, actually. You kinda have to do it that way,
since the actual "real" text of the choice might vary at runtime, so could
be different from one minute to the next!

(We used to have this in the old version of the engine and we used it in 80
Days, though I can't quite remember what for now; it was called a
PeekAhead. It may yet go in as a "proper" thing to do.)

[Also - what a great feature; so when you choose the line you're already
half-way through reading it! ]
