### ISSUE TITLE
Is this a bug? Example from docs...

### ISSUE THREAD

**Issue by awhillas** [inkle/ink#466]
HI,

Nice work with the Ink markup language, saved me doing something similar myself. I was going through the `WritingWithInk.md` examples to get a feel for the language and this is giving me an error:
```
-> outside_honolulu

=== crossing_the_date_line(-> return_to) ===
*	"Monsieur!"[] I declared with sudden horror. "I have just realised. We have crossed the international date line!"
-	Monsieur Fogg barely lifted an eyebrow. "I have adjusted for it."
*	I mopped the sweat from my brow[]. A relief!
* 	I nodded, becalmed[]. Of course he had!
*  I cursed, under my breath[]. Once again, I had been belittled!
-	-> return_to 

=== outside_honolulu ===
We arrived at the large island of Honolulu.
- (postscript) 
	-> crossing_the_date_line(-> done) 
- (done)
	-> outside_pitcairn_island 

=== outside_pitcairn_island ===
The boat sailed along the water towards the tiny island.
- (postscript2) 
	-> crossing_the_date_line(-> done2)
- (done2)
	-> END 
```
is this right or is it a bug?

**Comment by joningold** [comment]
Oh, yeah; it uses up the option in "crossing..." first time, so on the
second time it runs dry. A useful example, but not quite the point I was
intending to make..!

**Comment by joningold** [comment]
The {|->->} will only work in you’re actually in a tunnel; check you
tunnelled in rather than diverting in.

->a->
Rather than
->b

**Comment by awhillas** [comment]
thanks... it was a copy/paste from the `WritingWithInk.md` doc...

**Comment by joningold** [comment]
Oh, well, it isn’t actually a tunnel at all, it’s using a parameter to tell
it where to go back to. To be fair tho the example in the doc does work
(Since it doesn’t try to run the sub block twice) and it is an example of
“something you don’t have to do because tunnels are better).

See the example directly after that one.
