### ISSUE TITLE
Compiler emits temp= instead of VAR= when updating a global

### ISSUE THREAD

**Issue by Skrylar** [inkle/ink#469]
Version: 8026e604ae68ead46ace4c9dee80d58be190109a

The spec says that updating a global should be done with `VAR=`, but my copy of Inklecate is doing something weird.

In the "global definitions" section it will emit `VAR=` to assign the value. Then later I write this:

`~ gdp -= 10`

And it actually outputs `{"VAR?", "gdp"}, "10", "-"` (as expected), followed by `{"temp=": "gdp", "re": true}` which is weird.

**Comment by joethephish** [comment]
Oops, good catch! I guess this was working because the runtime engine was always looking everywhere/falling back to globals anyway. Fixed in 8eb0d3204025fe27def5cabd487a2e8004c0d809.
