### ISSUE TITLE
Setting a LIST from an external function

### ISSUE THREAD

**Issue by micabytes** [inkle/ink#471]
Hmm... was trying to find this from the documentation, but didn't have any luck.

So, LISTs are a tremendously useful feature which - at least to my mind - increase the power of Ink by a lot.

One thing that's not obvious to me from the documentation (maybe I missed this?) is: how would you instantiate a list from an external function? Is this possible, for instance?

For example:
`LIST peopleInRoom = getPeople()`

A simple use case is for example starting a new story snippet by fetching the people in the room from the game state.

**Comment by joethephish** [comment]
Yeah, this has been a bit of a black hole in our documentation that a few people have asked about in the past. I just took a quick moment to write something up: https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#working-with-lists

**Comment by micabytes** [comment]
Awesome Joe. Thanks a lot.
