### ISSUE TITLE
Elegant way to interact with persons/objects in "room"?

### ISSUE THREAD

**Issue by micabytes** [inkle/ink#473]
Yet another List question.

A modified Wayne manor example.

```
LIST Characters = Alfred, Batman, Robin 
VAR persons = (Batman)
->a_room

=== a_room
~ persons = getPersonsInRoom()

~ describe_room(persons)

* Talk to person
  -> talk_knot_for_the_room
* Leave the room
  -> END

=== function describe_room(roomState)
{ roomState ? Alfred: Alfred is here, standing quietly in a corner. } { roomState ? Batman: Batman's presence dominates all. } { roomState ? Robin: Robin is all but forgotten. }
```
getPersonsInRoom() is an external function which grabs the list of people currently in the room from the game state. What I'd like to do, is to have the game display the portraits of the persons in the room during the a_room knot (easily done using a tag or directive to execute an external command). However, in addition, I'd like the game to divert to the talk_knot, when the person's portrait is clicked/pressed - and preferably not shot the "Talk to a person" option in text.

The naive way is to create a command for the room and hardcode the divert (i.e., not have it in Ink at all), but since I'll likely have many places where this will end up being done, I'd like to do it a bit smarter.

The best idea I've had so far is to create a standard variable (e.g., VAR talkDivert) which sets the diverts in each room, grab that and then force the jump to the set scene on a click. E.g.,

```
=== a_room
~ persons = getPersonsInRoom()
VAR talkDivert = ->talk_knot_for_the_room
# ShowPersonPortraits

~ describe_room(persons)

* Leave the room
  -> END
```

I think that should work, but I wonder if there is some more elegant solution that I may be overlooking?

**Comment by joningold** [comment]
I would simply have the game look out for choices with the text TALK
<person>, and when it finds them, prevent them being displayed on screen —
and instead fire those choices via clicking on the portraits instead. (And
if the game offers a choice for a character who isn’t around, the game
simply never offers it so it can’t be chosen.)

That way you can still test the game in inky; and the real game is just
turning the talk choices into a UI nicety.

You could still have a talk-knot and the main content knot; just include
the talk-knot using a thread:

<- talk-knot

... and that would let you, say, use the same talk knot in whichever room
you’re in.

**Comment by micabytes** [comment]
Of course... I already parse the text lines for similar reasons; no reason why I shouldn't do the same to the choices. Overcomplicating things a bit, there. Thanks.
