### ISSUE TITLE
Selecting the next knot with random chance

### ISSUE THREAD

**Issue by omid3098** [inkle/ink#484]
I want to have 3 kind of stories for the same scene of game, that Ink will chose it randomly each time the game is played.
and i want to set "chance value" for each of those lines. the greater the "chance value" more often it will be selected.

```
=== part 1 ===
- part 1 description
    + [choice1]  {-> part2|-> part3}  // Here we want part2 or part3 to be selected randomly
    + [choice 2] -> part3

=== part 2 ===
- part 2 description //  "chance value" 70%

=== part 3 ===
- part 3 description  //  "chance value" 30%

```

**Comment by joningold** [comment]
Does it need to be on a choice?

{
- RANDOM (1, 3): -> a
- RANDOM(1,2): -> b
- else: -> c
}

**Comment by omid3098** [comment]
Actually I think it should to be a choice. not sure as I'm pretty new to Ink
trying to understand if it is possible to make a Reigns like game using ink.
As far as I studied Ink so far one black-box is choosing random cards based on their chances to happen.
so as each card needs to have two choices and each choice send player to another card based on its probability, I guess the method you suggest does not cover this case.

**Comment by joningold** [comment]
If I was making a Reigns game I would have a central hub deciding what card
to go to via diverts; and then divert back to that hub at the end of each
card after the choice / outcome. But it depends on what you want to do!

**Comment by omid3098** [comment]
Actually this is an interesting approach but I don't think that it's easy to implement the hub inside Ink. And using ink to only hold card data without being able to test the results, does not seem logical.
