### ISSUE TITLE
[Documentation] Error in threads example code?

### ISSUE THREAD

**Issue by fireton** [inkle/ink#485]
I'm now in the process of translation ink documentation into Russian (I will make PR when I finish). I'm now at the Threads section and bumped into possible error in docs. Consider this fragment:

    == characters_present(room)
    { generals_location == player_location:
        <- general_conversation
    }
    { doctors_location == room:
        <- doctor_conversation
    }

What the `room` parameter is for? It never used in other code in example. But it compares with `doctors_location`. It's a bit confusing. Shouldn't it be same as `generals_location` - comparing with `player_location`?

**Comment by joningold** [comment]
That does look wrong; or like two different ways of solving the same
problem! Feel free to submit a PR to fix the English version.

Cheers
Jon

**Comment by joningold** [comment]
Don’t worry about it then; I’ll update when I get a moment. Thanks again!!

**Comment by fireton** [comment]
Thanks a lot.
