### ISSUE TITLE
Threads don't work in latest Ink

### ISSUE THREAD

**Issue by bladecoder** [inkle/ink#494]
Hi,

Threads are not showing the options in the latest Ink release (v0.8.2). Below is a screenshot with the thread example from the Ink manual.

![image](https://user-images.githubusercontent.com/6229260/48476718-1aad2900-e800-11e8-892a-df2b72bea82c.png)

**Comment by joningold** [comment]
That’s because END kills the flow entirely. In that case it should say ->
DONE

I’ll update the manual as necessary!

**Comment by bladecoder** [comment]
Yes, I just realised that the DONE was missing... I close the issue.

Thanks!
