### ISSUE TITLE
So many PRs for Table of Contents?

### ISSUE THREAD

**Issue by houfu** [inkle/ink#498]
I was about 30 mins away from contributing another PR adding a Table of Contents to the documentation: see also #323 #486 #404 #324 

Is there a reason why this PR is not being merged/accepted? When I was considering this issue, I also wondered whether it is easier to maintain the docs if they were split up into multiple files instead of having a TOC on the top of a very long single document. Is there a discussion on this?

**Comment by joethephish** [comment]
Apologies to everyone for now replying to the PRs!

In theory it’s a good idea, but Inky has its own TOC sidebar for the internal documentation that’s automatically generated.

Ideally, yes, we’d split it up into multiple pages. And ideally this would also all integrate into inky seamlessly! (I’m also happy for the way things are done in inky to be redone if there’s a better way.)

**Comment by houfu** [comment]
Oh that makes sense. I also didn't realise that inky already has an easier to read document (which makes this less critical than I originally assumed).
Will take a peak at inky to see how this can be resolved. In the meantime, closing this issue..
