### ISSUE TITLE
Updating Ink Nuget

### ISSUE THREAD

**Issue by barefists** [inkle/ink#500]
I'm working on a project running Ink outside of Unity, but on C#. The last version of Ink on Nuget was 0.7.4 from sometime last year.

It's not super urgent (because 0.7.4 is still very functional), but would Ink be updated on Nuget in the near future?

**Comment by teichert** [comment]
@barefists Does [this](https://www.nuget.org/packages/Ink.Engine.Runtime-Unofficial/) satisfy your use-case?
Possibly satisfies #683 as well?

**Comment by barefists** [comment]
Yes it does :)
