### ISSUE TITLE
visited for options

### ISSUE THREAD

**Issue by titusvk** [inkle/ink#501]
Is there a visited attribute for *-options in Ink? I only found this for labels.

Maybe a similar syntax like:  knot.stich.option(3)

With labels:

```
-> fight_guard.throw_something

=== fight_guard ===
= throw_something
*	(rock) [Throw rock at guard] -> throw
* 	(sand) [Throw sand at guard] -> throw

= throw
You hurl {throw_something.rock:a rock|a handful of sand} at the guard.
-> show_label

=== show_label ===
Label {fight_guard.throw_something.rock}
-> DONE
```

**Comment by joningold** [comment]
The rock label in your example refers to the option...?

**Comment by titusvk** [comment]
Ok, I only have to label alle options for visited once or more. Thank you.

**Comment by joningold** [comment]
The idea is - if you want to divert to, or test the visited property, of a
bit of content, you'll want to give it a definite name . If you don't want
to then it doesn't need a name.

Something more general like options(3) won't work though, as the number of
options is highly highly variable - and easily broken by editing.

**Comment by titusvk** [comment]
Completely right, number of option can break easily and leads to inconsistency, for example when changing the order of options or replacing orders.
