### ISSUE TITLE
Problem with conditional text

### ISSUE THREAD

**Issue by ABritish** [inkle/ink#505]
For some odd reason, whenever I want to write a  text which can only be seen if you have certain condition, it'll put 1 or 0 in front of it and it's really annoying and I don't know how to fix it
![bug](https://user-images.githubusercontent.com/42033365/51428660-7fbd3a80-1c06-11e9-9c8a-54532c8d17b4.png)

**Comment by jack-fractal** [comment]
Hey ABritish! This is because you're not quite using this correctly.

While you can have conditionals on options that work like that, to do conditional text, you have to include the text within the brackets.

Like this:

{spaghet == 27 : Oh my gerd!}

That will do what you want.
