### ISSUE TITLE
Lua, Ink and the Defold game engine

### ISSUE THREAD

**Issue by Aerobird98** [inkle/ink#511]
Hi everyone!

I need a [Lua](https://www.lua.org/) implementation for my game project in [Defold](https://www.defold.com/), but i couldn't find any suiting my needs. Altough I found an implementation called "[pink](https://github.com/premek/pink)", it doesn't seem reliable and looks abandoned.
[Lua](https://www.lua.org/) is an extremely powerful language so as [Ink](https://www.inklestudios.com/ink/)!
I want to make use of them alongside the [Defold](https://www.defold.com/) engine, because I've found [Unity](https://unity3d.com/) a bit too messy for my taste. My questions are the folowing:

- Is there a reliable implementation of [Ink](https://www.inklestudios.com/ink/) in [Lua](https://www.lua.org/)?
- Any suggestions on where to search?
- Or at least where to begin if I'd like to create one myself?
- Is it even posible?

Regards,

A.

**Comment by Natrium729** [comment]
I wanted to create a Defold project with ink too, but as you found out, there were no solid lua integration. I decided to write my own, but then other projects took my attention and I never started.

I guess that if you wanted to write your own ink integration, you would "only" need to translate [the C# integration](https://github.com/inkle/ink/tree/master/ink-engine-runtime) into Lua. But that's a fair amount of work.

If no one does it, then I think I'll do it when i'll need it, but that won't be soon.

**Comment by Aerobird98** [comment]
I've found a [ haxe](https://github.com/Glidias/inkhaxe) implementation recently that could be easily compiled to lua but others said that it is a bit slow compared to native implementations when compiled like this.

Anyway I haven't tried it out yet but if it's working then maybe I could improve it somehow?

If I manage to get it right with defold then I'll post my experiences and the code used in the proccess but since it is not as inportant for me right now it won't be soon either.

**Comment by astrochili** [comment]
You can try [Narrrator](https://github.com/astrochili/narrator). Any feedback is welcome 🙂.

**Comment by Aerobird98** [comment]
That's pretty  cool @astrochili, thanks! I will try it when I get to it, so closing this issue for now.
