### ISSUE TITLE
Choices not disappearing when returning to a knot?

### ISSUE THREAD

**Issue by alwaysusa** [inkle/ink#517]
In the documentation it says "By default, every choice in the game can only be chosen once.", however, this is not what's happening in my scenario, and I wonder if they changed that, or if I'm just using it wrong. Here's the scenario:

```
==first_knot==
Blah blah.
+ [Do A]
-> a_knot
+ [Do B]
-> b_knot

==a_knot==
You chose A!
-> first_knot 
```

In the above scenario, as I understand it my only option when returning to the first_knot would be + [Do B]. However, I still have both options.

Am I misunderstanding something?

Cheers!

**Comment by joningold** [comment]
A choice marked with a * will disappear. A choice marked with a + is sticky and will keep appearing. So just change your + to * above.

**Comment by alwaysusa** [comment]
> A choice marked with a * will disappear. A choice marked with a + is sticky and will keep appearing. So just change your + to * above.

oooo I see. Thank you!
