### ISSUE TITLE
Is there anyway to get the current line number or a unique identifier for a line of dialogue?

### ISSUE THREAD

**Issue by WilsonCWong** [inkle/ink#522]
Hi,

I wanted to implement a feature in my game that allows you to skip text you have already seen. I know you can get the read counts of knots and stitches, but this is quite inaccurate (e.g. I could be halfway through a knot and divert out of it, then when I return to that knot, all the content that hasn't been read now counts as read).

Is there anyway to get the line number that ink is currently evaluating or get a unique identifier for each line? Currently, I'm just planning to create a MD5 hash for each line of dialogue using the runtime path + the line of dialogue, then checking for this hash each time I call ```story.Continue()```. Unfortunately, this will still skip over lines of dialogue if there are lines that are exactly the same at that path (e.g. Path is ```chapterone.sceneone``` and there are two lines of dialogue that say "Ok", both will be skipped if only one of them is read).

Any suggestions would be appreciated.

**Comment by facelesspanda** [comment]
one way I would try to think about it is named gather points.

Like, you would write something like the following:
```
== knotA ==
= stitchAA
- (line1) Content
- (line2) More Content
```
which would give you variables like `knotA.stitchAA.line1` giving read counts.

but the overhead on this is significant, as each line would basically become its own little named object in memory, and the `.ink.json` file could be *really* heavy.

Depending on whether you want to skip any content already seen or just the ones "chronologically before", you could also do as you suggested: hash your content and store the hashes and then check if the hash has already been recorded. That'd skip over any line that is exactly the same one as any previously read line, but I don't think I've ever seen a "skip read" feature in a game that did not behave like that.

**Comment by WilsonCWong** [comment]
Yeah, that would be pretty heavy on the overhead. 

I believe Ren'Py assigns an ID to each line of dialogue and uses some diffing, so even a similar line would not be skipped (not that it isn't buggy at times). And now that I think about it, a line number would not be sufficient if I, for example, update the ink file with more content. Looks like either a unique ID or hashing is needed. I guess I could use gather points if I notice something is repeated so that ```runtime path + line of dialogue``` would give a different hash. This is prone to human error and adds slightly more overhead though.

One idea that I just thought of is including the previous line in the hash if it is in the same path as the current line. I think this will allow it to account for diverts and tunnels. Some lines will be counted as unread if they appear after any changed or new content that is added after the game is already started, but I think this is the best I can do without a unique ID.

**Comment by joningold** [comment]
This is indeed a hard problem, and a very relevant one, for games with localisation etc. We don't have a robust solution yet, but some people have used #tags on lines effectively to 'mark up' content themselves.
