### ISSUE TITLE
Is there a way to clear/delete the text from previous knots?

### ISSUE THREAD

**Issue by MarianaCacique** [inkle/ink#523]
Hi folks! I just started learning Ink and i bumped into something I don't know how to do. Is there any any to clear the text from previous knots/parts from the screen? I want the player to only be able to read the current knot

**Comment by facelesspanda** [comment]
a `#clear` tag at the top of the knot, and check for it at runtime to clear the screen?

**Comment by sasmlange** [comment]
I found out that it is `#CLEAR` (uppercase)
