### ISSUE TITLE
Action hover color fade out in HTML export

### ISSUE THREAD

**Issue by starry-abyss** [inkle/ink#525]
Hello, I'm both ink and html newbie. I'm using the latest release version: 

> Inky version: 0.10.0
> ink version: 0.8.2
> inkjs version: 1.7.1 with hotfix

I'd like adding a color fade out for actions' text, so I increased the transition here (style.css):

```
a {
    font-weight: 700;
    color: #3B3B6C;
    font-family: 'Courier New', Courier, monospace;
    transition: color 1.6s;
    text-decoration: none;
}
```

But it doesn't work for actual game, only fade in works - a.hover one

I figured that in the HTML page: `<div id="story" class="container">` - if I remove `class="container"`, then fade out starts to work! But text's boundaries are broken then, apparently...

**Comment by joningold** [comment]
CSS isn't my thing, but you might find people who can help with this over on the Discord channel: https://discord.gg/MUXj7Md

**Comment by starry-abyss** [comment]
That's what I did before creating the issue, got no answer...

**Comment by lunarcloud** [comment]
Could you attach or send me an example export? It might be more obvious in the full context.

**Comment by starry-abyss** [comment]
@lunarcloud Here: https://starry-abyss.github.io/a3a4a5/
It was a jam game, and I didn't find a proper solution in the end. I used CSS from the engine export, I just modified timings, colors, fonts, etc. This CSS works for both game and intro pages, except fade out, which is ignored in the game.
Notice how the 2 intro pages are custom ones (not from the engine), and color fade out after moving mouse from clickable text works. Then next pages are from the engine export, and fade out doesn't work.

**Comment by lunarcloud** [comment]
If you inspect your element in your web browser, you can see that the rules for " .container * " takes precedent over the rules for 'a'. It's been overridden. This seems like an error by someone who didn't realize these "transition" rules don't stack.
I think the " .container * " rules should really be " .container > * ", i.e. any immediate children instead of any elements inside. 
Good catch.

**Comment by lunarcloud** [comment]
But, this is an INKY issue, not one with this repository for Ink.

**Comment by lunarcloud** [comment]
Since merged, recommend closing this.

**Comment by starry-abyss** [comment]
Sure, thanks!
