### ISSUE TITLE
Implementing Save/Load in simple web-based game

### ISSUE THREAD

**Issue by PeppersGhostSCP** [inkle/ink#531]
You know how the [web tutorial](https://www.inklestudios.com/ink/web-tutorial/) was written with non-programmers in mind? I'm one of those folks. I was able to get everything up and running using the guide, but since my project is probably going to be rather long, I'd like to add a save/load feature. However, I can't find any documentation that spells out a simple way to implement this. Could I get a hand?

**Comment by joningold** [comment]
Hey! I just wrote up some stuff about this in the Discord server. It's *definitely* straight-forward and I quite strongly disagree with the other poster's remarks about needing to understand programming to achieve what you're after here. (And there are lots of helpful people on that server too.)

Reposting what I wrote there, here:

As you’ve found there are two lines of JS; one writes the game state to a variable in “local storage”; that just means it’s saved by the browser your players using. (Locally). The other line writes the state back into the story
You can do them either whenever you like, of course, but what you probably want is “save all the time” and “reload the save on reloading the story”
So for that
- stick the saving line into main.js on line 130, just before the comment that reads “tell the story where to go next”
- stick the loading line on line 5 of main.js just after “story = ...” (that’s what creates the story from your ink data)
(And ask if you need to know what the actual JS lines are for saving/loading; I don’t have them in front of me)

**Comment by PeppersGhostSCP** [comment]
You're the best! Thank you!  It works great. I'm surprised the solution turned out to be so simple.
