### ISSUE TITLE
NullReferenceException after modifying previously observed variable

### ISSUE THREAD

**Issue by zvinless** [inkle/ink#533]
Repro:
1. Call `Story.ObserveVariable(variableName, observer)` to observe a single variable
1. Remove the observer via `Story.RemoveVariableObserver(observer)` (either overload is fine)
1. Update the observed variable in Ink
1. Observe NullReferenceException in `Story.VariableStateDidChangeEvent` (the `observers` variable is null)

When a `VariableObserver` is removed, and it was the last observer for that variable, it remains in the `_variableObservers` dictionary but its value is `null`.

Suggestion is to either remove entries entirely from the dictionary if they're null immediately after removing the observer or just add a null check in `Story.VariableStateDidChangeEvent`.

**Comment by mdorr** [comment]
Ran into the same issue. See PR https://github.com/inkle/ink/pull/542 for a quick fix.

**Comment by zvinless** [comment]
Fixed by #542
