### ISSUE TITLE
[bug] Passing by ref via a divert target doesn't actually pass by ref

### ISSUE THREAD

**Issue by joningold** [inkle/ink#538]
In the following, using the "double" function via a divert target causing the pass by reference to silently pass by value.

```
VAR number = 1 
VAR func = -> double 

{number}
~ double(number) 
Should be 2: {number}

~ func(number) 
Should be 4: {number}

=== function double(ref x) 
    ~ x = x * 2 
```

**Comment by joethephish** [comment]
Unfortunately this isn't possible without a lot of work :-( The compiler needs to know ahead of time when generating parameters to be passed to a function whether to generate a variable reference or a value, and when the divert target is variable, it can't know.

This is potentially possible if we re-wrote the way that arguments are passed so they're determined at runtime based on new stored metadata about functions, but this would be a lot of work.

In the meantime, I've added an error message so you can't do this accidentally: bcef9a9f
