### ISSUE TITLE
Divert parameter not working with stitches?

### ISSUE THREAD

**Issue by tomhewitson** [inkle/ink#543]
Hi,

I want to be able to provide some generic choices & logic throughout the story but use context specific text where relevant.

I've been trying to achieve this by threading a second knot and the original knot as a divert parameter as shown in the docs and combining that with the relevant stitch address.

Here's a simplified example:

```
-> knot_1

====== knot_1
It plays this text each time instead of going to the relevant stitch
<- knot_1_choices
<- more_choices (-> knot_1)
-> DONE

= knot_1_choices
+ choice 1
    -> stitch_1

= stitch_1
1 -> END

= stitch_2
2 -> END

= stitch_3
3 -> END

====== more_choices (-> return_to)
+ choice 2
    -> return_to.stitch_2
    
+ choice 3
    -> return_to.stitch_3
```
 
The problem is that the diverts don't honour the stitch address component so it keeps taking me back to the start of the knot and replaying the whole text.

Not sure if this is intentional, a bug or user error? Any help would be much appreciated.

**Comment by joningold** [comment]
Divert targets are absolute addresses, so there's no such thing as "variable_divert"."particular stitch" - although that would be useful! If you want to achieve this, you'll need to pass all your target knots as parameters.

```
<- more_choices( -> stitch2, -> stitch3 )
...
==== more_choices(-> return_to_A, return_to_B) 
....
```

**Comment by tomhewitson** [comment]
Cool, didn't realise I could have more than one target as a parameter. That should work fine for now.

Thanks for your help.
