### ISSUE TITLE
Using RemoveVariableObservers throws NullException

### ISSUE THREAD

**Issue by bertaye** [inkle/ink#549]
Hi,
I was trying to lock some variables in my unity game for some conditions. So i thought that the best way for this is just removing the observer.

Since I was passing my observer function to ObserveVariable method as an anonymous function(just as how the API documentation does), I wasn't sure about how to remove it. I tried to remove it as an anonymous function too but it did not work . I also should note that I tried to pass myFunction -which accepts only one int parameter- to observeVariable method as delegate too but compiler didn't accept it.

I figured it out by changin _variableObservers dictionary to public and then i just passed it's value for specificVariableName and it started working!

But the problem is, now I'm getting NullReferenceException from

```
        void VariableStateDidChangeEvent(string variableName, Runtime.Object newValueObj)
        {
            if (_variableObservers == null)
                return;
            
            VariableObserver observers = null;
            if (_variableObservers.TryGetValue (variableName, out observers)) {

                if (!(newValueObj is Value)) {
                    throw new System.Exception ("Tried to get the value of a variable that isn't a standard type");
                }
                var val = newValueObj as Value;
                    observers (variableName, val.valueObject);
            }
        }
```
Unity says error is on last line.

I also managed to get rid off this by modifying last line with:

```
                if(_variableObservers[variableName]!=null)
                    observers (variableName, val.valueObject);
```

I was observing all variables with only one observer so I think when it gone it started throwing this error.

Also I wonder if it is possible to remove variable observers without modifying the original code? 

Thanks for advices!

**Comment by joethephish** [comment]
You could use a normal method as a variable observer so that you have a name to remove again:

```
story.ObserveVariable("x", MyVariableObserver);
story.RemoveVariableObserver(MyVariableObserver);
```
```
void MyVariableObserver(string varName, object newVal)
{
    // ...
}
```
