### ISSUE TITLE
Variables for Knots

### ISSUE THREAD

**Issue by joaobsneto** [inkle/ink#550]
Hi guys,

Quick question:

I was reading the documentation and I found 2 types of variables: global and temporary. I imagined that temporary worked like local variables, but they seem to work only inside a block of content. If I declare a temp variable inside a knot I cannot access them from stitches that are declared inside this same knot. Are there any type of variables for that or I have to use global variables?

Thanks!

**Comment by joethephish** [comment]
Sorry for the late reply! Yeah if the scope doesn't allow a `temp`, you will always have to fall back to a full global `VAR`. On the good side, you can declare it anywhere, so if you want to declare it within the knot, that's fine. It'll be accessible from everywhere else, but that style of global accessibility isn't frowned upon in ink.
