### ISSUE TITLE
ToJson and LoadJson are really unicode strings?

### ISSUE THREAD

**Issue by Remusforte** [inkle/ink#555]
This is more a question of nomenclature, to be sure I am using these methods properly.

When I call _inkStory.state.ToJson(), I am in fact getting back a unicode STR object, correct? 

When I inspect the output, it is a STR of a DICT, which contains the state info, or at least appears to be, yes?

If I want to save this to a file and reload it later, I am in fact saving the STR to a file, not the dict itself (which could just as easily be JSON saved). 

And when I want to load from a file and use the method: _inkStory.state.LoadJson(savedJson)
I am actually loading the STR data (as text), not the underlying DICT (which also could be just as easily JSON loaded).

**Summary:**
I am trying to be clear that these two methods are saving and loading a unicode **string** that contains the DICT info, NOT saving and loading a "true JSON" of the DICT itself. Correct?

**Comment by Remusforte** [comment]
The distinction I am trying to separate out probably isn't clear from that post. :-|
So let me try an example to show the difference I am poking at...

If I JSON save the output from _inkStory.state.ToJson() to a file using the json.dump method, I get the following .json file content:

`"{\"callstackThreads\":{\"threads\":[{\"callstack\":[{\"cPath\":\"\",\"idx\":0,\"exp\":false,\"type\":0,\"temp\":{}}],\"threadIndex\":0}],\"threadCounter\":0},\"variablesState\":{},\"evalStack\":[],\"outputStream\":[],\"currentChoices\":[],\"visitCounts\":{},\"turnIndices\":{},\"turnIdx\":-1,\"storySeed\":80,\"previousRandom\":0,\"inkSaveVersion\":8,\"inkFormatVersion\":18}"`

That is indeed a valid JSON file, but in reality it's just a unicode string in there. It could just as easily been saved as a text file and the called method could be named something like "inkStory.state.ToTxt()".

If instead I take the actual dict **contents** of the output from _inkStory.state.ToJson() and save it to a file using json.dump, I get the following .json file content:

`{"callstackThreads":{"threads":[{"callstack":[{"exp":false,"type":0,"temp":{}}],"threadIndex":0,"previousContentObject":"dog_wont_hunt.8"}],"threadCounter":0},"variablesState":{},"evalStack":[],"outputStream":[{"#":"bark(unit, 3500)"},"^never bark twice","\n"],"currentChoices":[],"visitCounts":{"dog_wont_hunt":1,"":1},"turnIndices":{"dog_wont_hunt":0,"":0},"turnIdx":0,"storySeed":55,"previousRandom":0,"inkSaveVersion":8,"inkFormatVersion":18}`

That too is a valid JSON file, and IMHO is more a "true JSON" in that it serializes the dict itself, not just a unicode string of the dict.

So... I'm just checking the the intent of these ToJson and LoadJson methods is really to manipulate (i.e. save and load) that **unicode STR**, not the embedded dict. Correct?

**Comment by joethephish** [comment]
Yes, it's a JSON string.
