### ISSUE TITLE
Possible to print RANDOM_SEED?

### ISSUE THREAD

**Issue by DawncallerDE** [inkle/ink#557]
I have seen that it is possible to set a specific seed, but is it possible to print the current seed so I can reproduce the exact playthrough of one of my users?

Thank you for your time!

**Comment by joethephish** [comment]
Sorry, that's not in the API. You'd have to store it yourself (and randomise it yourself if you like):

```
VAR seed = 0
~ seed = RANDOM(0, 9999999)
~ SEED_RANDOM(seed)

Seed on this playthrough is {seed}.
```
