### ISSUE TITLE
Is it possible to use a variable state to control a divert?

### ISSUE THREAD

**Issue by aumusic** [inkle/ink#558]
Hi,

I apologize in advance if this is a "newbie" question (and if I'm not explaining myself well), but is it possible to use a defined variable state to control a divert? At one point in my code, a variable is randomly set to one of two states, and that state is later supposed to divert to one of two different knots. I'm not seeing anything in the manual which explains how to do this, so is it possible?

Thanks in advance

**Comment by facelesspanda** [comment]
you missed it, it's in there: https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#advanced-storing-diverts-as-variables

**Comment by joningold** [comment]
I think you actually just want a multi line conditional like this

{ variable == whatever:
  -> go_somewhere
- else:
  -> go_somewhere_else
}

That first condition can be as simple or complex as you want, and inside
the conditional you can have text, logic or whatever.


-- 
Jazz, in Three-Four Time: A Novel
http://www.amazon.co.uk/dp/B004K1EYIE

**Comment by aumusic** [comment]
Joningold, that one did it! I had been trying something similar, albeit with a single equal sign.

Thank you again!
