### ISSUE TITLE
tailXNewlineIdx variables in StoryState.TrySplittingHeadTailWhitespace are from the beginning instead of the end

### ISSUE THREAD

**Issue by mwchase** [inkle/ink#565]
TrySplittingHeadTailWhitespace populates several variables in loops
```
            int headFirstNewlineIdx = -1;
            int headLastNewlineIdx = -1;
            for (int i = 0; i < str.Length; ++i) {
                char c = str [i];
                if (c == '\n') {
                    if (headFirstNewlineIdx == -1)
                        headFirstNewlineIdx = i;
                    headLastNewlineIdx = i;
                }
                else if (c == ' ' || c == '\t')
                    continue;
                else
                    break;
            }

            int tailLastNewlineIdx = -1;
            int tailFirstNewlineIdx = -1;
            for (int i = 0; i < str.Length; ++i) {
                char c = str [i];
                if (c == '\n') {
                    if (tailLastNewlineIdx == -1)
                        tailLastNewlineIdx = i;
                    tailFirstNewlineIdx = i;
                }
                else if (c == ' ' || c == '\t')
                    continue;
                else
                    break;
            }
```
The second set of variables is populated from a loop that works the exact same as the first. It looks like the second loop should start something like `for (int i = str.Length - 1; i <= 0; --i) {`

I don't know what kind of effect this loop being "wrong" has on the output step.

**Comment by joethephish** [comment]
Yikes, good catch, thanks! Fixed in acc6ddcea4f2429e2ce883a0ae4a3f0a0dd62727.

I do suspect though that the reason this hasn't been an issue is that nowadays the compiler always emits newlines as their own separate string objects in the engine, so the splitting is actually never necessary, and the method could probably be removed. But that's a consideration for another day!

**Comment by mwchase** [comment]
Hm. What happens if a line ends with an expression in curly brackets, that evaluates to a string ending in newlines?

**Comment by joethephish** [comment]
The string ending in newlines still has a separate text object for each newline character when it comes out of the compiler. I thiiiink this Trim method may be entirely redundant now. But I don’t have the confidence to rip it out without significant testing and triple checking first!

**Comment by mwchase** [comment]
I was thinking if, the game logic passes in a single string with the given structure. Then, the compiler isn't involved, because it couldn't see what happens at runtime.

**Comment by joethephish** [comment]
Yeeeees that’s possible then. Though it’s debatable whether should support it in the same way given the complexity it adds.
