### ISSUE TITLE
Mark options as "visited" in UI

### ISSUE THREAD

**Issue by kennedyrose** [inkle/ink#568]
I'm not sure the best way to accomplish this with Ink, but I'm trying to "gray out" dialog options that have already been selected by the player before.

I'm using Unity. Is there a way to get information on if a choice has been selected already or not? Or is there a way to simulate this somehow?

**Comment by joethephish** [comment]
Something like this should do it!

```
var choice = story.currentChoices[0];
var choiceVisitCount = story.state.VisitCountAtPathString(choice.pathStringOnChoice);
var makeItGrayedOut = choiceVisitCount > 0;
```

**Comment by kennedyrose** [comment]
This works great, thanks for the quick reply!

**Comment by BambooBandit** [comment]
I believe there must be a regression in Ink, because `story.state.VisitCountAtPathString(choice.pathStringOnChoice);` always returns 0
