### ISSUE TITLE
Flatpak package for linux

### ISSUE THREAD

**Issue by manuq** [inkle/ink#578]
Hi,
I have packaged `inklecate` for linux as a [flatpak](https://flatpak.org/) here: https://github.com/manuq/inklecate-flatpak

I would like to know if you are fine with this. If not, I can remove the package from that repo releases. Or, if you are happy with the package and want to add it to the releases of this official repo, then much better!

Regards,

**Comment by joethephish** [comment]
Fine with me! I’ve got enough to think about with the dependency graph of ink, Inky, inkjs, ink unity integration etc so not very interested in officially supporting another package, but very happy for your repro to exist!

**Comment by manuq** [comment]
@joethephish indeed is a lot to maintain officially and semi-officially already! Thanks for the reply! I'll keep the repo with the package then.
