### ISSUE TITLE
Allow Variables/Shuffles in Choice Text

### ISSUE THREAD

**Issue by lunarcloud** [inkle/ink#580]
This is illegal:
```
* {discover_cafe} {~Swung by|Went to|Detoured by|Strolled into} the cafe.[]
```

but this is valid (and less readable):
```
~ temp choice_a_text = "{~Swung by|Went to|Detoured by|Strolled into} the cafe."
* {discover_cafe} [{choice_a_text}]{choice_a_text}
```

**Comment by joningold** [comment]
The problem with the first line is that ink reads the shuffle as a condition on the choice. You can tell it not to do that with an escaped space

`* {discover_cafe} \ {~Swung by|Went to|Detoured by|Strolled into} the cafe.[]`

... though this still has an issue, that the text is shuffled once on generating the choice and then again on choosing the choice; so your second way of doing it is actually more robust.
