### ISSUE TITLE
Callstack and threads documentation

### ISSUE THREAD

**Issue by RokasVaitkevicius** [inkle/ink#585]
Hello, 

I was trying to understand in more detail how ink works and I got to threads and callstack, but it seems that documentation about them is missing [(link to docs)](https://github.com/inkle/ink/blob/master/Documentation/ArchitectureAndDevOverview.md#callstack-and-threads).

Is there any chance that these things will get documented someday?

**Comment by joethephish** [comment]
Oh, sorry! Yeah that's a pretty big topic, and given I don't have a huge amount of free time, it doesn't seem like something I'll get round to sitting down and doing any time soon.

I've removed the section and TODO comment for now. If you need help with something specific, feel free to hit me up [on our Discord](https://discord.gg/QYs6muQ)?
