### ISSUE TITLE
sequence choices

### ISSUE THREAD

**Issue by townbully** [inkle/ink#59]
Doesn't seem possible? E.g.:

Welcome to my Lair:
* {~ Thanks! | Great! | Love it here.. } -> good_reaction
* {~ Yikes! | Oh no! | [flee] } -> bad_reaction

**Comment by micabytes** [comment]
No, the syntax of Ink is such that the {} gets handled as a conditional (I had a similar observation in a prior discussion).

Without checking, I expect that you could label the nodes, e.g., as follows, and this would work as expected:
```
Welcome to my Lair:
* (good_react) {~ Thanks! | Great! | Love it here.. } -> good_reaction
* (bad_react) {~ Yikes! | Oh no! | [flee] } -> bad_reaction
```

**Comment by joethephish** [comment]
Another hacky although pleasantly short solution is to escape a space at the start:

    Welcome to my Lair:
    * \ {~ Thanks! | Great! | Love it here.. } -> good_reaction
    * \ {~ Yikes! | Oh no! | [flee] } -> bad_reaction

...since it forces the choice to go "into content mode" instead of attempting to parse a condition.

**Comment by townbully** [comment]
Thanks! That seems to work great. :+1:
