### ISSUE TITLE
Shared Story Does Not Auto-Scroll?

### ISSUE THREAD

**Issue by Erilis000** [inkle/ink#590]
When I view my story in Read or Write mode it automatically scrolls down as new paragraphs are shown, however it does not auto-scroll when reading the shared version.

Is that intentional? Bug?

Edit: people already seem to just be humoring me by reading my stories, not auto-scrolling is even more work for them, lol

**Comment by joethephish** [comment]
As mentioned in the other issue, this is the ink project not inklewriter. Inklewriter is maintained [here](https://github.com/inklewriter/freeinklewriter). Good luck!
