### ISSUE TITLE
Divert targets as parameters - not working as I expected

### ISSUE THREAD

**Issue by nairobiny** [inkle/ink#595]
I'm getting an error message when trying to pass a divert target as a parameter. I'd be very grateful if someone could explain why this doesn't work. It seems to be forgetting the reference to '-> thewayback' when it enters the thread. I would have expected it to remember the reference while inside the same knot. Is there another way I can do this?

```
This is the introduction.
-> first(-> theend)

=== theend
And this is the end.
-> END


=== first (-> thewayback)
This is the start.
-> loop

== loop
This is the first section.
* [Subsection 1] -> subsection1
* [Subsection 2] -> subsection2
* [Subsection 3] -> subsection3
* [All done] -> alldone

= subsection1
This is subsection 1.
-> loop

= subsection2
This is subsection 2.
-> loop

= subsection3
This is subsection 3.
-> loop

= alldone
OK, we're all done now.

-> thewayback
```

**Comment by nairobiny** [comment]
This is the error message:

![inkproblem](https://user-images.githubusercontent.com/17965147/82660038-89531a00-9c21-11ea-8056-ac14b0117ed0.png)

**Comment by joningold** [comment]
the parameter "thewayback" is local to the "first" knot; so it's thrown away when you leave that knot. (That includes to stitches within the know, which is what you'd have here if "loop" was "= loop" rather than " == loop").

I suggest you rewrite using a tunnel:

```
=== first (-> thewayback)
This is the start.
-> loop ->

Okay, all done now. 
-> thewayback

== loop
This is the first section.
* [Subsection 1] -> subsection1
* [Subsection 2] -> subsection2
* [Subsection 3] -> subsection3
* [All done] ->->  // this returns from the tunnel
```

**Comment by nairobiny** [comment]
That works. Thank you very much. I had presumed - wrongly - that stuff that was scoped to a knot would be retained until you reached a new knot.

Many thanks for the very fast reply.
