### ISSUE TITLE
Fill a List from Unity

### ISSUE THREAD

**Issue by jeuazarru** [inkle/ink#598]
Hello Everyone, I have a list of skills in Ink like:

LIST Skills = skill1, skill2, skill3... etc
Then I have a new list that uses the same components from the previous list:
VAR MySkills = ()
~ MySkills = Skills

I need to fill MySkills from Unity. That is, add only some skills from the first Skills list depending on player input. I already manage to fill VAR values with list items from Unity, thanks to a previous topic in this forum, but I'm not being able to fill a complete list with some values from Unity. I tried something like in c#;

var tempskills = new Ink.Runtime.InkList("MySkills", story);
foreach (Skill skill in ThisRun.MainCharacter.PersonajeSkills)  //this is a character class that has skill objects
{
 {tempskills.AddItem(skill.Name);}
}
story.variablesState["MySkills"] = tempskills;

but didn't worked. I tried some other things with no avail. Using listitems instead of list, etc. 

Can you help me with this? Or maybe telling me another way to do something similar?

My game is kind of a narrative RPG, and the player picks some skills in unity, and I want to transfer those skills to ink, so the dialogues will change depending on the skills you have picked. Before implementing the game in Unity I had a demo working exclusively through Ink, but now I am migrating it to Unity an connecting the variables to be able to manage them from there.

Thanks a lot!

**Comment by joethephish** [comment]
When you say it didn’t work, what went wrong exactly? Did you get an error?

**Comment by jeuazarru** [comment]
Hi Joe, thanks for the reply! There is no error, but the list is empty.

**Comment by joethephish** [comment]
Ah! Gave it a quick go, you have a mistake in this line - it should be: `var tempskills = new Ink.Runtime.InkList("Skills", story);`. The name should be `Skills` since it needs to match the *definition* list, not the variable name. Otherwise, your code works fine for me!

**Comment by jeuazarru** [comment]
Thank you Joe. I still have the same issue, the list in Ink is empty. I tested ant the list in Unity has the elements it should have. I did it that way before (with skills list) and changed it to myskills because it didn't worked. Maybe I am missing something else. I thought that there was not possible to fill a list completely from the variable in Unity, but if you said the code should work, I will keep looking at my code to find a bug in it?

**Comment by joethephish** [comment]
That definitely worked in my test, so there must be something else going on.

My only other thought is that it could be an order of operations thing. Like, if the line `~ MyList = ()` OR `~ MySkills = Skills` (that latter line is unnecessary btw) runs after you've run your C# code then it would wipe it out again - this would be if you set up your story, run the C# code, and then only start running the story after that?

**Comment by jeuazarru** [comment]
Thank you Joe!, that was the issue (~ MySkills = Skills) was erasing the data sent by unity to Ink, As I read in the ink documentation I understood I needed to set the list type by using that sentence, so the compiler can intepret the type of the new list, but it seems it is not necessary.

**Comment by joethephish** [comment]
Great, glad that's working!
