### ISSUE TITLE
Data Structure Question

### ISSUE THREAD

**Issue by jeuazarru** [inkle/ink#599]
Hello Everyone. I have a question about how to create data structures to organize better a project in Ink. Maybe some developers who had created big projects in Ink can give me some tips. My problem is that I am developing a kind of narrative-driven RPG in Ink with Unity (something like Disco Elysium in some way). The game has several characters, and each character can have Items, Skills, Health, and other relevant information attached. I haven't found a way to encapsulate that info, as in the documentations there are no data structures other than variables and lists (there are no classes, objects, arrays, etc.). 
For now I created global variables lije HealthJohn, HealthPedro, HealthMary, etc. and then lists of items like itemslistJohn, itemslistPedro, ItemslistsMary, etc. And then encapsulated that in functions so I can call something like HasItem(John,Knife) or CurrentHealth(John), or SomeoneHas(Knife) that in the end are just a dictionaries with a huge switch/case that looks for the variable assigned to that person and give back the value of it. But that is done by hand, and each time I add an Item, or a Stat, or a new character I have to go trough the process of creating more variables and lists, and add those to the function that search for the values… And in the end that is not scalable and prone to errors. 
There are better ways to do something like I need and have flexibility? Does the community has ideas? I have all that information in Unity, but I need the info in Ink because the interactions and dialogues depend on knowing if a certain character has an Item or a Skill (I am talking of NPCs (friendly or enemies), so there are a lot of them and the number keeps growing). That adds more complexity because I have to inject by hand the values of the specific variables from Unity to show the dialogues part when needed and be able to show different dialogue options based on it.
This situations is making me doubt if Ink is the right tool for my project, or if I am doing something very wrong, or if it might be better to use other narrative plugin like "Dialogue System for Unity" instead. I love Ink because its simplicity and elegancy, and I already programed a good Chunk of the game in it, but this situation is getting out of hand for me at this point.
Any thoughts are welcome. Thanks!

**Comment by Selsynn** [comment]
Hi, 
I think if you know how to do it in Unity, you could just have a pure external function to get the element like `getHealth(John)` or even `getParameter(John, health)` and calculating it on the unity version.
Warning, if you are in the current version, you'll have to update these variables with custom parsing to avoid problems (hence the `pure` element).

Another solution that I don't know if it is interesting or too long/difficult is to just have your custom way to do JSON, and stock the string as the John. You could do whatever you want with it, I am just not sure if it is really possible to do it in Ink. 

The last solution I see is to have each of your character with a very special nomenclature 
John_health, John_mana, John_gold, or even random name, and to hide that behind some  dictionary  function, totally in ink.
```ink
VAR John3267varshealth = 50

=== function getParameters(name, quality)
{
- name == John && quality == Health:
  ~ return John3267varshealth
- name == HarryPotter && quality == Gold:
  ~ return HarryPot156Gold
}```
That way you don't have to worry about your internal values. Whatever they are behind the scene, they will stay "nice" to work with. 
It's really verbose, but it's pure Ink.

**Comment by jeuazarru** [comment]
Thank you Maelle! I am currently doing exactly it in the way you mentioned (nomeclature+dictionary), but I found that very complex, prone to errors, and not scalable (I might have dozens of characters). I like your first idea and I believe it is the best way to go, and my question in this thread was if it was possible to do something like that. I am newbie in Unity, so I have no idea on how to do it, but I will investigate further. Or if you or anyone has an example I will be very grateful if I can take a look at it.

**Comment by jeuazarru** [comment]
UPDATE: I used External functions with great success. I Was able to obtain information on the flight straight from unity without needing to inject the info into variables or lists. This will speedup my development process and simplify a lot of the ink structure I was working on, so I can make calculations or evaluate options based on the Unity info. Thanks a lot for the support!

**Comment by brunurd** [comment]
I come here because I miss this feature too,   but my question is: exists some kind of roadmap with planned next features?

**Comment by joethephish** [comment]
I'm afraid we're unlikely to ever support built in features like objects/structures and arrays since the language isn't designed to be especially performant, and we wouldn't want to encourage too much full-on programming in it.

We don't have any new major features *planned*, so no roadmap at the moment. We're primarily focussed on maintenance, robustness, adding features that we need ourselves for our games, and supporting the community with adding theirs.
