### ISSUE TITLE
Stitch definition causes inklecate play mode to exit with a 'ran out of content' message

### ISSUE THREAD

**Issue by bitbutter** [inkle/ink#6]
I run the following test story via the terminal: (inklecate -p myStory.ink). 
```
===once===
Once upon a time there was a story.
= options
*	Read it
*	Ignore it
- The end.
-> END
```
I get the following output:
```
Once upon a time there was a story.
Runtime error in myStory.ink line 2: ran out of content. Do you need a '-> DONE' or '-> END'?
```
If i comment out the '= options' stitch, then it works as expected. It looks like including the stitch is causing a problem.

(OSX 10.11.3 i case it matters)

**Comment by joethephish** [comment]
You need a divert after the first line in the "once" knot. It doesn't automatically enter the first stitch if you include content at the top of your knot. Here's the fixed version in full:

    ===once===
    Once upon a time there was a story.
    -> options

    = options
    *   Read it
    *   Ignore it
    - The end.
    -> END

**Comment by joethephish** [comment]
I'll see how easy it is to add an error message for this specific case, because it could potentially be a gotcha for newcomers to the language.

**Comment by bitbutter** [comment]
Great thanks! (Maybe a note in the tutorial would be enough)

**Comment by joethephish** [comment]
Good idea, and done.
