### ISSUE TITLE
Documentation license

### ISSUE THREAD

**Issue by PiOverFour** [inkle/ink#602]
Hello, I’m working on [a tool](https://github.com/Kungsgeten/ink-mode) to edit ink files. I’d like to include the _Working with ink_ documentation with it. What license is it under?
It would seem it is under the MIT license like the rest of the code, which would allow me to re-use it, but since docs are often published under a different license, it is not entirely clear.

**Comment by joethephish** [comment]
Yup, it's MIT licensed - feel free to reuse!
