### ISSUE TITLE
Unity-integration: Ink recompilation takes a long time in large projects

### ISSUE THREAD

**Issue by patrickklug** [inkle/ink#608]
I'm having a problem where Recompiling the Ink library in my project takes AGES...
It seems that every single .ink file, regardless of how small it is, takes about 75 seconds to import. We have 55 files currently in the project and there will be 100s more in the future.

If I take the same files and push them into a new project, they all compile in about five seconds instead.

We have no local modifications to ink. From what I can gather, the only difference is the size of the project. From debugging the problem it seems that the calls to `AssetDatabase.ImportAsset` and `InkLibrary.Save()`as part of the `InkCompiler:CompileInkInternal` (which is called once per file) are the slow bits.

Is this a known issue?

**Comment by joethephish** [comment]
Discussion [moved to the ink unity integration repo](https://github.com/inkle/ink-unity-integration/issues/109), closing this issue.
