### ISSUE TITLE
Is there a Way to Observe/Print Ink Variables in Web Export?

### ISSUE THREAD

**Issue by omz85** [inkle/ink#609]
Hi, 

Very new to Ink/Inkle and programming in general here...

I'm not sure if this is possible or not but I want to create a crude "UI" within the Inkle web export to observe/track certain numerical variables (Health, etc) as they change within the Ink file based on choices the user is making so it's always at the "top" of the screen if that makes sense.

Any advice towards this (perhaps lofty) aim would be gratefully received.

Regards
omz

**Comment by Selsynn** [comment]
Hi, 

Ink side:
There is an extensive explanation here https://github.com/videlais/Unofficial-Ink-Cookbook/blob/master/Chapter13/index.md
what you want to do is specifically https://github.com/videlais/Unofficial-Ink-Cookbook/blob/master/Chapter13/index.md#observing-variables 

UI/vanilla JS/HTML side:
To update the UI, I will redirect you toward how to update in JS a span/div html element content. 
For example https://www.w3schools.com/js/js_htmldom_html.asp will get you the basics.

**Comment by omz85** [comment]
Hi Selsynn - thanks for the response.

I've had a look at the first link - and sorry if this is a terribly stupid question but regarding the "Observe Variable" function, I am adapting it from their example as follows to basically watch a "Health" variable in Ink:

story.ObserveVariable("Health", function(variableName, variableValue) {
  console.log(variableName, variableValue);
});

My understanding is this function is observing the variable "Health" already defined from within the story.js file and from the looks of things they are inserting this code into the main.js file just before the "//Generate Story Text" section. 

What is not clear to me is how the Javascript is recording this variable - is it creating a new variable for "Health" within the Javascript? My assumption is that I will also need to "map" this to an HTML variable using something akin to the following(?):

document.getElementById("health").innerHTML = Health

I've had a look at the second link you posted.. based on this. I'll probably need to look at this in more depth as it's becoming clear I may need to spend more time getting to grips with HTML.

**Comment by Selsynn** [comment]
> What is not clear to me is how the Javascript is recording this variable - is it creating a new variable for "Health" within the Javascript? My assumption is that I will also need to "map" this to an HTML variable using something akin to the following(?):

That would depend what you are doing in the body of :
``` 
story.ObserveVariable("Health", function(variableName, variableValue) {
console.log(variableName, variableValue);
});
```
^ Here it is just logging in the console (taht you can show by Options/Web Developper/Console) or F12 and the Console tab
It's not creating any variable. For your case you don't need any special new variable.

If you replace the body by 
``` 
story.ObserveVariable("Health", function(variableName, variableValue) {
document.getElementById("HealthDiv").innerHTML = "Health: "+variableValue
});
```
it will update the HTML element with an id of `HealthDiv` with the text `Health: 5` if the variable Health has currently 5

**Comment by omz85** [comment]
Thanks Selsynn - am I right in thinking all I need to add is that second bit of code you've posted and this will in effect both observe the Ink variable and directly merge this into a newly created string variable for the HTML called "HealthDiv" all in one go? Do I not need to define HealthDiv anywhere else?

I've put this in to my main.js file and seems to run fine but can't seem to get the HTML to print the HealthDiv variable.

**Comment by omz85** [comment]
Selsynn: ignore my last post. Turns out all I had to do was initiate a single change in Health within the Ink code and it triggered the observe function which allowed the HTML to start picking it up.

Absolutely fantastic - thank you so much for your help you have made my evening!

**Comment by omz85** [comment]
OK - just to clarify this has been solved also now. I didn't realise I needed to invoke the following in my HTML for it to work as well:

```
<div id=VitalityDiv></div> 
<div id=EnergyDiv></div> 
<div id=LucidityDiv></div>
```

All good!
