### ISSUE TITLE
Documentation for encoding of string values seems wrong

### ISSUE THREAD

**Issue by martinduvergey** [inkle/ink#61]
In file Documentation/ink_JSON_runtime_format.md it is stated that a string value must be prepended with ^ but in the examples string values are prepended with $

Given that the runtime looks for ^ at the beginning of string objects I guess that the examples using $ are wrong?

Regards,

Martin

**Comment by joethephish** [comment]
Oops, yes. We used to have a `Runtime.Text` object, but it was redundant since we also had `Runtime.StringValue`, which uses the `^` symbol.

Fixed, thanks!

**Comment by facelesspanda** [comment]
Docs still mention `Runtime.Text` here and there, I got confused. Namely [this comment](https://github.com/inkle/ink/blob/master/ink-engine-runtime/StoryState.cs#L242) and this [bit in the docs](https://github.com/inkle/ink/blob/master/Documentation/ArchitectureAndDevOverview.md#content)

**Comment by joethephish** [comment]
Pull requests happily accepted!
