### ISSUE TITLE
"came_from" error

### ISSUE THREAD

**Issue by marcharpin** [inkle/ink#622]
When I try to use the "came_from" structure Jon uses to such good effect in his "Blade Runner" talk, I get a "function call target not found:'->came_from'" error and the script won't run. Even opening Jon's Ink files from that talk ("interactive_final_ink" for example) gets me that same error. I'm running Inky on a Mac, if that makes any difference. Any suggestions would be appreciated.

**Comment by joningold** [comment]
Are you missing the actual function definition?

```
=== function came_from(-> x) 
~ return TURNS_SINCE(x) == 0
```

came_from isn't part of the ink language set; you have to actually include the function itself in your code!
