### ISSUE TITLE
Storing pure string into variable

### ISSUE THREAD

**Issue by metamorphium** [inkle/ink#647]
Hello,

Is it anyhow possible to store a pure string into a variable without being treated as Ink tokens? I need to do something like this:

~myVar = "{C:H}+={R:6}"

which would result to UE4 variable request to this very string.

I can of course create a substitution characters, but it makes it a bit more difficult.

Thanks!
Jan

**Comment by joethephish** [comment]
You can escape the curly brackets: `~ myVar = "\{C:H\}+=\{R:6\}"`

Not particular beautiful though, I'm afraid!

**Comment by metamorphium** [comment]
Thank you! That will do nicely!
