### ISSUE TITLE
GetIncludePaths parsing illegal characters -- Path.Combine error

### ISSUE THREAD

**Issue by crustforever** [inkle/ink#65]
I have two Ink files:

**Test.Ink**:

![test](https://cloud.githubusercontent.com/assets/6498456/14717938/c65ebf06-07c1-11e6-928a-4e90538bb76e.PNG)

and **Global.Ink**:

![helloworld](https://cloud.githubusercontent.com/assets/6498456/14717956/db319c0a-07c1-11e6-9083-9a0d977990e9.PNG)

I get this error when the plugin compiles:

![error](https://cloud.githubusercontent.com/assets/6498456/14717999/155f28c0-07c2-11e6-8073-f8b706bb7aa1.PNG)

I'd have a better analysis of the offending code but I don't have a working debugger at the moment.  Here's the GetIncludePaths code which has some weirdness that I've highlighted:
![getincludepaths](https://cloud.githubusercontent.com/assets/6498456/14718137/d3d84804-07c2-11e6-9015-2faf7e11e589.PNG)

"index+"?

And then I really don't understand this.  If I just comment out the include path parsing, everything works.

![working](https://cloud.githubusercontent.com/assets/6498456/14718421/95dea1d6-07c4-11e6-840b-5c6270a2087b.PNG)

![commented](https://cloud.githubusercontent.com/assets/6498456/14718427/9d9e2716-07c4-11e6-83a9-e3b10626ed23.PNG)

**Comment by joethephish** [comment]
That code deals with having multiple ink files included in each other using ink's `INCLUDE` statement, so as long as you're in one ink file, you shouldn't have a problem temporarily hacking out that code.

In the meantime, we'll investigate... thanks for the report!

**Comment by crustforever** [comment]
Thanks!  I'm still a little confused why my example of two Ink files with one referencing the other doesn't cause an issue but I think this is not worth looking into on your end until I can step through the code to figure out what exactly is happening...

If you're not seeing it, maybe it has something to do with whitespace or line endings?  Idk I'll get back to you with better evidence

**Comment by crustforever** [comment]
Okay so this did indeed turn out to be a Windows-only issue.  GetIncludePaths() is grabbing the '\r' part of '\r\n' (the Windows line ending).  Here's my line-ending agnostic version using System.Text.RegularExpressions:

		private void GetIncludePaths()
		{
			this.includePaths = new List<string>();

			Regex includeRegex = new Regex(@"^" + InkFile.includeKey + @"(.+?)\r?$", RegexOptions.Multiline);
			MatchCollection matches = includeRegex.Matches(this.fileContents);

			foreach(Match match in matches)
			{
				string path = match.Groups[1].Value;
				int invalidIndex = match.Groups[1].Value.IndexOfAny(Path.GetInvalidPathChars());
				if (invalidIndex >= 0)
				{
					Debug.LogError("Ignoring INCLUDE path '" + path + "' because it contains invalid character: '" + path[invalidIndex] + "'");
				}
				else
					this.includePaths.Add(path);
			}
		}

**Comment by joethephish** [comment]
Fantastic, thanks so much!

**Comment by crustforever** [comment]
No problem!  I'm now looking at GetIncludes() and it's checking each path in includePaths (which are relative file paths) against inkFile.absoluteFilePath, so in my environment where the relative path is not equal to the absolute path, the includes variable is not actually being populated!

Also InkInspector calls CreateIncludeList() when inkFile.includes != null instead of inkFile.Count > 0, so there is an empty includes list field in my inspector.

I am guessing that this is all just inspector business (and therefore not crucial) since the Ink figures out the INCLUDES properly once compiled to the JSON, but it's probably worth taking a look anyway.

**Comment by joethephish** [comment]
Yup, thanks for those too, very useful feedback. We'll take a look.

**Comment by crustforever** [comment]
disregard my previous comment about file paths!  i flubbed up

**Comment by Horatio-Blackwood** [comment]
Ran into this tonight - switched to unix-style line endings in my editor and voila!  All better.  Hope this helps.

**Comment by joethephish** [comment]
@tomkail - take a look at the replacement code by @crustforever that copes with the Windows line endings. (It should be able to cope without people having to switch to unix line endings)

**Comment by tomkail** [comment]
Closed!

**Comment by crustforever** [comment]
This is still listed as open.  Does that mean I have to close this? Or does @tomkail have the power?  I'm not sure how this works sorry.
