### ISSUE TITLE
Inklecate Crash When Compiling Ink Script with Conditional Statement

### ISSUE THREAD

**Issue by Horatio-Blackwood** [inkle/ink#66]
Using version 0.33 of ink, I ran into a problem with an ink script trying to use ink's ternary style operator on a variable to alter some text in-line.

I was hoping to use the following example from the WritingWithInk.md page to do this:

- "His real name was {met_blofeld.learned_his_name: Franz|a secret}."

But when changing 'met_blofeld.learned_his_name' to a different conditional statement, the compile failed and crashed out.  I've attached an ink script that (at least for me) demonstrates the crash, and a change I can make that makes the compile successful.  Neither one runs as I would expect (i get no output from this script at all and it seems like I should be getting something?  Not even the question at the beginning?)  I'm assuming that part is just something silly I've done wrong.

I don't yet think I understand the parser/compiler code enough to try to take this on myself, but figured I would just post up here since I found a repeatable issue.

[error.txt](https://github.com/inkle/ink/files/232848/error.txt)

**Comment by joethephish** [comment]
You've got too many curly brackets! Your ink should read:

`-	A cab driver holds a sign that says {character == CHAR_ONE: Char One|Char Two}`

However, obviously the compiler shouldn't crash, so we'll look into it.

**Comment by Horatio-Blackwood** [comment]
Joe,

Thanks for your response.  It seemed to me like I had too many braces too, but it was giving me trouble so I started trying things.  That does keep the compiler from crashing with the example script I shared.

HB

**Comment by joethephish** [comment]
Ah, but I just noticed, you still have a compiler crash even after making that fix. It looks like assigning a string to a CONST is buggy right now... I'd advise you use a VAR for now. Sorry!

**Comment by Horatio-Blackwood** [comment]
It seems as if you comment out EITHER the "cab driver" line or the "Who are you?" logic, it seems to compile.  Something about accessing that String constant I suppose?  Or accessing things that are set to its value?

Anyway thanks, I can deal with that - just tinkering with ink for now, so I'm happy to use a VAR for the moment.  

Thanks!

HB

**Comment by joethephish** [comment]
Fix for compiler's broken `CONST` in development branch, will push into master and ink-unity-integration soon: 2a09595b4bc4f67a1aad1f18e23c8f7e40157b8e
