### ISSUE TITLE
[QUESTION] Is there a list type for variables in Ink?

### ISSUE THREAD

**Issue by crustforever** [inkle/ink#67]

**Comment by joethephish** [comment]
Nope, not right now! Data structures are something we're considering for the (far) future but not coming any time soon.

Depending on what you're trying to achieve, you might be able to make use of sequences and/or switch statements.

Or put more complex data and logic on the game side.

**Comment by joningold** [comment]
Also; I often do "arrays of booleans" using an integer and powers of 2.

Jon

**Comment by crustforever** [comment]
Thanks!  Yeah it can be handled on the game side I was just wondering.

Another quick question: I just ran into an issue where an externally bound function with two parameters is flipping the parameter order.

**Ink**
EXTERNAL TestBinding(x, y)

{TestBinding("x", "y"}

**C#**
this.Story.BindExternalFunction("TestBinding", (int x, string y) => Debug.Log(x + y));

Produces the output:
yx

Furthermore, 3 parameters causes an error.

Is this something you're aware of? If not, I'll make a separate issue with better diagnostic info

**Comment by crustforever** [comment]
woops that C# part should be:
this.Story.BindExternalFunction("TestBinding", (**string** x, string y) => Debug.Log(x + y));

**Comment by crustforever** [comment]
the other one obviously throws a casting exception as it tries to cast the string "y" to an int32

**Comment by joethephish** [comment]
Hrm. I saw this bug before and fixed it! Will take a look tomorrow to
double check. What version did you download, and from where?

**Comment by crustforever** [comment]
It's version 0.3.3 downloaded from here: https://github.com/inkle/ink-unity-integration/releases

I'm on Unity 5.3.4f1 and I'm using Windows.  I am going to make a new empty project and revert my hacks that I made to InkFile.cs to account for issue #65.  I'll use Unix line endings and if it's still broken I'll make a new issue and just attach the whole unity project for you to look at.

Thanks for all the help!
