### ISSUE TITLE
Path.Component should implement or derive from *something*

### ISSUE THREAD

**Issue by mwchase** [inkle/ink#73]
> This function call doesn't seem to be equivalent - not sure why not?
> return otherPath.components.SequenceEqual (this.components);

I believe the problem is that SequenceEqual is comparing the components by object identity. I'm not really familiar with C#, but the docs indicate that **something** has to be different. Either Path.Component needs to implement IEqualityComparer, or perhaps IEquatable, or perhaps it should instead derive from EqualityComparer. The MSDN documentation makes _many_ recommendations.

**Comment by joethephish** [comment]
Thanks, implemented in f5965cbb1b1dd02c12dafca566c7b28f20e5a26d in development branch, should make it into a release very soon.
