### ISSUE TITLE
Returning a once-only from a function without evaluating it within the function

### ISSUE THREAD

**Issue by rezich** [inkle/ink#737]
Hello, I've just started playing around with Ink and I'm enjoying myself immensely. While writing a story, I found myself using the pattern `{!<strong>}Important Thing Name{!</strong>}` repeatedly, as a way of bolding names of important things, but only when they're first mentioned. After awhile this was cluttering up my code so I thought I'd try making a function:
```
=== function b1(x) ===
    ~ return "{!<strong>}" + x + "</strong>"
```
...but while this does compile, it does not have the desired effect. It seems that the "once-only" parts evaluate *inside* of the function (as opposed to *returning* the once-only parts and evaluating them at the call site, which is what I expected/hoped for), and the result is that only the first *use* of the `b1()` function is bolded.

Is there a syntactic way around this that I have not yet discovered? Or is this a limitation of the language?

**Comment by joethephish** [comment]
Sorry, afraid not. The internal counter that is used for the once-only content is stored only for that specific bit of text where it’s used. So the counter is within the function itself rather than where it’s called.
