### ISSUE TITLE
Checking if InkList item is set to true in C#

### ISSUE THREAD

**Issue by jugzor** [inkle/ink#742]
I see I can use `.ContainsItemNamed()` on InkLists to check if they have certain items. But this simply checks if the item exists in the list. How can I check if the list item is actually switched on or off?

**Comment by joningold** [comment]
Internally, "existing in the list variable" is being switched on. (There's
a separate ListDefinition object that handles what *might* be in the list.)

**Comment by jugzor** [comment]
Sorry, not sure I understand. 

In my Ink story I have an inventory list `LIST Inventory = weapon, armor, (potion)`. And then in C#:
```
     var inkInventory = Story.variablesState["Inventory"] as Ink.Runtime.InkList;
        
        if (inkInventory.ContainsItemNamed("weapon"))
        {
            // do something
        }
        
```
The conditional is returning true because the item exists in the list, but I want to check if the item has been switched on.

**Comment by jugzor** [comment]
> Internally, "existing in the list variable" is being switched on. (There's a separate ListDefinition object that handles what *might* be in the list.)
> […](#)
> Message ID: ***@***.***>

Sorry, not sure I understand. 

In my Ink story I have an inventory list `LIST Inventory = weapon, armor, (potion)`. And then in C#:
```
     var inkInventory = Story.variablesState["Inventory"] as Ink.Runtime.InkList;
        
        if (inkInventory.ContainsItemNamed("weapon"))
        {
            // do something
        }
```
The conditional is returning true because the item exists in the list, but I want to check if the item has been switched on.

**Comment by jugzor** [comment]
> I can't check it right now, but I'm pretty sure ContainsItemNamed will only return true if the item is switched on. That is, if ink doing {Inventory} doesn't list "weapon", then ContainsItemNamed will return false. Is that not what you're seeing?

Ahh it's working, your testing instructions helped me realize the issue was elsewhere in my code. Thank you! 

I'm dealing with a slightly different issue now. 
```
if (inkInventory.ContainsItemNamed("weapon"))
        {
            // do something
        }
```
This part was actually working before, because my mistake was automatically switching 'weapon' on while the game loaded. Now 'weapon' is off when the game loads, then it's switched on while the game is running when I select a dialogue choice. The issue is that the if statement does nothing now that I'm switching 'weapon' on during gameplay. It seems to have worked only with the values it had when the game was loaded. I've confirmed that 'weapon' is in fact being switched on when I select a dialogue choice. Any idea what I might be doing wrong? I have this in the update method, if that helps.
