### ISSUE TITLE
Enter tunnel by code?

### ISSUE THREAD

**Issue by Alex-Sand-0** [inkle/ink#744]
Hi,
In am wondering if there a simple way to enter in a tunnel from the c# api?
In other words: I can do something equivalent to  '-> somepath' (in ink) with the c# code  '_story.ChoosePathString("somepath")', but is there a c# equivalent to  "-> somepath-> " ?  
Ideally it would look like '_story.EnterTunnel("somepath")' 

PS: I think I could use flows to get something a bit similar, but it would not exit the flow on a "->->" would it? Actually I suppose I could make a special knot ==BACK== where I could call a function unstacking a flow, but that seems a bit convoluted... Is there something simpler before I re-invent the wheel?

**Comment by SirMetathyst** [comment]
Would it work to make a knot called somepathTunnel which would just tunnel into somepath? I haven't used ink in a while so maybe that won't work?

**Comment by Alex-Sand-0** [comment]
> Would it work to make a knot called somepathTunnel which would just tunnel into somepath? I haven't used ink in a while so maybe that won't work?

I do not think it would work, the exit of the tunnel would be at somepathTunnel , not at the (arbitrary) initial knot.

Actually I ended up using the flows to emulate a tunnel. I post my solution below in case it would be useful to anyone else, or in case someone as an idea to make it more robust.
(It 99% works, but could break badly if you either use mix threads with the tunnels, or use flows somewhere else in your code)

Essentially my solution to emulate tunnels with flows consist of: 
- a "tunneler class" keeping a stack of flows. Its API is simple:  a single function "EnterTunnel(knotName)"
- replacing every  "->->"  in my ink by  "->BACK"   . At the BACK knot we either: exit current tunnel if any, or exit the top flow, or go to DONE.


In my ink, I have this: 

```
 // Back() simply returns true if  ->-> if possible
// if not, it returns false, and unstacks the head flow in the tunneler if possible.
EXTERNAL Back()

== BACK ==
    { Back() : ->-> }
    -> DONE 

== function Back() == // for testing with inky
    ~ return true
```

and in c\#:

```
 public class StoryTunneler
    {
        const string _defaultFlowName = "StoryTunneler_DefaultFlow";

        readonly Stack<string> _flows;
        readonly Story _story;

        public StoryTunneler(Story story)
        {
            _story = story;
            _story.BindExternalFunction("Back", () => Back());
            _flows = new Stack<string>();
            _flows.Push(_defaultFlowName); // Ensure we can always Peek()
        }
        int TunnelDepth => _story.state.callstackDepth;

        public bool EnterTunnel(string flowname)
        {
            // entering in a new "tunnel" flow which is pushed on the stack
            flowname = flowname + $"_({_flows.Count})";
            _story.SwitchFlow(flowname);
            _flows.Push(flowname);
            return true;
        }

        bool Back()
        {
            //  This function should be called only from the "BACK" node
            if (TunnelDepth > 1)
            {
                // in a "normal" tunnel
                return true; // to go to "->->" in the "BACK" node
            }
            if (_story.currentFlowIsDefaultFlow)
            {
                // Cannot go back further
                return false;
            }
            var flownameBefore = _story.currentFlowName;
            if (_story.currentFlowName != _flows.Peek())
            {
                // here, something weird happened... did we enter a flow directly without calling TunnelTo?  You may want to log a warning.
               return false;
            }
            else
            {
                // normal case, just unstack a flow
                RollbackCurrentFlow();
            }
            return false; // not going to "->->" in the "BACK" node
        }

        void RollbackCurrentFlow()
        {
            var flowname = _flows.Peek();
            _flows.Pop();
            JumpToHeadFlow();
            _story.RemoveFlow(flowname);
        }

        void JumpToHeadFlow()
        {
            if (_flows.Peek() == _defaultFlowName)
            {
                _story.SwitchToDefaultFlow();
            }
            else
            {
                _story.SwitchFlow(_flows.Peek());
            }
        }
    }
        
```


PS: a side question, do you think I should close this issue? I am interested in eventual feedbacks/improvements on the solution above, but the solution is "good enough" for me now. What is the policy?

**Comment by SirMetathyst** [comment]
Hmm. If you believe your problem is solved, close it.
