### ISSUE TITLE
Feature Request: List of knots

### ISSUE THREAD

**Issue by tcconway** [inkle/ink#745]
Would love to see a "table of contents" feature, showing all knots as a list.

I imagine clicking on the 3-bars (the hamburger menu) at the top left of the app and see a top-tabbed interface. 

A tab could be "Knots", where it lists all the knots in the current file, based on the order they are written. Clicking one of them would jump the editor to that specific knot. This would be extremely helpful in working on large .ink files.

Another tab could be "files" as currently shown in the menu. 

Thanks.

**Comment by SirMetathyst** [comment]
Hello, If this is an editor feature request (which it sounds like it is) then this repository is where the editor is located: https://github.com/inkle/inky

**Comment by sasmlange** [comment]
In [Inky](https://github.com/inkle/inky), this feature exists.

**Comment by tomkail** [comment]
Sounds like this is addressed by the latest versions of inky. Closing!
