### ISSUE TITLE
Hiding choices according to old ones

### ISSUE THREAD

**Issue by essasquared** [inkle/ink#755]
I'm still rather new to this, but I've tried most tutorials, still do not understand what to do here. I want to hide a choice if a previous certain choice was taken before, for example:

---------------------
* "What's my name
-> reveal_name
*ask where you are
-> reveal_location
----------------------
So if the player asks their name, they'' be told their name. Let's say their name is Steve. So later on, when speaking with a stranger, the stranger asks their name.

----------------------
Stranger: What's your name, by the way?
*give him your name
-> tell_stranger_name
*"I don't know my name"
----------------------

So if they picked "What's my name" earlier they have the option to pick *give him your name, but if they didn't then the choice never appears on the players end.
How do I do that?

Similarly, if I had a choice like

*cut your hand off

how do i make it so that you could later on

*open door with doorknob
*kick door open
*walk away from door

how do I make it so that the *open door with doorknob    option is hidden if they cut their hand off earlier.

**Comment by Selsynn** [comment]
There is multiple manners to do this, but the two more useful are the label and the list tag system. 
Here is a sample using both

```ink 
LIST KnowledgeTags = REVEAL_LOCATION

*(REVEAL_NAME)"What's my name?"
//We declare the choice label, so we can just ask about it, and we will know if the player went through it
 reveal_name
* "Where you are?"
 reveal_location
 ~ KnowledgeTags += REVEAL_LOCATION
 //We add the tag to a knowledge list, so that we know that the player went through a choice that gives that information 
- After some time
"What's your name, peasant?"
*{REVEAL_NAME} "I am not mere peasant, I am Lord Examplus! You should address me as Your Lordship!"
    // This choice is displayed only if the player choose the label of  
*{(not REVEAL_NAME) and (KnowledgeTags has REVEAL_LOCATION)} "I don't know my name but I know where I am, that count for something, right?"
    //This choice is displayed only if the player didn't take the reveal name choice and also has the tags for knowledge, and the parenthesis are there for grouping the condition.
* "And who do you think you are to ask that?"
//This choice is displayed, no matter what
```

I encourage you to read about the labels, which may directly help you to do what you want.
(it's in the `tracking the weave` section of the documentation https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#3-tracking-a-weave)
It describe with more words and example what I did with the `REVEAL_NAME` part 

The other method is a bit more difficult, but can cover more thing (especially if you have multiple path covering the same information that you want to keep track) the documentation is here https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#1-basic-lists

**Comment by essasquared** [comment]
Thank you very much for replying! I am still a little confused though. I pasted the chunk of content I'm working on below. To test some of these functions, I am using this dialogue. If you look at the "median_ex" divert, I have a question that says "So.. Earth?" but when they ask, the being they're talking to calls them out for not knowing that there is more than just Earth in the universe. I want to track it as the player being (dumb) which is why I tried to put that label there. So later on when they are asking more questions in the "entities_q" divert, there is an option that disappears if they're already called out for being dumb. However, I get an error for an unresolved variable: dumb. I tried to do it like you did but it didn't work out. Does it not track across diverts maybe?


------------------------------------------------------------------
== void_loop2 ==
* "The Median?"
-> median_ex


== median_ex ==
The Median is the existential plane that you just came from. Consider it a mainland, the first attempt. An infinite universe with an infinite amount of planets, collectively housing an infinite amount of entities.
* (DUMB) "So.. Earth?"
-> shallow_mind
* "Entities?"
-> entities_ex

== shallow_mind ==
Ω: "ugh. Such a shallow mind on you humans. There's more than just Earth."
-> void_loop2
== entities_ex ==
Ω: "Yes, entities. Many planets house many conscious entities. You lived on planet Earth in the year 2022. The dominant species, humans, do not understand many of the concepts of the universe yet. They only see things that are made up of cells as conscious entities. For that, they are fools."
-> entities_q

== entities_q ==
* {(not DUMB)} "Are you telling me that there are living extra-terrestrial beings out there?"
-> other_planets
* "Does that mean that there are things in the world that we think aren't conscious but they actually are?"
-> unknown_beings
* "huh.."
-> void_loop2
---------------------------------------------------------

**Comment by essasquared** [comment]
Update: I figured it out :)
For anyone wondering, you can use my example. What I needed to do was track it to the divert as well. It's like trying to search a street address without a zip code. The divert is the zip code. So for the "Are you telling me that there are living extra-terrestrial beings out there?" I had to put {(not median_ex.DUMB)}

DUMB is the street address but median_ex is the zip code. Without putting median_ex in there, the program could pull up a few labels that are set as DUMB, but you can narrow it down for the program by adding the zip code, or divert. Hope this helps people who were stuck like me, and thank you @Selsynn :))
