### ISSUE TITLE
[Question] Best way to compile ink files runtime

### ISSUE THREAD

**Issue by nibylec** [inkle/ink#78]
Hello! 

I am writing a standalone tool for writers that will allow them to edit, save, load and most importantly: compile and run the written story. More or less it will be what you have specified in Readme: 

"A more friendly install-edit-play flow for writers. For example, a downloadable GUI-based app with an editor pane on the left and a play pane on the right".

CurrentIy have run into a problem that I need to compile ink files during execution of unity game. I started to read the ink compiler class in ink's engine and I wanted to mimic the functionalities that I need, but decided to ask for some tips and possibly a preferred way to do this before I dive deeper.
Maybe there is already an API to do this but I missed it somehow? 

Thanks!
Witek

**Comment by joethephish** [comment]
Hrm. So, the compiler is a separate command-line tool (unfortunately it uses modern C# that mean it can't be compiled direct into Unity). You'd have to embed it (inklecate.exe) into the app, and call it separately using C#'s Process class. Have a look at the ink-unity-integration project to see how exactly this is done.

To be honest, I'd question the use of Unity to build a pure GUI-based tool though? (assuming I understand what you're doing)

**Comment by nibylec** [comment]
This is exactly what I needed.  Thanks!

**Comment by joethephish** [comment]
Cool, good luck!

**Comment by bliu886** [comment]
I'm doing something similar where I'm working on a Unity app where the people authoring the dialog are able to change the text even while the app is running. The app needs to be able to run in WebGL, Windows, and MacOS. Is there a way to compile ink files at run time?

**Comment by joethephish** [comment]
Not out of the box. Previously the problem was that the compiler used new C# features that weren’t supported by Unity. With their move to support those features now, it ought to be possible to compile the compiler (!) directly into Unity games.

I’ve never tried it though, and we’d be unlikely to do this by default until the newer versions of Unity become more widely used by developers.

**Comment by bliu886** [comment]
Hey joethephish, thanks to your direction, I was able to compile the compiler in Unity 2017.4.0f1 by changing the scripting runtime version to the experimental .NET 4.6 in the player settings.

**Comment by joethephish** [comment]
Awesome!
