### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by robin7crows** [inkle/ink#79]
Imported the most recent Ink/Unity Integration asset library and now get the attached errors in an endless loop whenever I try to compile a file. This happens with a new test project as well using the default Hello World Ink file. Any thoughts more than appreciated. Thanks!

Running Unity 5.4.3f1 on Windows 10.

![unityinkerror](https://cloud.githubusercontent.com/assets/19244980/15095402/30a9d896-1479-11e6-9084-e2076c38cee8.jpg)

**Comment by robin7crows** [comment]
Did a complete uninstall of Unity; re-installed from scratch; imported UnityInkIntegration 0.3.4. Did Create/Folder under Assets called Ink, and inside that folder Create/Ink. Named file Hello World. Immediately got the same result O.o

**Comment by robin7crows** [comment]
Additional info: I pulled the .ink files out of the sub-folder into Assets root, everything worked fine. Moved the .ink file back into the sub-folder, the error returns. Changed name of sub-folder to Blah, error still occurs. So error appears to be triggered by having a .ink file in a sub-folder below Assets.

**Comment by tomkail** [comment]
I've no idea why the structure of your files was creating a problem, and can't replicate it, but I can see how the endless loop might have happened. I've pushed a fix. Let me know if that doesn't fix it!

**Comment by ocofiz** [comment]
Same issue here, but found out something!
Opening InkCompiler.cs and following code execution step by step, I found that the method `GetInkFileWithAbsolutePath` called inside `CompileInk` at line 110 returns null when the .ink file is in a subfolder!
Going deeper I saw that the problem is in an "if" comparison:
```
if(inkFile.absoluteFilePath == absolutePath)
```
that returns false even if the paths are equals. This depends on the path separators on Windows: some are "\\" and others are "/". The two paths uses different separators, so, even if pointing the same file, strings are not equals!

**Comment by tomkail** [comment]
Ah, that sounds likely. I've seen this before - thought i'd fixed most the instances of it, but we're mac users and it's hard to track down! I'll fix it now.

**Comment by tomkail** [comment]
Ah yup, I see it. Good spot, thanks for your help! Let me know if the latest doesn't fix it for you - I'm just about to upload a new package (0.3.4 Hotfix 1) here, and I've pushed to the repo.

**Comment by tomkail** [comment]
Package can be found at:
https://github.com/inkle/ink-unity-integration/releases

**Comment by joethephish** [comment]
Hotfix package available here: https://github.com/inkle/ink/releases/download/0.3.4/UnityInkIntegration0.3.4_Hotfix_1.unitypackage

**Comment by joethephish** [comment]
Try again, hotfix package here:
https://github.com/inkle/ink/releases/download/0.3.4/UnityInkIntegration0.3.4_Hotfix_2.unitypackage

**Comment by ocofiz** [comment]
Great!
Everything works fine, now!
Thanks!

**Comment by robin7crows** [comment]
Thanks so much for the fast fix everyone! I'll pull down the hotfix and integrate into my project this evening.
