### ISSUE TITLE
Outdated Linux Launch Instructions

### ISSUE THREAD

**Issue by Shinigami072** [inkle/ink#791]
It seems that since version v1.0.0 launching on linux does *NOT* require to be run by `mono inklectate` like in the Readme file - instead as suggested by [SirMetathyst — 07/03/2022 on discord](https://discordapp.com/channels/329929050866843648/329929390358265857/993144924570652732) the  program should be run directly `inklecate`, in addition the current rreadme file still contains the `inklecate.exe` filename - from when the linux and windows were packaged in the same file.

To reproduce:

Ubuntu 20.04
(With `mono-complete` installed) 

Try to run 
`mono inklectate`
Result:

```
Cannot open assembly 'inklecate': File does not contain a valid CIL image.
```

**Comment by cidneyhamilton** [comment]
Just noticed this for the first time too (six months later). Submitted a pull request to fix.
