### ISSUE TITLE
How to refresh content/variable status

### ISSUE THREAD

**Issue by lhughes41** [inkle/ink#797]
This is perhaps a bit tricky and I understand if that is no good solution. But hoping!:

So for Burden of Command (a python based game) I integrate scripting commands for Burden into Ink for the writers (my script calls are signaled by '#' ). Generally has worked out very well. In particular, I wrote a Burden command that takes a variable value from my engine and inserts into a ink var for the writers to play with. All good.. EXCEPT the timing of when Inkle appears to look at ink variables and use them in generating content lines vs when I update them via my script commands :-(

Specifically if I:
1. trigger an ink knot 
2. issue a Burden command ('tag'  in your language) to set an ink variable to the value of one of mine - **it definitely updates**.
3.  pop on screen a game dialog box showing that ink variable value... THAT VALUE IS OUT OF DATE. It does **not** reflect the new value I shoved successfully into your Inkle engine! 
4. So it appears that your Inkle engine has precomputed content lines before execution reaches my command call.... Understandable..
**5.  **My question** - is there a way I could force Inkle to recompute the next content line? So it gets the newly updated variable value into its next content line.**   We have found a work around - which perhaps gives you a clue - which is to pause the Inkle engine flow with a choice (we simply offer a [continue.] to user.  Once the user chooses to continue this seems to update the next content line again (or probably delay its computation) and now we get right value. But this is awkward and easy to forget. I am hoping there is something I could say to your engine that would force it recompute it's next content line. So it would get the updated ink variable value I inserted.

An example to make this more concrete:

_---- EXAMPLE PSEUDO INK SCRIPT -----
// Ink variable I will manipulate.
VAR ldr_OOA_status = "not set"

===tmp_knot===
// 
#--- triggers ---
// Here would be my triggers in Burden that decide if the commands below will be executed and that this knot will be jumped to in Inkle.
#<VARIOUS TRIGGERS YOU DON'T NEED TO BE BOTHERED WITH ;-) ) >

// the Burden commands if triggers above succeeded
#--- commands ---
// I GRAB A VALUE FROM MY ENGINE AND SHOVE IT INTO INK VARIABLE 'ldr_OOA_status'
//  I definitely succeed in setting it via 'attribute_to_ink_var' below
// (which uses your variablesState.set_Item):
#attribute_to_ink_var(test_ldr, "OOA_status", "ldr_OOA_status")

// I try to show that ink variable's value in a Burden dialog box
#choicebox('OOA_status var test)
// THE VALUE IS **NOT UPDATED** HERE even though I successfully set it above :-(
//  In other words it shows the value as it was when jump to knot happened. Even though
// my command above did update it inside your Inkle engine :-(
Var 'OOA_status' variable value is: {ldr_OOA_status}

-> DONE
------------------------_

My guess is your Inkle engine precompiles content lines for this knot as soon as it gets ready to enter the knot. So my updating your ink variable ("ldr_OOA_status") arrives too late in execution.

So see #5 as the question.

p.s. Thinking about why our workaround of putting a choice 'pause' in works. Is there a way I could tell the engine directly to pause ("can't continue") without asking writers to do? Then I would maybe release that inside my code after my command to set the ink variable had executed? I.e. do what they do as writers but do it behind scenes problematically. But better would be if I could just ask Inkle engine to simply refresh it's next content line. Or similarly ask it to backup where it is in content after I have had my 'lookahead' peek on content and tags. So ideally refresh, or backup,  now that my command has updated the ink var. Or if there is a lookahead/peek for next content and tag that does NOT advance the content pointer that could help me fix too ;-) Thanks!
p.p.s. I worked on this quite awhile after this post  and figured out the core issue was that asking for next line of content AT SAME TIME gets tags. So therefore my ink var updating tag (command) can't execute before the content updates. And I see no way to just get tags before content (is there?). Therefore my workaround is now simply to have a keyword piece of text (e.g. "REFRESH_INK") which will be ignored by my engine but allow your engine to update tags without any content truly changing (since I ignore 'refresh_ink'). So bottomline until you can suggest something cleaner this will work ;
_# attribute_to_ink_var(test_ldr, "OOA_status", "ldr_OOA_status")
REFRESH_INK//<--- IGNORED BUT ALLOWS my tag to update before this line:
Var 'OOA_status' value is: {ldr_OOA_status}_

Sorry for such a long post but was trying hard to be clear. And I would still love a cleaner programmatic  Inkle approach.

**Comment by joningold** [comment]
So it’s hard to diagnose remotely but
- continue is *the* way to get ink to process a line of content. The only
alternative is continuallyMaximally which is just a while loop of continue
calls.

- It seems like your triggers are using #tags. A tag is a markup to a line
of content; and as such is only passed to the engine after the content line
has been computed. (It’s meant to say, this line in #this way.)

I suspect what you want is to fire your triggers using an external function
call using the new “lookahead safe = false” setup which forces the function
call to only happen once, and be done with before the content continues.

**Comment by lhughes41** [comment]
Thanks for quick response Jon. Yes my final analysis is similar: asking for a line of content at the same time pulls in cotemporaneous tags... leading to the latter's execution *after*  the content line has resolved. So the latter's variable access happens before my tag command updates the variable.
  "lookahead safe = false" seems like right kind of idea. Not so sure I can easily pull that off in a Python setting though :-( So my workaround will be having a throwaway content line  between my tag and the real line of content (e.g. "REFRESH_INK") to get my tag command to fire before the real line of content happens.

 Thanks!, 
   Luke
