### ISSUE TITLE
Empty lines between paragraphs

### ISSUE THREAD

**Issue by TApicella** [inkle/ink#8]
I did not see this mentioned in the tutorial anywhere so I don't know if this feature exists, but it would be nice to be able to have a blank line between paragraphs or between prompt and selections. For instance, I'm trying to make a quit game prompt:

=== quit_prompt(-> return_to) ===
Done so soon? 

* [Yes, I'm outta here!] -> quit_game
* [No, let's keep going] -> return_to

But I would want it to display a space between the prompt and the choice, as a stylistic decision, and there are many cases where you are writing longer paragraphs where whitespace would be helpful.

**Comment by joningold** [comment]
So, this kind of thing is really in the presentation layer - so if you want
line breaks, then you should alter the way the game UI works. You could add
markup if you wanted: say, if the text of a line is "..." you could convert
that to a paragraph break in game.

Note the console test framework isn't really designed for making games
with.

**Comment by joethephish** [comment]
Potentially we could consider allowing a backslash on its own on a line to mark up an explicit new line. Essentially, escaping a newline. Would have to consider how this would interact with glue though.

**Comment by joningold** [comment]
I guess. It'd have to play nicely with the markup parser step too -- my
feeling is it's a specific problem for specific games to solve.

**Comment by michelmcbride** [comment]
Just wanted to throw in my 2 cents that I agree it should be left up to the presentation layer.

**Comment by joethephish** [comment]
Yup, okay, agreed!
