### ISSUE TITLE
[1.1] Tag in choice appearing in choice text

### ISSUE THREAD

**Issue by smwhr** [inkle/ink#801]
The tag in a choice appears inside of the choice text.

**Minimal ink to reproduce :**

```
* a choice # a tag 
    the result
```

**Reproducible evidence :**

![image](https://user-images.githubusercontent.com/1090485/196742761-6dba0c8c-a677-44c4-9d40-0f621bc52a49.png)

**Expected behaviou :**
`a tag` should not appear in `choice.text` but rather in `choice.tags`

**Comment by smwhr** [comment]
[Great work](https://github.com/inkle/ink/commit/7fcc40ad5b3be8a248a3bfae4bfa27c034292ddb) @joethephish !

**Comment by joethephish** [comment]
Thanks, fixed!
