### ISSUE TITLE
TagsForContentAtPath returns null

### ISSUE THREAD

**Issue by dannflor** [inkle/ink#826]
Calling `story.TagsForContentAtPath("path")` gives me a null even when my story looks like this
```
=== path ===
#tag: test
first line of content
```
The tag then shows up in `currentTags` when I call `Continue()` and get my first line of content.
Even if it couldn't find any tags, it should return an empty list, not a null. But it should be finding my tags!

**Comment by dannflor** [comment]
I can see the issue is here
```csharp
bool inTag = false;
List<string> tags = null;
foreach (var c in flowContainer.content) {

    var command = c as Runtime.ControlCommand;
    if( command != null ) {
        if( command.commandType == Runtime.ControlCommand.CommandType.BeginTag ) {
            inTag = true;
        } else if( command.commandType == Runtime.ControlCommand.CommandType.EndTag ) {
            inTag = false;
        }
    }

    else if( inTag ) {
        var str = c as Runtime.StringValue;
        if( str != null ) {
            if( tags == null ) tags = new List<string>();
            tags.Add(str.value);
        } else {
            Error("Tag contained non-text content. Only plain text is allowed when using globalTags or TagsAtContentPath. If you want to evaluate dynamic content, you need to use story.Continue().");
        }
    }

    // Any other content - we're done
    // We only recognise initial text-only tags
    else {
        break;
    }
}

```
Because of the way that tags are added in an `else if` to the `if (command != null)` clause means that the `else if` will never evaluate to true and no tags will ever be added. I can make a pull request to fix this, but will it actually get merged into a release? I don't want to waste my effort if it's not.

**Comment by joethephish** [comment]
I'm actually not managing to reproduce this - I tried pasting your sample ink into a test file and `story.TagsForContentAtPath("path")` gives me the correct answer. Is it possible that you're using a different version of ink to compile vs run it or something?

**Comment by dannflor** [comment]
@joethephish Ok I see that Inky is on Ink version 1.0 and I'm running the latest release here of 1.1.1. I updated my Inky and everything is working now. Thank you so much for noticing this. I still think it should return an empty list instead of null so it matches the other tag APIs, don't you?

**Comment by joethephish** [comment]
Yeah, it probably should. Also, it should've been more resilient to the format version change (either handling it correctly or not loading at all).
