### ISSUE TITLE
Read counts after divert

### ISSUE THREAD

**Issue by Fahrengeit** [inkle/ink#85]
Am I right that read counts doesn't increase after divert command from the script in Unity? (Or using Divert function in your Ink Player, as an example)
I understand, that there is some logic in increasing those read counts, but it can be especially frustrating, if you need to divert to some knot or stitch within a script, like from a map. Or maybe I'm missing something?
For now I found a workaround with creating additional stitches "goto_something" that will just divert to "something" and increase that count, but it's still a workaround.

**Comment by joethephish** [comment]
Hrm. That sounds like it could well be a bug! I will take a look! Diverts
from C# side should definitely be counted, and possibly I overlooked that.

**Comment by joethephish** [comment]
As mentioned in #92, this is now fixed in development branch. Will make it into a release build soon!

**Comment by Fahrengeit** [comment]
Yep, thank you very much. Need not to forget to delete all the workarounds I've added :)
