### ISSUE TITLE
Instructions for non-Unity C# environments?

### ISSUE THREAD

**Issue by isakgrozny** [inkle/ink#86]
I'm leaning away from using Unity, as I'd prefer to use MonoGame (which has the benefit of being both free and open-source, unlike Unity), but I'm no great shakes at C# (or programming in general) and I'm finding myself a bit lost on how to implement Ink in MonoGame. 

Any pointers would be very welcome. I'm sure I'm missing something basic here.

**Comment by joethephish** [comment]
So, there are a few steps when you're working outside of Unity. Let me see if I can concisely describe the process in pipeline-order. First, setup:

1. Create an ink file (text file with .ink extension) in a text editor like Sublime Text.
2. Use **inklecate** to compile it. Follow [the instructions](https://github.com/inkle/ink#using-inklecate-on-the-command-line) on the main repo page for doing so on the command line. I'm afraid if you haven't used the command line much before that could be tricky. But it may help to put **inklecate** in the same folder as your source ink. The instructions above describe "play" mode, but to compile to json, just miss out the `-p`. So it should be simply:

    **Mac:** `./inklecate yourFile.ink`
    
    **Windows:** `inklecate.exe yourFile.ink`
    
    (Once you've navigated to the right directory.)
    
3. Include `ink-engine.dll` and `Newtonsoft.Json.dll` in your Xamarin (or Visual Studio project). You'll need to add them as references.

Within your game:

1. Load the JSON as a text file. e.g. `var inkJson = File.ReadAllText("AwesomeGame/yourFile.ink.json");`. 
2. Follow [Running Your Ink](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md). Where you see Unity's `TextAsset` object, instead create the ink story with `var inkStory = new Story(inkJson);`. Anywhere you see Unity's `Debug.Log`, use `Console.WriteLine` instead.

Let us know if you have any problems with any of those steps!

**Comment by lhughes41** [comment]
First, thanks for the above guidance. I am trying to do Python integration. I have made some progress. However I have run into a snag.  The compiled json file that inklecate puts out has some formatting that upsets the json to text Python library I am using.  I know because if I extract the text from the compile .ink.json file and put it in a .json file I have created things are happy but otherwise not. I looked at it  in Word and there are some special characters at the beginning (I am in Windows btw) that vanish in Word when treated as UTC-8.  So my best guess so far is that there is UTC-8 encoding. Is this correct? Anything else? (I am struggling to read even with this guess but wanted to confirm it).
  Thanks!

**Comment by lhughes41** [comment]
OK for those that come after me.. it is indeed UTC-8. However it is a Windows variant for which python needs to open it as 'utc-8-sig'. For example:
with codecs.open(json_file_path, 'r', 'utf-8-sig') as data_file:    
    data = json.load(data_file)

**Comment by lhughes41** [comment]
This took about 8 hours of work and I'm still kind of shocked I pulled it off (I don't know C#).. but here is a code snippet on how to call the Ink Engine from Python!!!!  8-)   
 It looks easy but there were some amazingly obscure aspects.. (at least for me)...
Hope this helps other pythonic folk...
--------------------------------------------------------------------------------
import codecs  # manages encoded json file
import clr     # import the C# ink-engine classes and more into Python via pythonnet library
# pythonnet ->  http://pythonnet.github.io/readme.html

#--------------------------------------  
# Locate the Engine and Story Files
#--------------------------------------
# Engine
ink_dir = "..\\third_party_libs\\ink\\"
ink_engine_filename = "ink-engine"
ink_engine_path = ink_dir + ink_engine_filename
# Story
story_json_filename = "myStory.ink.json"
story_json_file_path = ink_dir + story_json_filename

#--------------------------------------
# Load the Compiled Json
#--------------------------------------
# the json file is utf-8 encoded ( windows variant -sig in Python)
with codecs.open(story_json_file_path, 'r', 'utf-8-sig') as data_file: 
    ink_json = data_file.read()
    
#--------------------------------------
# Create the Ink Story Instance
#--------------------------------------
clr.AddReference(ink_engine_path) #import the ink-engine assembly
import Ink.Runtime
from Ink.Runtime import Story
ink_story = Story(ink_json) #create the instance

# do a test run. Produces "Hello World!"
while ink_story.canContinue: 
    next = ink_story.Continue()
    print next

**Comment by joethephish** [comment]
Oh, wow! That's awesome. Thanks for sharing!

**Comment by lhughes41** [comment]
Aw shucks... On the shoulders of giants :)

**Comment by denfromufa** [comment]
@lhughes41 here is another example using monogame from Python (SadConsole) and packaged into stand-alone executable using pyinstaller: https://github.com/pythonnet/pythonnet/issues/325
