### ISSUE TITLE
Unexpected line break generated by the space between bracket and the arrow

### ISSUE THREAD

**Issue by cyanlink** [inkle/ink#860]
See: https://github.com/inkle/ink-unity-integration/issues/193
It turned out that the culprit is the space between the bracket and the arrow. Such space will be considered as contents! Such spacing is very common amongst other programming languages for formatting purposes.
e.g. :
```
[Option One] -> helloworldknot ->
```
The space after right bracket will be considered a content line, generating a "\n" line in the output JSON.
Possible solution:
ignore empty tokens or tokens containing only invisible characters, do not treat them as content blocks.

**Comment by joningold** [comment]
The ink engine produces empty lines frequently as part of its processing steps; your code should skip them as part of your basic Continue() loop.
