### ISSUE TITLE
Feature Request: Support Manual Input

### ISSUE THREAD

**Issue by 7flash** [inkle/ink#889]
Currently ink allows me to describe chat scenarios where user can choose an answer with button. But now I would like to allow user typing his answer with input field. Then it can compare user message to expected responses to find which one is most similar one, then continue the conversation as it would have been chosen.

Actual comparison can be implemented on external server and available with openai-compatible API https://github.com/outlines-dev/outlines/issues/594#issuecomment-1928793333

The question is: how to trigger API calls with ink?

**Comment by joningold** [comment]
We definitely won’t add this to the core language, but you can achieve this kind of effect using external functions
