### ISSUE TITLE
Translation / localization tips

### ISSUE THREAD

**Issue by Abuki** [inkle/ink#89]
Hello,

We are thinking about using ink in our project. I think we will be able to make all the things we want in ink and it looks really cool. So great work btw.

Just one thing - how would you approach localization? Is there any localized game written in ink? Am I right, that all inkle games are just English? I saw that Banner saga has more languages, but on the website is written, that it was written in inklewriter, not ink.

Thank you

**Comment by joethephish** [comment]
So far we haven't localised any of our ink games, and it's an open question right now I'm afraid!

When we come to it, our preferred solution would most likely be to get localisers to work directly within ink, albeit with some kind of constraints to prevent them breaking the logic. The advantage would be that they’d have the full context of the in-game script, and if they’re at all technical, they might even be able to understand enough of the syntax language-specific branching logic. The disadvantage is of course that we’d have to manage and enforce that process somehow!

I hadn't heard about how Stoic approached it with The Banner Saga actually, so I'd be interested to hear about that!

**Comment by joethephish** [comment]
See also [this issue](https://github.com/inkle/ink/issues/83) about audio / voice over, which is closely related.

**Comment by Abuki** [comment]
Thanks, I was thinking about the same, since extracting separated strings seems to me impossible.

So how would you prevent them from breaking logic? Make some validator, that check the document has the same structure? Or some editor tool for the translator?

**Comment by joethephish** [comment]
Yes, one or both of those options, I think! To be honest, I haven't given it enough serious thought to say either way.

I really like the idea of adding constraints - e.g. make a simple editor that loads the full ink but only makes the text parts editable, or simply validate for the same structure as you say. The main problem is that there are valid cases where the translator might want/need to change the structure very slightly, for example, when doing word swaps based on certain logic, they might want to change the sentence order a bit.

So at that point, I'm not sure what to do - somehow allow a certain, but limited, degree of changes? Perhaps it suggests that validation is the right thing, and then we can choose to accept light logic changes...

**Comment by Abuki** [comment]
When I am thinking about it, I am not sure if the translators will be willing to use our custom editor. Might they be used to use some own tools? Then the validations would be a better idea. Also, it is probably easier to develop. So that might be a way for us.

Can you give me an idea where to start technically with the validator?

**Comment by joethephish** [comment]
Yeah, I think many translators are used to their own tools such as Excel. I think in our case we'd have to find translators who'd be willing to use custom tools so that they could integrate better with our pipeline.

Technically speaking, it's not entirely straightforward I'm afraid! If you want to look into it I'd suggest you make it a mode for the inklecate compiler. The compiler takes the plain ink text, constructs a structured representation of the ink syntax as `Parsed.Object`s, then compiles it down to `Runtime.Object`s before serialising. I'd suggest you take a look at adding a mode that allows it to compare two `Parsed.Object` trees. There's more information on the architecture of the compiler [here](https://github.com/inkle/ink/blob/master/Documentation/ArchitectureAndDevOverview.md).

**Comment by Abuki** [comment]
Thank you very much for the useful info! We are now just in the research phase of the project, but if we will develop something in the future, I will let you know!
In case you would start working on such a feature, I will catch it on twitter right? :)
Thanks again!

**Comment by joethephish** [comment]
Yup, I imagine if we made localisation tools that would be a pretty big deal so we'd probably want to talk about it :)
