### ISSUE TITLE
Can't recall visited choices through C#

### ISSUE THREAD

**Issue by klootas** [inkle/ink#893]
The following always returns 0 for me, regardless whether the choice has been selected before:

`var visitCount = story.state.VisitCountAtPathString(choice.pathStringOnChoice);`

The choices are being selected in a tunnel, but I don't think that matters.
It seems to work using Unity, but not in Godot (where I'm using the standard DLLs of this repository).

**Comment by klootas** [comment]
This was due to the countAllVisits compiler flag not being set while instantiating the Compiler.

**Comment by mttkay** [comment]
Could there be another reason for why this isn't working? @klootas I noticed that godot-ink does set `countAllVisits = true`: https://github.com/paulloz/godot-ink/blob/main/addons/GodotInk/Src/InkStoryImporter.cs#L79

The only knot for which `VisitCountAtPathString()` returns a non-0 value for me is the first knot that is ever visited. Any other knots that I reach through a choice return 0.
