### ISSUE TITLE
Linux builds?

### ISSUE THREAD

**Issue by beeglebug** [inkle/ink#9]
Any chance of a linux build?

**Comment by micabytes** [comment]
In my thoughts as well, though I'm kinda averse to MonoDevelop.

**Comment by joethephish** [comment]
We don't have a linux box, but we'd be interested to hear whether it "just works" with mono already? (We don't really have the capacity to include a binary linux build in the releases, unless someone can find a way to do that from a Mac.)

**Comment by 5310** [comment]
Here is a record of my current experience trying to get the project running on Linux. (Please note that I have no idea what I'm doing to begin with!)

At first I tried to build the project and it did produce the binaries out of the box, but also produced some warning (but no errors.)

I did the following on a fresh Ubuntu vm:
```
sudo apt-get install mono-complete
git clone https://github.com/inkle/ink.git && cd ink
xbuild /p:Configuration=Release ink.sln
```

It created the following output: https://gist.github.com/5310/eca7c5254d18853fb446

Having no experience with Mono/.Net, only then did I realize that Mono projects build the same `.exe` binaries that are cross-platform given the Mono/.Net runtimes, so the binaries already available for download under release should already work on Linux. Or so I thought.

I installed the mono-runtime on my local Ubuntu machine, downloaded the Windows release and extracted the three files `inklecate.exe`, `ink-engine.dll`, and `Newtonsoft.Json.dll` to a directory and copied over the tutorial test game. 

But it failed to run with the following error:
```
$ mono inklecate.exe -p tutorial.ink 

Unhandled Exception:
System.TypeLoadException: Could not load type 'Ink.InkParser' from assembly 'inklecate, Version=1.0.5914.28194, Culture=neutral, PublicKeyToken=null'.
  at Ink.CommandLineTool.TimeOperation (System.String opDescription, System.Action op) [0x00000] in <filename unknown>:0 
  at Ink.CommandLineTool..ctor (System.String[] args) [0x00000] in <filename unknown>:0 
  at Ink.CommandLineTool.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'Ink.InkParser' from assembly 'inklecate, Version=1.0.5914.28194, Culture=neutral, PublicKeyToken=null'.
  at Ink.CommandLineTool.TimeOperation (System.String opDescription, System.Action op) [0x00000] in <filename unknown>:0 
  at Ink.CommandLineTool..ctor (System.String[] args) [0x00000] in <filename unknown>:0 
  at Ink.CommandLineTool.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Next I went back to my vm and ran the same tutorial game from the freshly built binaries. But there it worked! :D
```
$ mono ./inklecate/bin/Release/inklecate.exe -p tutorial.ink 

I looked at Monsieur Fogg
1: ... and I could contain myself no longer.
2: ... but I said nothing

```

That's as far I've gotten until now. Not sure what the difference is between the binaries built inside the vm and downloaded locally. I'm probably missing some of the dependencies, but I don't yet know how to fix that yet. Will read up about it more.

**Comment by 5310** [comment]
Followup: Inklecate wasn't failing to run because of any missing project dependencies but because of missing Mono runtime dependencies. 

Installing the full compliment of packages with `mono-complete` on my local machine instead of just `mono-runtime` allowed me to run the game.

**Comment by joethephish** [comment]
Thanks! I'm very far from a Mono/C# expert, so I have no idea of how these different mono runtimes compare. Is it that the `mono-runtime` is absolutely bare bones with no .NET libraries at all I wonder? Anyone know?

**Comment by micabytes** [comment]
Thanks for taking that bullet, @5310 .

`mono-runtime` contains a bunch of dependencies, but not the mono-system-core. With the core installed, it works perfectly, and it's easy enough to run the windows package as @5310 describes. Tested on an ubuntu trusty 14.04 install.

**Comment by joethephish** [comment]
Great! So broadly speaking, for future releases, we should just be able to rename the windows release zip so that it's simply the same build for both windows and linux then, right? And then just add instructions for Linux to the documentation.

Anyone fancy submitting a pull request for a documentation update, that mentions the `mono-complete` dependency?

**Comment by micabytes** [comment]
Sure.

**Comment by joethephish** [comment]
Thanks, all done!
