### ISSUE TITLE
Adding Ink to nuget

### ISSUE THREAD

**Issue by ncthbrt** [inkle/ink#90]
Just wanted to ask if it is ok if I create a fork and add ink to nuget. This would make development for non unity environments much easier.

**Comment by joethephish** [comment]
Sounds sensible. Perhaps it's something we should do so that inkle's name is attached to it? Is it straightforward?

**Comment by ncthbrt** [comment]
Pretty straight forward. I'll submit a pull request once I've made the requisite changes. Just a quick question, are the Nunit tests being run automatically somewhere? A few tests were failing, including the includes and nested include tests because the working directory for the test runner in VS is the solution folder not the test directory.

Btw are you running windows? I'd like to make the nuget package project use the dotnet cli and the new project formats but the support for linux and mac tooling is a little bit behind. With the cli, building and packaging is a lot easier, but I don't mind using the old format if you feel that it is too much hassel.

**Comment by ncthbrt** [comment]
Ok. So travis is now happy. So now that we have a project which can generate a nupkg, there are a few options. I read that Travis supports secret encryption based on repo. So publishing a build to nuget could be part of the build process, perhaps checking whether it is a tagged release. An alternative could be that a package maintainer uploads to nuget in step with the tagged release cadence this is fairly simple and what I usually do for my company's packages.

**Comment by joethephish** [comment]
Hrm. So, if this was automatic, it would definitely help things out. It's already *slightly* complicated for us to do new ink releases already, since we have to release both an ink version and an ink-unity-integration version, and upload the latter to the Unity Asset Store. So fewer manual steps would definitely be appreciated! Broadly speaking though, I'm more than happy to have ink on nuget, assuming we can make the process straightforward :)

**Comment by ncthbrt** [comment]
I need to better understand how travis works, but I believe (according to this doc https://docs.travis-ci.com/user/deployment/releases) that nuget releases and other release scripts can be triggered when you add a release tag. I need to better understand secret management and whether the dotnet cli could be installed on travis. For now it is easy enough to create an artifact you can upload, you just call `dotnet restore` and then `dotnet pack` in the ./ink-engine-nuget/Inkle.Ink.Engine folder and it'll create a nuget artifact.

**Comment by joethephish** [comment]
Ooh, reading that Travis page, it sounds like we could even automate my existing release procedure, which would be great. I haven't really looked into dotnet - has it only recently been released for Mac? I'm not sure of the differences between it and Mono...

**Comment by ncthbrt** [comment]
It is still under heavy development, but once mature, it seems likely that it will become the predominant way of developing cross platform applications and libraries in C#. You can find more information here (https://get.asp.net).

**Comment by spinda** [comment]
It's been a while, could this still be done? I'm integrating ink into a non-Unity project right now and this would be quite helpful.

**Comment by ncthbrt** [comment]
Available at https://www.nuget.org/packages/Inkle.Ink.Engine/
