### ISSUE TITLE
[Discussion] Inky: An ink IDE

### ISSUE THREAD

**Issue by joethephish** [inkle/ink#95]
Hey all!

I've been working on an ink IDE. Here are a couple of GIFs of it in action.

The first shows the general editor flow: (full length version [here](http://recordit.co/VZV93ZQlFq) - the GIF seems to cut out:

![vzv93zqlfq](https://cloud.githubusercontent.com/assets/858967/15656746/4369be66-26a2-11e6-9456-0285f755609d.gif)

While the second GIF shows the error fixing flow, and the jump to definition feature (which is hard to see since the screen capture tool didn't capture the cursor changing - you alt-click on an underlined symbol to jump to its definition):

![px9lbxi0q3](https://cloud.githubusercontent.com/assets/858967/15656750/464b66f2-26a2-11e6-9eea-faddbe198950.gif)

I'm building it in [Electron](http://electron.atom.io/), so although I'm just building a Mac version for now, it should be pretty straightforward to fix up any Windows-specific issues. We (inkle) will release it open source, so hopefully that'll happen soon enough with the help of community contributions!

Hopefully I'll be releasing it within a few weeks.

**Comment by joethephish** [comment]
And here's a demo of include files:

![eguvp9yhr2](https://cloud.githubusercontent.com/assets/858967/15656994/d650e8e2-26a4-11e6-8298-8437512f2043.gif)

**Comment by elhomosiguiente** [comment]
I ll be porting a draft story to Ink the next month I hope. if it is what a think, will help. I like Ink syntax

**Comment by Horatio-Blackwood** [comment]
This is cool.  Can't wait to try it out.

**Comment by joethephish** [comment]
Mac version out now! Looking for help with porting to other platforms: https://github.com/inkle/inky

**Comment by Fahrengeit** [comment]
Trying Windows version right now. Looks very cool. I think I won't need Sublime anymore :)

Found yet only one error - it happens after Help - Learn more.
And I'm looking at highlighting, it has some issues in different situations.

`"Well, here {!variable: I go|it goes}."`
Everyone, I suppose, knows, that if you want start a variable text with negation, you should use "not", so you won't mix it with Once-only list. Maybe it's better not to highlight "variable:" in that case, so user will know that it won't work how he expects.

`"Well, here {not variable || anything: I go|it goes}."`
Logical operator || doesn't highlight correctly in variable text, Inky thinks that this one is operator of list and breaks highlighting though in runtime it works fine as logical operator. 

I hope it helps in some way.

**Comment by joethephish** [comment]
Thanks - well found. Argh, those are hard things to deal (in a regex grammar-based syntax highlighting system as opposed to a full featured parser) with because of the ambiguity. It's perfectly valid to have sequences with empty elements, e.g. `{first|second||fourth}`.

It's almost an argument to remove all punctuation based boolean boolean logic operators in favour of `and`, `or` and `not`! And the once-only thing is a genuine ambiguity. Thoughts @joningold?

**Comment by Fahrengeit** [comment]
Yeah, I know what are you talking about. First when I've downloaded Ink I didn't notice that you've uploaed Sublime language and font, so I've spend some evenings on my own (and I didn't know how to write sublime language and regex wasn't a thing I've known well). I wanted to make highlighting of language operators and text keep in black font. So I've had issues with sequences and operators too.
So, I think you can highlight "|" everytime if in branches, but when you'll meet combination of "||" between "{" and ":" then it should override previous highlighting with condition. 
I have my realization for Sublime, but I don't know if it will really help - it can differ a lot from your realization (and it is one big messy expression).
