### ISSUE TITLE
Imported type 'NewtonSoft.Json.JsonSerializerSettings' is defined multiple times.

### ISSUE THREAD

**Issue by cenewsom1** [inkle/ink#96]
Hi, I've just started working with Unity and Ink the past two months and have been trying to integrate Ink with a UI system that some coworkers of mine had developed a while back. Whenever I import Ink packages, I get the compiler error:

Imported type 'NewtonSoft.Json.JsonSerializerSettings' is defined multiple times.

I don't get this whenever Ink is not part of my library, and trial-and-error deletion has the error go away after deleting Newtonsoft.Json. Seeing as this isn't a viable solution, is there any way to use them together?

**Comment by joethephish** [comment]
So, as you have probably gathered, `Newtonsoft.Json.dll` is a library for serialising to and from JSON that's used by ink, and by your coworkers' UI system. We ship ink with a copy of the DLL, so it sounds like you've ended up with two copies of the DLL in your project. You should simply be able to remove one of the DLLs (e.g. `Plugins/Ink/Inklecate/Newtonsoft.Json.dll`) and all will be well!

**Comment by joethephish** [comment]
Note that we've removed our dependency on Newtonsoft.Json.dll in our [latest release](https://github.com/inkle/ink/releases/tag/0.4.0), so this shouldn't be a problem anymore.
