### ISSUE TITLE
[Question] Formal grammar specification

### ISSUE THREAD

**Issue by ncthbrt** [inkle/ink#97]
Hi again,
I was wondering if there is by any chance a formal grammar specification lying around somewhere for the ink.
I am interested in building some tooling, and it would be really handy to have the formal grammar available. It would also make ports somewhat easier

**Comment by joethephish** [comment]
I'm afraid there isn't a formal spec, no. Have you tried looking at the `InkParser` code to see how readable it is? The parser is hand-written, but it was designed to be written a bit like a declarative grammar interspersed with the code that actually constructs the parsed hierarchy of objects.

**Comment by ncthbrt** [comment]
I'll give it the parser a read when I have the chance. Thank you. I'll post a pull request with the grammar in the docs once I have something I'm happy with.

**Comment by joethephish** [comment]
That would be awesome, thanks!
