### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by y-lohse** [inkle/ink#99]
Hi,
just noticed a bit in the docs that is outdated, [over here](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#exernal-functions). It says to bind external functions before `story.Begin()` but that method doesn't exist. I'm guessing it's before `Continue` or something like that.

**Comment by joethephish** [comment]
Good catch, thanks! (You used to have to call `Begin` after constructing the `Story` and before calling `Continue` for the first time, but I managed to roll the functionality into the constructor.)
